.gitignore

A next batch of ignored files comes from running `make test`.

.gitignore: ignore temporary test files

---

Makefile.in

Coincidentally, default GitHub CI environment contains libsqlite.so library in place, which hid the fact that Rust tests fail to prefer the locally built library. The tests were previously effectively verifying that the library from system path is correct, which is also nice, but not the desired effect. The amended rusttest command correctly prefers locally build libraries.

test: link to correct library in Rust tests

---

doc/libsql_extensions.md
src/build.c
src/insert.c
src/parse.y
src/sqliteInt.h
src/vdbe.c
test/rust_suite/src/lib.rs
test/rust_suite/src/random_rowid.rs
tool/mkkeywordhash.c

With the new RANDOM ROWID keywords, a table can explicitly state that it wants its rowid to be generated randomly, not consecutively, without having to previously create a sentinel record with rowid == max(i64).
RANDOM ROWID is mutually exclusive with WITHOUT ROWID,
and cannot be combined with AUTOINCREMENT primary key.
This series come with tests.
Fixes #12

Add RANDOM ROWID keywords

---

ext/wasm/GNUmakefile
ext/wasm/fiddle.make

In addition to compiling with -Os and stripping the binary, an extra round of post-process optimization is optionally run with the help of Binaryen's wasm-opt utility.
With the additional pass, the resulting binary size drops from 3.1MiB to 792K, which is almost a 75% reduction.

wasm: post-process optimize for smaller module size

---

ext/wasm/fiddle/serve.py

In order to experiment with Origin-Private File System (OPFS), certain HTTP headers need to be sent from the server to opt-in into newest features. It's also advised to run bleeding-edge Chrome, e.g. version 108 seems to support all of it. To make development easier, a simple server which adds the required headers is added in fiddle/ directory.

fiddle: add a small Python server for COOP/COEP

---

.github/workflows/makewasm.yml

The workflow builds the Wasm extension in release mode with emscripten.

CI: add ext/wasm extension test

---

ext/wasm/fiddle/fiddle-worker.js
ext/wasm/fiddle/fiddle.js
ext/wasm/fiddle/index.html

This commit switches the default view from split to terminal. The scripts are now fetched from cdnjs.com, which is expected to be generally available for the time being.

fiddle: default to terminal view, scripts hosted by cdnjs.com

---

configure
configure.ac

If --enable-readline option is passed to configure, but no readline support is found, previous behavior was to silently continue and not enable readline support. The new behavior is to error out if readline was explicitly enabled, but there's no library that provides it. Users are expected to either drop the --enable-readline flag or install the missing dependency.
#65

configure: error if readline not found, but requested explicitly

---

src/shell.c.in

Flushing the buffer on each new entry makes iotrace much more useful for debugging interactive sessions.

iotrace: flush on each entry

---

src/shell.c.in

The distinction will make it abundantly clear that the user is running libSQL.

shell: shameless rebranding of the default prompt

---

Makefile.in
tool/generate-artifacts.sh
tool/pre-release.sh

The scripts are meant to be run during releases
in order to automate producing artifacts, like
precompiled binaries and the amalgamation files.

Add scripts for creating release artifacts

---

Dockerfile-wasm-udf

Our Dockerfile suffered from bitrot after LIBSQL_VERSION file was introduced - let's fix.

docker: add LIBSQL_VERSION to docker image

---

doc/libsql_extensions.md
ext/vwal/vwal.c
src/attach.c
src/btree.c
src/btree.h
src/build.c
src/loadext.c
src/main.c
src/pager.c
src/pager.h
src/shell.c.in
src/sqlite.h.in
src/sqlite3ext.h
src/sqliteInt.h
src/test2.c
src/test3.c
src/vdbe.c
src/wal.c
src/wal.h
test/rust_suite/Cargo.lock
test/rust_suite/Cargo.toml
test/rust_suite/src/lib.rs
test/rust_suite/src/random_rowid.rs
test/rust_suite/src/virtual_wal.rs

This preparatory commit moves all WAL routines to a virtual table.
Also, a helper libsql_open() function is provided. It allows passing
a new parameter - name of the custom WAL methods implementation.

Virtualize WAL methods

---

doc/libsql_extensions.md

Enhance documentation by describing the new xPreparedSql callback for virtual tables. Refs #87

Document xPreparedSql virtual table callback

---

src/wal.c

add args names to libsqlPreMainDbOpen so gcc stops complaining.
This prevents building in debian for me

libsqlPreMainDbOpen: add args names

---

src/rust/wasmtime-bindings/Cargo.toml

This PR adds the `[workspace]` directive to the `Cargo.toml` for the rust wasm crate. This is for when libsql is built from within a cargo workspace, so cargo undertand that this crate is in fact part of its own workspace.

add workspace to rust crate

---

src/rust/wasmtime-bindings/src/lib.rs

replace `*const i8` with `*const c_char` to make the crate more portable

replace *const i8 with *const c_char where necessary

---

src/page_header.h
src/pcache.h
src/wal.h
tool/mksqlite3h.tcl

It was reported on Discord that the amalgamation file only includes libsql_wal_methods as an opaque type, which is not easily consumable, especially for projects which automatically generate bindings to other languages.
This issue was an oversight, rooting from the fact that our Rust bindings were simply written from scratch. And while we still intend to add official Rust bindings, virtual WAL methods should be included in the amalgamation sqlite3.h file, so that they can be easily consumed by other languages.

wal: include relevant virtual WAL headers in sqlite3.h

---

src/pager.c
test/rust_suite/src/lib.rs
test/rust_suite/src/virtual_wal.rs

It's reasonable to assume that a database open with custom WAL methods should default to WAL journaling mode.
This commit comes with an updated test which ensures that the database is open in WAL mode without having to resort to calling `PRAGMA journal_mode=wal` manually.

Use WAL journaling mode by default if custom WAL methods are specified

---

Makefile.in
tool/mksqlite3c.tcl

... so that it's properly taken into account during the creation of sqlite3.{c,h} amalgamation files.

build: register page_header.h as a new header

---

src/loadext.c
src/sqlite.h.in
src/sqlite3ext.h

Following the suggestion from #101, libSQL-specific extension API is split to a separate structure in order to avoid compatibility issues once new API entries are added to SQLite.
Fixes #101
Solution suggested by @thomcc
Smoke-tested with https://github.com/libsql/bottomless extension

ext: split libSQL extension API to a separate struct

---

src/pager.c

That makes the behavior consistent with how this code used to work
- if there are no pages in WAL (e.g. an empty database), opening WAL is deferred.

pager: do not open an empty WAL

---

README.md

From Abdur's feedback, it is important to justify the fork right in the README instead of just pointing to the motivation page. So bring some of the text - with adaptations for the README format - from the motivation page back.
We have also heard feedback that the file compatibility claim is not clear enough regarding future extensions like CRC that may require file modifications, so clarify that as well.

clarify README

---

src/pager.c
test/rust_suite/src/lib.rs
test/rust_suite/src/virtual_wal.rs

The code that automatically set WAL mode in connections that define custom WAL methods is broken - let's revert it asap, and then debug.

Revert auto-WAL detection

---

src/sqliteInt.h
tool/mksqlite3c.tcl
tool/mksqlite3h.tcl

The amalgamation files now properly include the contents of wasm_bindings.h header.

src,tool: fix including ext/udf/wasm_bindings.h in the amalgamation

---

src/build.c
src/rust/wasmtime-bindings/Cargo.lock
test/rust_suite/src/user_defined_functions.rs

The call is idempotent, so it's safe to just run it on each CREATE FUNCTION, which is a rare operation in the first place.
Fixes #123

build: initialize Wasm func table before CREATE FUNCTION

---

Makefile.in
configure
configure.ac

The switch between static and dynamic linking is especially important in the context of "make libsql" or "make sqlite3". Without default static linking, running the shell fails out of the box, which results in poor DX.

build: bring back enable-wasm-runtime-dynamic

---

.github/workflows/maketestwasm.yml
.gitignore
Makefile.in
configure
configure.ac
ext/udf/wasmedge_bindings.c
src/rust/wasmtime-bindings/src/lib.rs
test/rust_suite/Cargo.toml
test/rust_suite/src/lib.rs
test/rust_suite/src/user_defined_functions.rs
test/rust_suite/src/user_defined_functions_src.rs
test/rust_suite/src/virtual_wal.rs
tool/mksqlite3c.tcl

Depends on having libwasmtime.so installed,
which can be done e.g. manually by compiling from source
and invoking `make install` later.
WasmEdge may not come with wat2wasm capabilities - in which case
only binary input will be accepted. That's still a very good
deal, because WasmEdge's slim runtime weighs just ~1.5MiB.
Tests need to be amended to fall back to using binary blobs
if wat2wasm is not available.
Fixes #94

udf: add WasmEdge bindings

---

doc/libsql_extensions.md

A short paragraph mentions multiple Wasm configurations and explains the quirks of the new WasmEdge backend.

docs: mention WasmEdge backend

---

src/shell.c.in
src/sqlite.h.in
src/vdbe.c
src/vdbeInt.h
src/vdbeapi.c
test/rust_suite/Cargo.lock
test/rust_suite/src/lib.rs

The stats are gathered in order to estimate how many rows were accessed when executing a statement.
While similar metrics already exist - like fullscan steps and VM steps - they are not always 1:1 with the number of rows touched in the process. The built-in count() aggregate is one of the exceptions. It technically does not read rows, but instead iterates over B-Tree pages, but it's asymptotically the same.
For writes, sqlite3_changes() function already exists and informs how many rows were affected by the most recent insert/update/delete, but it does not count triggers, replaces, etc into account.
Example output:
```
$ ./libsql /tmp/x < /tmp/test_paylod | grep Rows
Rows read:                           4602
Rows written:                        0
Rows read:                           4602 …
```

metrics: add LIBSQL_STMTSTATUS_ROWS_READ and _WRITTEN

---

.gitignore
src/rust/libsql-shell/Cargo.toml
src/rust/libsql-shell/README.md
src/rust/libsql-shell/src/main.rs

This commit adds an initial version of the new libSQL shell. It still misses lots of features, but it's already functional.
Example:
```
$ ./libsql
libSQL version 0.2.0
Connected to a transient in-memory database.
libsql> create table test(id, v); 
libsql> insert into test values(42, zeroblob(12));
libsql> insert into test values(3.14, 'hello');
libsql> insert into test values(null, null);
libsql> select id, v, length(v), hex(v) from test;
id   | v                  | length(v) | hex(v)    
------+--------------------+-----------+--------------------------
42   | 0xAAAAAAAAAAAAAAAA | 12        | 000000000000000000000000 
3.14 | hello              | 5         | 68656C6C6F    
null | null               | null      |    
libsql>
```

libsql-shell: initial commit

---

src/build.c
src/parse.y

In order to keep the grammar definition identical between Wasm and non-Wasm builds, let's support CREATE FUNCTION syntax uncondtionally - it will simply inform the users that user-defined functions support wasn't compiled in, if it wasn't.

parse: unconditionally support CREATE FUNCTION in the grammar

---

src/wal.c

This PR fixes #144. Commit 519a33b changed the function signature of `sqlite3_snapshot_cmp` which causes a compiler error when compiled with `-DSQLITE_ENABLE_SNAPSHOT`
Reverting this function signature back to `int sqlite3_snapshot_cmp` clears up the compiler error.
I've rebuilt this locally and done a `make test` and all the tests pass.
```
% grep SNAPSHOT Makefile
OPT_FEATURE_FLAGS =  -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_SNAPSHOT
% make test
Time: snapshot.test 19 ms
Time: snapshot2.test 11 ms
Time: snapshot3.test 5 ms
Time: snapshot4.test 5 ms
Time: snapshot_up.test 6 ms
SQLite 2023-04-19 20:29:26 …
```

revert signature change of sqlite3_snapshot_cmp

---

.gitignore
ext/udf/wasm_bindings.h
ext/udf/wasmedge_bindings.c
src/main.c
src/rust/wasmtime-bindings/Cargo.toml
src/rust/wasmtime-bindings/src/lib.rs

The leak was quite obvious - there was no destructor for the per-connection Wasm engine.

udf: fix memory leak for libsql_wasm_engine_new

---

doc/libsql_extensions.md
src/btree.c
src/main.c
src/pager.c
src/pager.h
src/sqlite.h.in
src/sqliteInt.h
src/test2.c
test/rust_suite/src/virtual_wal.rs

Adds the ability to pass user context to the WAL methods. The user_context is passed as the 7th argument to the `libsql_open_v2` function and is passed down to the first instantiation of the WAL struct, which happens in a call to `pagerOpenWal`. If the WAL struct is successfully allocated, then the pointer to the user data is installed in the WAL struct, where it becomes available to the wal_methods

add user context pointer to sqlite3 struct

---

src/vdbe.c

They were not taken into account in the original patch, because virtual tables use a separate opcode for reads.

vdbe: count virtual table reads in ROWS_READ metrics

---

.github/release-drafter.yml
.github/workflows/publish-release.yml
.github/workflows/release-drafter.yml

See the generated artefacts at https://github.com/libsql/libsql-dev/releases/tag/v0.1.39
The new release flow will be as follows: 
- On a push to main, a new tag will be created as a release draft, the tag is autogenerated based on the current largest tag in the repo, e.g. with 0.2.1 right now, the new one will be 0.2.2. This will be a draft release, and every PR pushed to main will be added to the draft. 
- Once we are ready to release, edit the draft release (change the tag if the automatic one isn't right) and hit the "publish" button. 
- This will create a release with the given tag and autogenerated note, and trigger a workflow that builds the artefacts.
- The workflow creates an aarch64 AWS VM, and also uses our self hosted linux and mac machines. 
- As each build completes it will …

release pipeline for linux x86_64, aarch64, darwin arm64

---

.gitignore
Makefile.in
src/rust/libsql-sys/Cargo.toml
src/rust/libsql-sys/build.rs
src/rust/libsql-sys/src/lib.rs

The official bindings are generated with
`make rust_bindings`, and are based on the current sqlite3.h header file.

rust: add Rust bindings

---

src/vdbe.c
test/rust_suite/src/lib.rs

Inserts and index inserts are now always counted, even if they are internal writes, e.g. ones that are incurred by schema changes.

vdbe: fix ROWS_WRITTEN metrics

---

crates/core/Cargo.toml
crates/core/src/connection.rs
crates/core/src/database.rs
crates/core/src/errors.rs
crates/core/src/rows.rs
crates/core/src/statement.rs

With the new layout in place, the code can rely on a local `../libsql-sys` dependency

crates/core: update to newest libsql-sys

---

crates/core/benches/benchmark.rs
crates/core/src/statement.rs

Lift the unconditional call to `sqlite3_reset()` to its own method to avoid calling it for single-shot queries.

libsql/core: Add Statement::reset() method

---

crates/core/src/rows.rs
crates/core/src/statement.rs

This implements Drop trait for the Statement struct to clean up after ourselves once we no longer need the statement. One complication is that Rows also holds a reference to the sqlite3_stmt object, which is why I introduced a StatementInner. We can probably make this cleaner, but that's for later.

libsql/core: Implement Drop for Statement

---

crates/core/src/errors.rs
crates/core/src/lib.rs
crates/core/src/raw.rs
crates/core/src/rows.rs
crates/core/src/statement.rs

Let's avoid using the libsql_sys wrappers everywhere and instead add a raw API layer between the high-level API and the FFI bindings. I am exposing this as a public interface too so applications that want more control can just use it.

Add raw API to libSQL core

---

crates/.gitignore
crates/core/examples/from_snapshot.rs
crates/core/examples/replica.rs
crates/core/src/database.rs
crates/core/src/errors.rs
crates/core/src/lib.rs
crates/libsql-sys/src/connection.rs
crates/replication/src/lib.rs
crates/replication/src/replica/snapshot.rs

Two things are now possible:
1. Syncing frames from a snapshot file produced by sqld, e.g. with `cargo run -- --max-log-duration 1`
2. Using `let mut db = Database::with_replicator(path)` in order to create a database, on which you can then call `sync(frames)` to load new frames. No need to instantiate a separate `Replicator` anymore

Replication: iteration 2

---

crates/replication/src/replica/hook.rs

The pre and post commit hooks are already Send in
InjectorHookCtx::new(), but let's not lose the types when we store them in the struct.

libsql/replication: Fix InjectorHook {pre,post}_commit types

---

.github/workflows/maketest.yml
crates/Cargo.toml
crates/bindings/wasm/Cargo.toml
crates/bindings/wasm/README.md
crates/bindings/wasm/example.js
crates/bindings/wasm/src/lib.rs

We want to be able to build libSQL API as wasm module for serverless deployments. Let's add enough wasm binding scaffolding to avoid painting ourselves into a corner.

libsql: Add wasm bindings scaffolding

---

crates/core/Cargo.toml
crates/core/examples/from_snapshot.rs
crates/core/examples/replica.rs
crates/core/src/database.rs
crates/replication/src/lib.rs
crates/replication/src/replica/hook.rs

This very crude draft hooks gRPC replication into the replication crate. The underlying interface is asynchronous, so we're likely to end up relying on Tokio for replication anyway.

replication: add gRPC-based replication

---

crates/replication/Cargo.toml
crates/replication/build.rs

Let's use the `protobuf-src` crate to remove the dependency to external `protoc` to simplify the build process.

libsql: Remove external `protoc` dependency

---

crates/core/src/errors.rs
crates/core/src/rows.rs
crates/core/src/statement.rs

We need to return the human-readable error message in `Error::PrepareFailed` so that language bindings can show it.

libsql/core: Improve error handling

---

src/main.c
src/sqlite.h.in
src/sqliteInt.h
test/rust_suite/src/lib.rs
test/rust_suite/src/user_defined_functions_src.rs

The callback allows registering a custom close hook, which gets called prior to closing the connection, allowing users to perform custom cleanups.
Fixes #62

add sqlite3_close_hook

---

test/rust_suite/src/lib.rs

rust_suite: add a test for accounting rows read with DESC order

---

crates/replication/Cargo.toml

That makes a transient dependency of openssl-sys go away. openssl-sys is great and battle tested, but also less portable.

replication: move to rustls

---

Makefile.in

Lucio pointed out that we're missing `--all`.

Fix `libsqlapi` target to run all the tests

---

crates/core/src/params.rs
crates/core/src/statement.rs
crates/core/tests/integration_tests.rs
crates/libsql-sys/src/statement.rs

This adds basic named parameter support via `Vec<(String, Value)>`.
Ref #187

libsql/core: Add named parameter support

---

crates/bindings/c/src/lib.rs
crates/bindings/wasm/src/lib.rs
crates/core/Cargo.toml
crates/core/src/connection.rs
crates/core/src/errors.rs
crates/core/src/lib.rs
crates/core/src/params.rs
crates/core/src/rows.rs
crates/core/src/statement.rs
crates/libsql-shell/src/main.rs
crates/libsql-sys/build.rs
crates/libsql-sys/src/connection.rs
crates/libsql-sys/src/statement.rs
crates/libsql-sys/src/value.rs
crates/wasmtime-bindings/src/lib.rs

Draft for now, since I'm actively working on migrating sqld on top of the new interfaces. Only once both work, I'll proceed with this PR.

crates/core: add ValueRef and Column

---

crates/bindings/c/include/libsql.h
crates/bindings/c/src/lib.rs
crates/bindings/c/src/types.rs
crates/core/src/connection.rs
crates/core/src/params.rs
crates/core/src/rows.rs
crates/core/src/statement.rs
crates/core/tests/integration_tests.rs

This adds blob type support and ensures the lifetime handed out from statements is valid.
Ref #187

libsql/core: Add blob type support

---

crates/core/src/connection.rs
crates/core/tests/integration_tests.rs

We already clean up after dangling statements in `libsql_sys::Statement` by implementing `Drop`. However, in cases where `Connection` drops before the statements, we will SIGSEGV because statements don't know about the auto-closing.

libsql: Fix SIGSEGV when `Connection` is dropped before statements

---

crates/core/examples/replica.rs
crates/core/src/database.rs
crates/replication/Cargo.toml
crates/replication/proto/replication_log.proto
crates/replication/src/client.rs
crates/replication/src/generated/wal_log.rs
crates/replication/src/lib.rs
crates/replication/tests/bootstrap.rs

This commit moves us from http based replication endpoints to gRPC based ones.
This also includes `h2c` upgrade code due to our hosting not doing proper ALPN negotiation.

libsql/replication: Move to gRPC based endpoints

---

crates/core/src/connection.rs
crates/core/src/rows.rs
crates/core/src/statement.rs

The parameter was really redundant, given that Connection just wraps over an already thread-safe pointer.
Important: what we "lose" here is that statement lifetimes are no longer tied to the connection, but they in fact never were, because nobody prevented calling a `disconnect()` on a connection, which will just free the underlying pointer.
Note that if/when we decide that a `Connection` should clean up after itself and close the raw connection it points to, we'll need to wrap the pointer in an internal `Arc`.

connection: drop the lifetime parameter

---

crates/replication/src/lib.rs

We should start asking for offset 0, not 1. Our internal numbering for frames starts with 0 (and SQLite's starts with 1, hence the confusion).

replication: fix off-by-one error

---

crates/replication/proto/replication_log.proto
crates/replication/src/generated/wal_log.rs
crates/replication/src/lib.rs

The LogEntries RPC is stream-based, which doesn't really work for the `sync()` API we have. Switch to the new BatchLogEntries RPC introduced by Lucio.

libsql/replication: Switch to BatchLogEntries RPC

---

crates/bindings/c/src/lib.rs
crates/core/src/connection.rs
crates/core/src/errors.rs
crates/core/src/rows.rs
crates/core/src/statement.rs

The JavaScript language bindings, for example, need a function for executing a SQL statement and getting the number of changed rows back. The rusqlite `execute()` function does just that so let's fix our function signature to be compatible.
Fixes #246

libsql/core: Fix Statement::execute() signature

---

crates/core/src/params.rs

We can't use `Params` type directly because that requires any caller of the macro to also pull it in.

libsql/core: Fix params and named_params macros

---

crates/core/examples/replica.rs
crates/core/src/database.rs
crates/replication/src/lib.rs

This commit adds gRPC auth for replication based endpoints by using `x-authorization` header.

libsql/replication: Add gRPC auth

---

doc/libsql_extensions.md
src/alter.c
src/parse.y
src/sqliteInt.h
test/rust_suite/src/alter_column.rs
test/rust_suite/src/lib.rs
test/rust_suite/src/update_column.rs

This draft extends SQL syntax in libSQL by allowing one to redefine a column declaration, e.g. by adding/removing a constraint, or changing the type affinity.
Examples:
```sql
libsql> CREATE TABLE t(id, v);
```
```sql
libsql> ALTER TABLE t ALTER COLUMN v TO v NOT NULL CHECK(v < 42);
libsql> .schema t
CREATE TABLE t(id, v NOT NULL CHECK(v < 42));
```
```sql
libsql> ALTER TABLE t ALTER COLUMN v TO v TEXT DEFAULT 'hai';
libsql> .schema t
CREATE TABLE t(id, v TEXT DEFAULT 'hai');
```
```sql
libsql> ALTER TABLE t ALTER COLUMN v TO v;
libsql> .schema t
CREATE TABLE t(id, v);
```
Fixes #43

Add ALTER TABLE ALTER COLUMN statement

---

crates/bindings/c/src/lib.rs
crates/core/src/params.rs
crates/core/src/rows.rs
crates/libsql-sys/src/statement.rs

`*const i8`/`*mut i8` was passed in a bunch of places where `*const c_char`/`*mut c_char` was expected which didn't compile on Linux on aarch64.

Fix compilation errors on platforms with unsigned chars

---

crates/core/src/connection.rs
crates/core/src/errors.rs
crates/core/src/lib.rs
crates/core/src/params.rs
crates/core/src/statement.rs
crates/core/tests/integration_tests.rs

This commit moves our usage of `Into<Params>` to `TryInto<Params` to enable users to have fallible conversions from their custom params type into a libsql's params type. This is a small step in the right direction for full rusqlite params support.

libsql/core: Switch to TryInto for params

---

crates/core/src/errors.rs
crates/core/src/statement.rs

Add result code to `Error::PrepareFailed` so that it's available to the user code.

libsql/core: add error code to Error::PrepareFailed

---

crates/core/src/statement.rs
crates/libsql-sys/src/statement.rs

We need to use sqlite3_column_decltype() like rusqlite does because it returns the type of the column in the result set whereas sqlite3_column_type() returns the type of the current row.

libsql/core: Fix Column::decl_type()

---

crates/libsql-shell/Cargo.toml
crates/libsql-shell/src/main.rs

Simple implementation of tab completion logic based on interfaces provided by rustyline. List of commands to complete is hardcoded but I guess we could put list of all commands in some shared variable and reuse it where needed.

libsql/shell: commands completion

---

crates/core/src/statement.rs
crates/libsql-sys/src/statement.rs

Extend the rusqlite column API to cover more of the SQLite C API. Needed for better-sqlite3 wrapper.

Column API improvements

---

crates/core/src/errors.rs
crates/core/src/rows.rs
crates/core/src/statement.rs

* Add error code to `FetchRowFailed`
* Use full error message in `FetchRowFailed`
* Use extended error codes in all errors
As a further improvement, it would probably be better to use https://www.sqlite.org/c3ref/extended_result_codes.html to get extended result codes directly instead of retrieving the extended error codes with a separate function call.

libsql/core: add code to FetchRowFailed and use extended error codes

---

.github/workflows/golang-bindings.yml
.github/workflows/maketest.yml
.github/workflows/maketestwasm.yml

Let's use an unique name for each task so that we can configure Github actions to check that they all pass before merging.

Fix Github actions workflow names

---

crates/bindings/c/src/lib.rs
crates/core/src/rows.rs
crates/core/src/statement.rs
crates/libsql-sys/src/statement.rs

`column_names` now returns `Option<&str>` instead of segfaulting when the provided index is not valid.

libsql/core: `column_names` return `Option<&str>`

---

crates/core/src/rows.rs
crates/core/src/statement.rs

Revert the change introduced by 77c8b71481ebac0dbfa928f5c108fcd00d64ed81. It caused a wrong error being returned.
For example `column index out of range` was returned when `database is locked` was expected.

Return correct error from Rows::next

---

crates/Cargo.toml
crates/core/Cargo.toml
crates/core/examples/example_v2.rs
crates/core/src/connection.rs
crates/core/src/errors.rs
crates/core/src/lib.rs
crates/core/src/params.rs
crates/core/src/rows.rs
crates/core/src/statement.rs
crates/core/src/v2/hrana.rs
crates/core/src/v2/hrana/pipeline.rs
crates/core/src/v2/hrana/proto.rs
crates/core/src/v2/mod.rs
crates/core/src/v2/rows.rs
crates/core/src/v2/statement.rs
crates/libsql-sys/src/statement.rs

This PR adds a new in-progress v2 rewrite of the libsql API to support both a sqlite3 and http based backend. None of this code affects the current API and is written in such a way to migrate over easily.
The current approach to abstract both the sqlite3 and http api is to use internal trait objects so that the public types do not contain generics. In the future, if we find that trait objects are too slow we can move to enums.

libsql/core: Add `v2` api

---

.github/workflows/golang-bindings.yml
.github/workflows/maketestwasm.yml

CI build is failing because Rust 1.66 is too old to build latest Clap. Let's use latest stable instead.

Use latest stable Rust toolchain in CI

---

crates/core/src/v2/hrana.rs

There's no state to reset so it's a no-op.

libsql/core: Implement hrana Statement::reset()

---

crates/Cargo.toml

`tonic-web` was pointing to a deleted branch which is now merged into main. This patch fixes the imports.

Fix broken import

---

crates/replication/src/replica/meta.rs

I am trying to use libsql API library and aiming to cross compile my app across OS. Currently it uses a *nix OS specific import and can't be used on Windows. This patch tries to fix that. 
- We are using `read_exact_at` but at offset zero, so it is same as `read_exact`
- Earlier, it was reading twice into buffer. Any particular reason for that? I changed it to read it once

Use `read_exact` instead of `read_exact_at`

---

crates/core/src/params.rs

The `Integer` value holds a 64-bit integer so that it can represent the whole range of numbers. Fix integer truncation in the conversion process where we accidentally use int() instead of int64().

libsq/core: Fix integer truncation in values

---

crates/core/src/statement.rs
crates/core/src/v2/hrana.rs
crates/core/src/v2/statement.rs
crates/libsql-sys/src/statement.rs

It's convenient to have it around for GC languages where it's hard to control when Statement objects are dropped.

crates/{core,libsql-sys}: Add Statement.finalize()

---

crates/bindings/go/libsql_test.go
crates/core/src/v1/errors.rs
crates/core/src/v1/rows.rs
crates/core/src/v1/statement.rs
crates/core/tests/integration_tests.rs

Switch the libSQL specific errors to be as close as possible to rusqlite to simplify porting apps.

Switch to rusqlite errors

---

crates/bindings/c/src/lib.rs
crates/core/Cargo.toml
crates/core/benches/benchmark.rs
crates/core/examples/example.rs
crates/core/examples/example_v2.rs
crates/core/examples/from_snapshot.rs
crates/core/examples/replica.rs
crates/core/src/errors.rs
crates/core/src/lib.rs
crates/core/src/v1/connection.rs
crates/core/src/v1/database.rs
crates/core/src/v1/mod.rs
crates/core/src/v1/params.rs
crates/core/src/v1/rows.rs
crates/core/src/v1/statement.rs
crates/core/src/v1/transaction.rs
crates/core/src/v2/mod.rs
crates/core/src/v2/statement.rs
crates/core/tests/integration_tests.rs
crates/replication/Cargo.toml

Without it, only basic utilities are compiled-in - errors and some types. Useful for exposing the API without forcing the dependent crate to be able to compile and link libsql-sys.

crates/core: introduce a "core" feature

---

crates/core/Cargo.toml
crates/core/benches/benchmark.rs
crates/core/examples/example_v2.rs
crates/core/src/v2/hrana.rs
crates/core/src/v2/mod.rs
crates/core/src/v2/statement.rs
crates/core/tests/integration_tests.rs

This changes `Statment` to use `&mut self` for fn that modify the statement state. This will enable write delegation enabled statments to "cache" the bindings locally without needing a mutex.

libsql/core: Use mutable refs for statement

---

crates/bindings/c/src/lib.rs
crates/core/examples/example_v2.rs
crates/core/examples/local_sync.rs
crates/core/examples/replica.rs
crates/core/src/lib.rs
crates/core/src/v2/mod.rs

This brings back a proper local sync API, which does not require callers to specify an URL and auth token.

libsql/core: Local sync API

---

crates/core/examples/local_sync.rs
crates/core/examples/remote_sync.rs
crates/core/src/v1/database.rs
crates/core/src/v2/mod.rs
crates/libsql-sys/src/statement.rs
crates/replication/src/lib.rs

Waiting makes sense if we have a background fiber that continuously
replicates frames back to us. In libsql crate we don't do that,
so we effectively wait for frames to be replicated, but no replication
was ever requested, and we deadlock.
Instead, as you can see in the modified examples/remote_sync example,
users call db.sync().await() in order to be able to read their own
writes.
Depends on #366

crates/replication: do not wait for replication in execute()

---

crates/core/examples/local_sync.rs
crates/core/src/v1/database.rs
crates/replication/Cargo.toml

The root cause was that in some parts of the code, it's assumed that if replication_ctx exists, then we set up HTTP replication, while sometimes we want only the local sync_frames variant to work. We *really* need to clean up the replication stuff and get rid of the separate libsql_replication crate, but meanwhile - this works.
Fixes #374

crates/core: fix local_sync example

---

crates/core/src/v1/database.rs
crates/replication/src/lib.rs

When replication is performed manually by calling sync_frames(), it was disallowed to start applying snapshots from offsets different than 0. This restriction is now lifted, and the caller is trusted to provide proper, continuous frame offsets to sync_frames(). If we decide to bring back validation, we also need to implement persisting replication metadata on-disk, so that we can validate offsets between restarts.
Fixes #374

crates/core: allow initializing replication from non-0 offsets

---

crates/core/examples/local_sync.rs
crates/core/src/v1/database.rs
crates/replication/src/lib.rs

Instead of checking if the incoming frame number is equal to previous
post-commit frame number, we should check if the incoming frame number
is the next frame. E.g. if the last post-commit frame number is 10,
we expect replication to send frame 11 next.
Fixes #374

crates/core: fix off-by-one error in validating snapshot frames

---

crates/core/examples/local_sync.rs
crates/core/src/v1/database.rs
crates/core/src/v2/mod.rs
crates/replication/src/lib.rs

Replicating frames from snapshot files will now return the number of successfully applied frames. If 0 is returned, it's still a success, and simply means that the frames were already applied before.

crates/core: return the number of frames synced

---

crates/core/src/v1/connection.rs
crates/core/src/v1/database.rs
crates/libsql-sys/src/connection.rs

This adds a `Sync` impl for `libsql_sys::Connection` and in addition adds a assert_eq! check to connection initialization to verify we have the correct threadsafe mode set.

libsql/sys: Impl `Sync` for `Connection`

---

crates/core/examples/example.rs
crates/core/src/errors.rs
crates/core/src/v1/params.rs

This small PR adds a `try_params` macro, which works similarly to `params!`, except it returns a Result and is based on `TryInto` instead of `Into`.
I also evaluated how compatible with rusqlite we can/should be, and here are my conclusions:
1. rusqlite implements `Params` as a trait, while in our code it's a clonable struct
2. rusqlite params are based on a `ToSql` trait, as well as `&dyn ToSql` for passing parameters
3. our params are just Value instances passed by value
4. rusqlite does intricate lifetime management of the parameters, while we're more into "pass and clone everything as is to avoid being generic over lifetimes
To sum up, I *haven't* just migrated to rusqlite code in this PR, because rusqlite params are more in line with their lifetime management -> e.g. `query` returns …

crates/core: add try_params and more conversions

---

crates/libsql-sys/Cargo.toml
src/vdbe.c
test/rust_suite/src/lib.rs

Ephemeral tables are created ad-hoc, often on selects, so we should not take data inserted in there as "rows written".
Tested with:
```sql
create table t(id);
insert into t values (42), (43), (44);
.stats on
select * from t where id in (select * from t);
```
, that used to return 6 rows read and 3 written, and now properly returns 6 rows read and 0 written.

vdbe: only bump rows written on non-ephemeral tables

---

src/btree.c
src/btree.h
src/vdbe.c
test/rust_suite/src/alter_column.rs
test/rust_suite/src/lib.rs

COUNT (*) is an optimized operation which scans the b-tree structure instead of individual rows to get a count of all rows in the table. Thus, it should be accounted only for b-tree pages inspected when counting "rows read".

btree,vdbe: account number of COUNT(*) pages read

---

crates/core/benches/benchmark.rs
crates/core/examples/example_v2.rs
crates/core/src/lib.rs
crates/core/src/v1/connection.rs
crates/core/src/v1/mod.rs
crates/core/src/v1/params.rs
crates/core/src/v1/rows.rs
crates/core/src/v1/statement.rs
crates/core/src/v1/transaction.rs
crates/core/src/v2/hrana.rs
crates/core/src/v2/mod.rs
crates/core/src/v2/statement.rs
crates/core/tests/integration_tests.rs

This change moves us from using `TryFrom` to convert into `Value` and `Params` to using our own internal trait. The motivation for this change is to allow us to encode the error variant directly into the trait return type rather than needing to be generic over it like how `TryFrom` has the `Error` associated type.

libsql/core: Add `IntoParams` and `IntoValue`

---

crates/core/examples/example.rs
crates/core/src/v1/params.rs

Heavily inspired by rusqlite. Allows passing arbitrary tuples as params, without wrapping it in a params! or try_params! macro.
Follows-up #390

crates/core: impl IntoParams for tuples

---

crates/core/src/v1/params.rs
crates/core/tests/integration_tests.rs

This adds doc comments explaining how a user can pass parameters through into libsql's prepared statements. This commit also seals the trait so that no external user can implement this crate allow us to modify impls down the line without breaking users.
In addition, this continues the tuple magic for named parameters as well.
Preview of the docs:

libsql/core: Add `IntoParams` docs

---

crates/replication/src/lib.rs

Previous code bumped next_offset too early, and in case we failed to send and apply frames, it remained bumped. That means we'd never try to apply the frames again and end up with some of them ignored, and that's data corruption. Not a likely scenario, since it happens after the frames were fetched from the network, and it's only their local application, but still, technically risky.
Refs #350

replication: fix bumping next_offset in http sync

---

crates/replication/src/replica/injector.rs

Looks like our replication crate took inspiration from old sqld code, which still had writable_schema=off. We actually need to apply a special RESET operation, which also parses and applies the modified schema to all in-mem structures.
Refs #392

crates/replication: fix pragma writable_schema=reset

---

crates/core/Cargo.toml
crates/core/src/box_clone_service.rs
crates/core/src/lib.rs
crates/core/src/v2/hrana.rs
crates/core/src/v2/mod.rs

add an `open_remote_with_connector` method to use libsql remote with a custom http acceptor.

add open_remote_with_connector

---

crates/core/Cargo.toml
crates/core/examples/transaction.rs
crates/core/src/errors.rs
crates/core/src/replication/client.rs
crates/core/src/replication/connection.rs
crates/core/src/replication/mod.rs
crates/core/src/replication/parser.rs
crates/core/src/v1/connection.rs
crates/core/src/v1/statement.rs
crates/core/src/v2/mod.rs
crates/core/src/v2/rows.rs
crates/core/src/v2/statement.rs
crates/core/src/v2/transaction.rs

This implements write delegation in the proper way by not leveraging the
internal libsql parser but to use a separate rust one. This allows us
to not corrupt libsql connection state when we want to submit remote
executes.
What this means is there is now a `RemoteConnection` implementation that
wraps the libsql version. It will detect when sql statements are write
based and will submit those against the primary.
Closes https://github.com/libsql/libsql/issues/403

libsql/replication: Write delegation v2 with txn support

---

crates/core/src/replication/parser.rs

Even if all SQL statements are read-only, if you start a transaction, it's safest to execute it remotely for correctness.

libsql/core: Fix Statement::is_read_only() for TX markers

---

crates/core/src/replication/connection.rs
crates/core/src/v1/connection.rs
crates/core/src/v2/hrana.rs
crates/core/src/v2/mod.rs

We had two interfaces for calling sqlite3_close C function:
- drop()
- disconnect()
In drop() we checked for `drop_ref` to make sure we only call it once for a raw pointer, but the check was missing for `disconnect()`. Now the behavior is unified.
As a result, we need to take a mutable reference on `fn close()`, but that sounds reasonable - we need to own the connection to be able to close it, since it renders it unusable for other users.
Refs (and maybe fixes) #419

core: make sure sqlite3_close is not called twice

---

crates/core/Cargo.toml

Bumps the version of tonic to fix this bug https://github.com/hyperium/tonic/pull/1540

libsql/replication: Fix sync with large databases

---

crates/Cargo.toml
crates/core/examples/transaction.rs
crates/core/src/replication/connection.rs
crates/core/src/replication/parser.rs
crates/core/src/v1/transaction.rs
crates/core/src/v2/mod.rs
crates/core/src/v2/statement.rs
src/parse.y
tool/mkkeywordhash.c

This adds prelimary `BEGIN READONLY` support for embedded replica's. Within libsql this syntax just converts into an `IMMEDIATE` transaction but when used with embedded replica's this will force the transaction to be local only and will reject any sql commands that write.

libsql: Add `BEGIN READONLY` support

---

src/sqlite3ext.h

`libsql_close_hook` was added here (#219) but it is not available to loadable extensions.
Following the same pattern was was done for `wal_methods_unregister` (https://github.com/tursodatabase/libsql/commit/47e59b7253d7f0250612942b8a4776059d13f3f5) to expose this to loadable extensions.
- Will be used in #434 to do cleanup of cr-sqlite

expose the libsql_close_hook to loadable extensions

---

libsql-server/sqld/Cargo.toml

It also transiently fixes the "malformed db" issue with embedded replicas. Those replicas didn't create a "libsql_wasm_func_table" when first connecting, and sqld did, due to having wasm functions enabled.
But, since our sqld parser still doesn't accept CREATE FUNCTION yet, there's no harm in disabling the support.

sqld: turn off wasm functions by default

---

bottomless/Cargo.toml
bottomless/src/backup.rs
bottomless/src/read.rs
bottomless/src/replicator.rs

Transplanted from https://github.com/libsql/sqld/pull/780

bottomless: add zstd compression option

---

README.md

Apparently they got moved down into a top-level `libsql-sqlite3` directory at some point.

Fix links to doc pages

---

libsql-server/src/connection/libsql.rs
libsql-server/src/http/admin/stats.rs
libsql-server/src/stats.rs

Top 10 most expensive queries are now stored and available
in the admin api. The ranking is kept in-memory only.
```
$ curl -s http://localhost:8081/v1/namespaces/default/stats | jq '.top_queries' | jtbl
╒══════════════════════════════════════════════════════════╤════════════════╤═════════════╕
│ query                                                    │   rows_written │   rows_read │
╞══════════════════════════════════════════════════════════╪════════════════╪═════════════╡
│ INSERT OR IGNORE INTO coordinates VALUES (?, ?, ?);      │              0 │           1 │
├──────────────────────────────────────────────────────────┼────────────────┼─────────────┤
│ INSERT OR IGNORE INTO counter VALUES (?, ?, 0);          │              0 │           1 │ …
```

libsql-server,admin: add top-k queries to stats

---

libsql-server/src/connection/libsql.rs
libsql-server/src/http/admin/stats.rs
libsql-server/src/rpc/proxy.rs
libsql-server/src/stats.rs

This PoC adds another stats entry - slowest queries, since they do not necessarily match the *most expensive* queries we count right now.
Ideas to entertain:
- tracking aggregated query time
- tracking the number of times the query was received (to ignore oneshot hyperlong queries as less interesting than lots of fairly-long queries)
Example:
```
$ curl -s http://localhost:8081/v1/namespaces/default/stats | jq '.slowest_queries' | jtbl
elapsed_ms  query
------------  ------------------------------
44  SELECT count (*) FROM t;
63  SELECT count (*) FROM t;
3483  INSERT INTO t SELECT * FROM t;
```

libsql-server: track slowest queries too

---

Dockerfile

This is a best effort attempt to run sqld with the same libraries that
it was built with. If anyone bases their images on this one and runs
apt update, and then install dependencies (e.g. because they need it
for extensions), then they risk running sqld with different dependencies
then it was built with.
Publishing the image with apt index updated allows images that depend
on this one to install further dependencies with the same version sqld
was built with. Of course apt update from the chef layer may get out
of sync with the runtime one, but this is a problem that we can solve,
since we control the life cycle of the image.

Run apt update on sqld runtime image 

---

libsql/src/replication/connection.rs
libsql/src/replication/parser.rs

Now that we support savepoints in the server, let's also allow them in the client library.
Refs https://github.com/libsql/libsql-experimental-python/issues/6

replication: support SAVEPOINT

---

libsql-server/src/http/admin/mod.rs
libsql-server/src/http/admin/stats.rs
libsql-server/src/stats.rs

Without being able to reset the queries manually, they can be forever clogged by some outliers that happened a long time ago. Long term, Prometheus should gather all kinds of these stats, but until it does, let's have a way of resetting them.

admin: allow resetting top and slowest queries

---

libsql-server/src/connection/libsql.rs
libsql-server/src/metrics.rs

Additional metrics include statement execution time histogram, vacuum + checkpoint information, memory used by prepared statements (as per SQLite statement status counters) and bytes returned to the user.

metrics: add more

---

bottomless/src/replicator.rs

I have made the option configurable since it would make a few things easier for me in testing

Make s3 retry op configurable and set default to 10

---

libsql-server/src/connection/libsql.rs
libsql-server/src/connection/mod.rs
libsql-server/src/metrics.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/stats.rs

Otherwise they aren't distinguishable from other Prometheus sources.

prefix metrics with libsql_server_

---

libsql-server/docs/http_api.md

This pull resolves disparity between http api v0 libsql-server docs and libsql-server/src/http/user/mod.rs:339
The following is the relevant snippet from libsql-server/src/http/user/mod.rs
```rs
let app = Router::new()
.route("/", post(handle_query))
.route("/", get(handle_upgrade))
.route("/version", get(handle_version))
.route("/console", get(show_console))
.route("/health", get(handle_health))
.route("/dump", get(dump::handle_dump))
```
However  libsql-server/docs/http_api.md mentions `POST /queries` and `POST /query`.

make http api v0 docs consistent with code in libsql-server/src/http/user/mod.rs:339 (impl UserApi<M, A, O, S>, configure)

---

libsql-sys/build.rs

Without this flag, we cannot run `cargo test` from a fresh build.

add missing flags to libsql-sys configure

---

libsql-server/src/connection/libsql.rs
libsql-server/src/connection/mod.rs

This PR fixes a bug in lock stealing that was two-fold:
- When downgrading a transaction we took the state slot without making sure that the state lock was ours, so we could end up taking some other txn slot instead, leaving an empty slot.
- When stealing a txn, we didn't make sure that the slot we stole was the same slot as the one we intended to steal.
This fix was tested by running the following code for 1M iterations:
<details>
<summary>Click me</summary>
```rust
#![allow(dead_code)]
use rand::Rng;
use serde::{ Deserialize,Serialize };
use tokio::task::JoinSet;
type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;
impl From<&[&str]> for Req {
fn from(s: &[&str]) -> Self {
let requests = s.into_iter().map(|&s| Op::Execute { stmt: Sql { sql: s.into() } }).collect();
Req { …
```

fix bug in lock-stealing

---

libsql-server/docs/http_api.md

The http api v0 docs is horribly out of parity with libsql-server/src.
This pull aims to mitigate this.
Evidence for docs' `Error` change:
Evidence for docs' `BatchResponse ` change:

make http api v0 docs consistent with libsql-server/src

---

libsql-sys/build.rs

I encountered this error when trying to use the `LIBSQL_REGENERATE_BINDINGS` environment variable:
```
$ cargo clean ; LIBSQL_REGENERATE_BINDINGS=1 cargo build -p libsql-sys -vv --jobs 1
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-DSQLITE_CORE" "-DSQLITE_DEFAULT_FOREIGN_KEYS=1" "-DSQLITE_ENABLE_API_ARMOR" "-DSQLITE_ENABLE_COLUMN_METADATA" "-DSQLITE_ENABLE_DBSTAT_VTAB" "-DSQLITE_ENABLE_FTS3" "-DSQLITE_ENABLE_FTS3_PARENTHESIS" "-DSQLITE_ENABLE_FTS5" "-DSQLITE_ENABLE_JSON1" "-DSQLITE_ENABLE_LOAD_EXTENSION=1" "-DSQLITE_ENABLE_MEMORY_MANAGEMENT" "-DSQLITE_ENABLE_RTREE" "-DSQLITE_ENABLE_STAT2" "-DSQLITE_ENABLE_STAT4" "-DSQLITE_SOUNDEX" "-DSQLITE_THREADSAFE=1" "-DSQLITE_USE_URI" "-DHAVE_USLEEP=1" …
```

libsql-sys: fix path to sqlite3.c in build.rs

---

libsql-replication/proto/replication_log.proto
libsql-replication/src/generated/wal_log.rs
libsql-replication/src/replicator.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/replication/replicator_client.rs
libsql-server/src/rpc/replication_log.rs

With this PR, the replicas will delegate their request until they have caught up with their primary's replication index at the moment the replica's namespace has been loaded.

Replica delegate request until in sync

---

libsql-server/tests/standalone/mod.rs
vendored/sqlite3-parser/src/parser/ast/mod.rs
vendored/sqlite3-parser/src/parser/parse.y

It's done in a hacky way, similarly to how "STRICT" is already handled. Sad, but I tried making it work properly with a registered RANDOM keyword and it failed. There's precedence in using this runtime string comparisons (like in STRICT case), so I guess it's here for a reason.
Tested locally, properly activates random rowid.
Fixes #333

vendored/sqlite3-parser: support RANDOM ROWID

---

libsql-server/scripts/prometheus_docker.yml
libsql-server/scripts/run_prometheus_docker.sh

It makes metrics development easier, with the prometheus image already seeded with configuration that scrapes events from localhost:8081.
Runs properly with `cargo run -- --admin-listen-addr 0.0.0.0:8081`.
My grand plan is to also create a dev grafana dashboard based on Prometheus data, but one step at a time :innocent:

scripts: add a dockerized prometheus helper

---

.github/workflows/rust.yml
Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/h2c.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/metrics.rs
libsql-server/src/rpc/mod.rs
libsql-server/tests/common/mod.rs
libsql-server/tests/standalone/mod.rs
libsql/Cargo.toml
libsql/src/database.rs
libsql/src/hrana/connection.rs
libsql/src/hrana/hyper.rs
libsql/src/local/database.rs
libsql/src/replication/client.rs

This commit adds a new `x-libsql-client-version` header emitted by clients. The server will collect these values and emit them as a `libsql_client_version{version="libsql-hrana-0.1.11"}`. This also exposes special doc hidden functions that our other clients that use the rust one to emit their own metric.
Closes #546

Add client version reporting metrics

---

libsql-server/src/config.rs
libsql-server/src/connection/config.rs
libsql-server/src/error.rs
libsql-server/src/heartbeat.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs

This is needed for putting namespaces for different users on the same cluster and still correctly reporting the usage.

Allow custom heartbeat url for namespace

---

Cargo.lock
libsql-server/src/replication/primary/logger.rs
libsql-sys-tmp/src/lib.rs

This pr adds tests that ensure replica consistency when savepoints an rollback are used. The result is not ideal since stale frames are written to the shadow wal, but at least the replica remains consistent. I'm not investing more efforts on that right now since this will be fixed by unification soon.

add test for savepoint with replication

---

.github/workflows/c-bindings.yml
bindings/c/Makefile
bindings/c/example.c

This PR updates the example of the C bindings to make it match the generated header (and thus Rust).
```
$ pwd
/Users/.../code/libsql-fork/bindings/c
$ clang -o example -I include/ example.c ../../target/debug/libsql_experimental.a -framework Security -framework CoreServices && ./example
1
```
Resolves #592

sql-experimental: update example.c to match rust

---

libsql-replication/src/replicator.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/mod.rs
libsql-server/tests/cluster/mod.rs
libsql-server/tests/cluster/replica_restart.rs

This PR fixes the replica not self-healing when the primary regenerates their log. The meta error was not handled correcly on handshake.

Fix replica reset on primary log regeneration

---

bottomless-cli/src/main.rs
bottomless-cli/src/replicator_extras.rs
bottomless/src/backup.rs
bottomless/src/replicator.rs
bottomless/src/wal.rs
libsql-server/src/test/bottomless.rs

This PR implements two things that lead to fixing #598.
1. (not direct cause) It makes the checksumming work as long as it's produced and checked on an arch with matching endianness. Most of modern machines, including the ones we run on our platform, CI, and home devices are just little endian anyway. The proper fix is to also store the checksum computation endianness in our .meta file, just like SQLite stores it in the WAL header, but that's not implemented yet.
The main change is not storing the checksum as a single u64 and using a pair of u32 instead, since that's how the SQLite algorithm is described -- and a single u64 is also more complicated on little endian, because reading a single u64 in little endian is not the same as reading two consecutive little endian u32's and merging …

bottomless: fix checksumming across checkpoints

---

libsql-server/src/replication/primary/logger.rs

When the instance was dirty, and we tried to create a namespace, it would attempt to revoced from an unexisting database file, and fail with a file not found error.

do not attempt to recover empty database

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs

Add some missing API functions outlined in #475.

Improve C bindings

---

libsql-server/src/connection/libsql.rs

This PR fixes a bug with lock-stealing when only a single connection would be notified when the lock was returned. The could cause some connections to never be notified, and only try to re-acquire the lock when the timeout had passed. Instead, we now notify all waiters, and let them wait again for a new slot.

Notify all waiting connections on transaction end

---

libsql-replication/src/injector/mod.rs
libsql-replication/src/meta.rs
libsql-server/tests/cluster/mod.rs
libsql-server/tests/cluster/replication.rs

This PR fixes a bug with very large snapshots that would cause the replica to enter an infinite loop of replication.
The issue was that with a sufficiently large snapshot to be injected in multiple chunks, we would not record the correct commit frame_no. To remidy that, the injector keeps track of the largest frame_no it's seen within a transaction and sets that to the commit frameno on commit.

snapshot injection bug

---

libsql-server/src/replication/primary/logger.rs
libsql-server/src/replication/snapshot.rs

This PR fixes a bug in snapshot compaction because I changed the channel type used for compaction from a 0 sized crossbeam to a 1 sized tokio channel. This created a data race in the wallog swap, and caused the compactor to crash.
I also made the log merger non-blocking, which should improve tail latencies quite significantly for large databases.
Finally, I have added extended  testing to this feature to prevent future regression.
close #647

fix snapshot compaction

---

.github/workflows/nemesis.yml

This PR adds a Github Workflow to run [Nemesis tests](https://github.com/tursodatabase/tursotest/tree/main/internal/nemesis) in local mode. In local mode, it spawns multiple libsql-server and minio processes and runs the test suite. 
I have added Nemesis test workflow separately than `Run Tests`. There is a possibility of false positive alert (the code is new) and separate work flow makes it easier to distinguish.

Add nemesis test runner

---

libsql-server/src/database.rs
libsql-server/src/error.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/replication/primary/logger.rs

closes https://github.com/libsql/sqld/issues/757
- I renamed `Database.shutdown` to `Database.destroy`, which sends only the close signal. The new `Database.shutdown` now sends the close signal + waits for snapshot to complete

snapshot on scale to zero and shutdown

---

docs/ADMIN_API.md

add basic documentation for the namespace API. Not all endpoints are documented, only the basic namespace operations.

partially document admin API

---

libsql-sqlite3/.gitignore
libsql-sqlite3/Makefile.in
libsql-sqlite3/src/os_unix.c
libsql-sqlite3/src/os_win.c
libsql-sqlite3/src/sqlite.h.in
libsql-sqlite3/src/sqliteInt.h

It is not directly tested or usable yet, and depends on having wasi-libc library available at /usr/share/wasi-sysroot.
Still, it compiled, so it's a nice start.
`make wasi` produces `libsql.wasm` module.
Future work includes using this module to run a WebAssembly app in a runtime that supports WASI, using `libsql.wasm` as the database implementation.
The patch is based on splitting SQLITE_OMIT_WAL into SQLITE_OMIT_SHARED_MEM, so that we can still compile WAL mode, just without shared memory, so still usable with exclusive mode or via libSQL's virtual WAL.

wasm: add `make wasi` command

---

libsql-replication/src/replicator.rs
libsql-server/src/replication/replicator_client.rs
libsql-server/tests/embedded_replica/mod.rs
libsql/src/local/database.rs
libsql/src/replication/local_client.rs
libsql/src/replication/remote_client.rs

Embedded replicas fetch frames in batches and need to resume replication at offset that are not necessarily on commit boundaries. When the replicator encounters an error and calls next_frames again, it expects the client to send frames from the previously known commit index. The embedded replica would instead try to fetch from the last received. This is fixed by adding a rollback method to the client to force fetch from previous commit index. Furthermore, the embedded replica now replicates to match the primary replication index on a call to `sync_oneshot`, and a handshake is forced on `sync_oneshot` to know the current primary index. That makes calling sync_oneshot more deterministic and prevent out-of-transaction boundaries syncs.

fix embedded replication

---

libsql-server/src/rpc/replication_log.rs
libsql-server/tests/embedded_replica/mod.rs
libsql/src/replication/remote_client.rs

The embedded replica started replicating from index 0 on restart, instead of the last committed index. Fixed and added a test.

fix replica resync from scratch

---

libsql/src/local/database.rs

- test embedded replica don't resync from scratch on restart
- fix replica re-syncing from 0 on restart
- remove unwraps when opening connections

fix connection error handling

---

libsql/src/deserialize_row.rs
libsql/src/hrana/mod.rs
libsql/src/lib.rs
libsql/src/local/impls.rs
libsql/src/replication/connection.rs
libsql/src/rows.rs
libsql/tests/integration_tests.rs

This PR ports [de.rs](https://github.com/libsql/libsql-client-rs/blob/main/src/de.rs) from libsql-client-rs so that `Row`s can be deserialized, attempting to resolve #614.
I'm adding a `column_count` method to the `RowInner` trait because I find it convenient for telling when to stop the iteration on the `Row` inside the `MapAccess` implementation. Alternatively, we can maintain a column index and stop the iteration as soon as `row.column_value` or `row.column_name` returns `Err` or `None`. (That would require some changes on the existing `RowInner` implementations.)

libsql: port row deserializer from rust client

---

Cargo.toml
libsql-sqlite3/Makefile.in
libsql-sqlite3/ext/libsql-wasi-demo/.gitignore
libsql-sqlite3/ext/libsql-wasi-demo/Cargo.toml
libsql-sqlite3/ext/libsql-wasi-demo/src/main.rs
libsql-sqlite3/ext/libsql-wasi-demo/src/memory.rs
libsql-sqlite3/ext/libsql-wasi-demo/src/vfs.rs
libsql-sqlite3/ext/wasi/vfs.c

This PR contains a demo which uses Wasmtime runtime to run libSQL in a WebAssembly instance, compiled in WAL mode. Right now it's full of stubs, and a VFS that calls back to the host for each operation. Once these stubs are implemented **and** we also provide a virtual WAL implementation that calls back to the host, we'll have a solid foundation for running libSQL with replication as a Wasm instance.
Step 1: compile `libsql.wasm` (should be automated with build.rs, I'm just lazy)
```sh
cd libsql-sqlite3
make wasi
```
Step 2: run the demo
```sh
cd ext/libsql-wasi-demo
RUST_LOG=info,libsql_wasi_demo=trace cargo run
```
Step 3: profit
```sh
$ file /tmp/wasm-demo.db*
/tmp/wasm-demo.db:     SQLite 3.x database, last written using SQLite version 3044000, writer version 2, read version 2, file …
```

Support compiling libSQL to Wasm with virtual WAL

---

libsql-server/src/main.rs

2nd try. Sorry I discarded my local fork changes too quick before previous pull #690 really got merged.

libsql had been moved under https://github.com/tursodatabase/libsql

---

libsql/src/hrana/hyper.rs

```rust
let conn = Database::open_remote("", "").unwrap().connect().unwrap();
// !!! Painc
conn.query("SELECT 1", ()).await;
```
```
thread 'main' panicked at libsql/src/hrana/hyper.rs:40:14:
called `Result::unwrap()` on an `Err` value: http::Error(InvalidUri(InvalidFormat))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Fix remote connection panic

---

.github/workflows/nemesis.yml

self hosted runner requires the path to be `/home/ubuntu` Github runner requires the path to be `/home/runner`
instead of using either of hardcoded paths, changing to `~/` works for both

nemesis: use correct path for binaries

---

Cargo.toml

Instead of appending to releases from release drafter, let cargo-dist take care of creating releases.

cargo-dist: handle releases

---

bottomless/src/replicator.rs
libsql-server/src/database.rs

This PR adds a `graceful_shutdown` method to bottomless replicator, which will wait for all known committed frames to be uploaded to S3 and for all pending snapshots to be uploaded as well prior completion.
There's a matter when to call this method as `ReplicationLogger` doesn't seem to expose graceful shuttdown method on its own. @MarinPostma could maybe help here.

bottomless: wait for all background tasks to complete on graceful shutdown

---

.github/workflows/release-libsql.yml

Only release a new version of libsql-sqlite3 on demand, by tagging `libsql-sqlite3-vx.x.x`

release libsql-sqlite3 on demand

---

.cargo/nextest.toml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
bottomless/src/replicator.rs
libsql-server/Cargo.toml
libsql-server/README.md
libsql-server/src/test/bottomless.rs

This adds in process mock s3 backend via the `s3s` crate. This allows us to run tests without requiring a user run `minio` or hook up their real aws account.

sqld: add in process s3 for bottomless tests

---

libsql-replication/src/replicator.rs
libsql-server/src/replication/snapshot.rs
libsql-server/tests/cluster/replication.rs
libsql/src/de.rs
libsql/src/transaction.rs

... so that it spams less hints when run locally.

treewide: apply clippy

---

libsql/src/de.rs
libsql/src/value.rs
libsql/tests/integration_tests.rs

I noticed that the row deserialization was not implemented correctly, because `Value::Null` was deserialized with the unit deserializer, which is incorrect. Instead, I implemented a `ValueDeserializer` that handles deserializing values correctly.

fix libsql Value deserialization

---

bottomless/src/bottomless_wal.rs
libsql-replication/src/injector/injector_wal.rs
libsql-server/src/namespace/replication_wal.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-sys/src/wal/ffi.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs

Use `NonZeroU32` to represent page_no and frame_no coming from sqlite, since a valid frame/page_no can't be 0. Also, find_frame returns 0, when a frame can't be found, instead, we return `Option<NonZeroU32>`

Use NonZeroU32 for frame_no and page_no

---

libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/wrapper.rs

This PR adds the `WalWrapper` utility to conveniently create implementation of `Wal` that wrap other implementation of `Wrap`, and only implement necessary methods.

add WalWrapper utility

---

Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-sys/Cargo.toml
libsql-sys/src/lib.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs

Until this PR, the replication index was stored in two places:
- In the shadow wal header on a primary
- In the `client_wal_meta` on a replication
Thsi was problematic because, on the replica it forces us to inject a transaction at a time and sync the meta file on each injection, and on the primary, it forces us to recover the database from scratch when we loose the shadow wal.
To fix that, we we now store the replication index in the sqlite file header, in the top 8 bytes of the reserved bytes available in the header. On checkpoint, the most recent version of page 1 is patched with the new replication index, before being re-injected in the wal, and then checkpointed.

Store replication index in Page 1

---

libsql/src/value.rs
libsql/tests/integration_tests.rs

```rs
let mut rows = conn.query("SELECT null as a, 1 as b, 2 as c, null as d, null as e", ()).await.unwrap();
// ...
#[derive(Deserialize)]
struct Row {
// From Null: `None`
a: Option<i64>,
// From Integer: `Some(1)`
b: Option<i64>,
// From Integer: `2`
c: i64,
// From Null: `()`
d: (),
// From Null: `None`
e: Option<()>,
}
```
fix: #749

Support deserialize to Option<T> and Unit

---

Cargo.lock
libsql-replication/Cargo.toml
libsql-replication/src/frame.rs
libsql-replication/src/injector/injector_wal.rs
libsql-replication/src/injector/mod.rs
libsql-replication/src/meta.rs
libsql-replication/src/replicator.rs
libsql-replication/src/snapshot.rs
libsql-server/Cargo.toml
libsql-server/src/namespace/fork.rs
libsql-server/src/replication/primary/frame_stream.rs
libsql-server/src/replication/primary/logger.rs
libsql-server/src/replication/snapshot.rs
libsql/Cargo.toml
libsql/src/replication/remote_client.rs
libsql/tests/replication.rs

zerocopy handles endianess, which was required for sqlite, and is overall more robust.

Migrate from bytemuck to zerocopy

---

bottomless/src/replicator.rs
libsql-server/src/lib.rs

Ensure DB ID is set if namespaces are enabled

---

.gitignore

According to https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control, library code is better off ignoring Cargo.lock. Our gigarepo contains binaries too, but for the sake of dev speed, let's just ignore it. The only effect of keeping Cargo.lock around I'm aware of is to annoy people who often check out different git commits and branches.

.gitignore: add Cargo.lock

---

bottomless/src/bottomless_wal.rs
libsql-replication/src/injector/injector_wal.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/namespace/replication_wal.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-sys/src/wal/ffi.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs

This fixes a mistake of mine. The `InhibitCheckpointWal` wal was not actually preventing checkpoint on close. This is solved by not providing a scratch buffer to the close method on close, and sqlite will simple skip checkpointing on close: https://github.com/tursodatabase/libsql/blob/main/libsql-sqlite3/src/wal.c#L2144

prevent checkpoint on WAL close for InhibitCheckpointWal

---

libsql/src/database.rs
libsql/src/local/database.rs

Add `Database::replication_index` that returns the currently committed replication index for the database.

Libsql: method to return currently commited index

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs

The libsql_open_ext() API does not support auth token. Let's add a libsql_open_remote() API for establishing connection to remote database, but also add a libsql_open_file() for what libsql_open_ext() does so that we can deprecate it in the future.

bindings/c: Implement libsql_open_{file,remote} API

---

libsql/src/connection.rs
libsql/src/hrana/connection.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/stream.rs
libsql/src/local/impls.rs
libsql/src/replication/connection.rs

Potential rollback, depending on the result of discussion from #758 .
The original decision to change was this discussion: https://github.com/tursodatabase/libsql/pull/653#discussion_r1400789143

make libsql Conn::is_autocommit synchronous

---

libsql-server/src/error.rs
libsql-server/src/http/user/db_factory.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/namespace/mod.rs

This PR adds a way to extract namespace from the path. This is done so that users can have smooth experience in `turso dev` and they can connect to multiple namespaces without editing `/etc/hosts` file. This patch does not require any changes in shell or libraries.
1. The expected path format is `/dev/<namespace>` I am not sure if we want to enable to this feature on the platform. So for now, I kept it behind the `/dev` sub path
2. Similarly, I have enabled only `/dev/:namespace/v2/pipeline` and `/dev/:namespace/v3/pipeline` paths.
I have tested this with turso shell and go sdk.

Add path based routing

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/local/connection.rs
libsql/src/local/database.rs
libsql/src/replication/connection.rs
libsql/src/replication/mod.rs

libsql: add read your writes support

---

libsql-ffi/bundled/src/sqlite3ext.h
libsql-sqlite3/src/loadext.c

... previously we somehow missed libsql_close_hook

libsql-sqlite3: initialize libsqlApi properly

---

bottomless/src/replicator.rs
libsql-server/Cargo.toml
libsql-server/src/error.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/src/namespace/fork.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/test/bottomless.rs

This is a port of Marin's https://github.com/libsql/sqld/pull/689
This PR replaces the namespace store dumb hashmap with an LRU cache to bound the maximum number of namespaces loaded into memory while unbounding the number of namespaces allocated on a sqld instance. Additionally, this enables fully concurrent access to namespaces by removing the global lock on the namespace store.

libsql-server: use LRU cache to store active namespaces

---

libsql/Cargo.toml
libsql/src/hrana/connection.rs
libsql/src/hrana/cursor.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/mod.rs
libsql/src/hrana/proto.rs
libsql/src/hrana/stream.rs
libsql/src/hrana/transaction.rs
libsql/src/value.rs
libsql/src/wasm/cloudflare.rs
libsql/src/wasm/mod.rs

WIP
This PR adds a support for cursors in Hrana HTTP client. Cursors enable to fetch rows and batch results on demand, without requiring to prefetch (potentially large) result sets in memory. This is done by:
1. Splitting `HttpSend` trait response into buffered and streamed one.
2. Introducing cursor data structure capable of patching streamed response into series of protocol messages:
- These messages are then organised into streams of cursor steps (each step matches an input batch request result set).
- Further cursor steps organise streams of subsequent entries into start/end step metadata and stream of rows.
PS: atm. cursor API is replacing existing execute/execute_batch statement in HranaStream without any profound changes in the upper libsql client API. It does so by calling a …

Libsql cursor

---

libsql-server/src/metrics.rs
libsql-server/src/replication/replicator_client.rs

Makes debugging replication latency issues easier.

Add a metric for out-of-sync replication values

---

libsql-server/src/replication/primary/logger.rs

Make the replication latency cache size configurable with the `REPLICATION_LATENCY_CACHE_SIZE` env variable.

configurable replication latency cache size"

---

libsql-server/src/auth.rs
libsql-server/src/http/user/dump.rs

Authenticated::is_namespace_authorized already returns false when Authenticated::is_anonymous() == true.

Remove Authenticated::is_anonymous

---

Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/connection/libsql.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/rpc/streaming_exec.rs
libsql-server/tests/cluster/mod.rs
libsql-server/tests/embedded_replica/mod.rs
libsql-server/tests/hrana/transaction.rs

The QueryBuilder was being misused (by me) in the `WriteProxy` code. This fixes it by driving the query builder in on the thread pool.

Fix blocking ResultBuilder in WriteProxy

---

.github/workflows/publish-server.yml

Closes https://github.com/tursodatabase/libsql/issues/795
This PR adds an additional `platform` to `docker buildx` to support arm64 (`linux/arm64`, the default for GitHub runners is `linux/amd64`).
[This commit](https://github.com/tursodatabase/libsql/pull/845/commits/c498c98e693d498f460a62fad6ed79b9cca737ec) will allow to test if it still builds successfully for both platforms before merging.

ci: release Docker images for arm64

---

libsql-sqlite3/src/wal.c

This is the first PR in the _unification_ series.
In this PR, the behaviour of the wal iterator is changed to insert frames in reverse frame-no number rather than in acending page_no number. In a future PR, we will need that to intercept frames on checkpoint to create snapshots, that are in reverse frame order.
Additionally, we add the option to retrieve frames that are less than `maxSafeFrame` even if the same page also exists with a `frame_no > mxFrameNo`, which the original implementation doesn't support. This is again necessary for us to build snapshots on checkpoint, since we require the snapshot to contain all the changes between two points in time.

sqlite3 wal reverse iterator

---

libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs
libsql-server/tests/common/http.rs
libsql-server/tests/namespaces/mod.rs

This PR uncovers and fixes issue with namespace deletion:
1. Original test `namespaces::delete_namespace` didn't work correctly, since:
1. POST `namespaces/foo/destroy` is not a valid request/route.
2. Test assertion was failing on error not because we sent a request to deleted namespace, but we tried to create table which already existed.
2. As it turns out, `PrimaryNamespace::destroy` removed all necessary entries, **except the namespace configuration in meta store**. The thing is that when a request was sent from a client to a deleted namespace, meta store still had a necessary config. In result we opened a new DB connection using that config: and since all sqld connections are opening DB file using open-or-create semantics, we recreated a deleted database.

fixing namespaces::delete_namespace uncovers a bug

---

.github/workflows/brew-test.yml

sample run: https://github.com/tursodatabase/libsql/actions/runs/7490407240
trigger is set to workflow dispatch, so this needs to be run manually
btw if you think its not necessary or adds noise to workflow directory, then I can move this to https://github.com/libsql/homebrew-sqld repo

Add a github workflow to test brew installs

---

libsql-sqlite3/ext/wasm/api/EXPORTED_FUNCTIONS.sqlite3-api
libsql-sqlite3/ext/wasm/api/sqlite3-api-oo1.js

We need the `sqlite3_get_autocomit()` and `sqlite_last_insert_rowid()` in the TypeScript SDK, for example. The fact that it's not exported seems to be just an omission so let's add it.

libsql-sqlite3: Export more API functions in Wasm

---

vendored/sqlite3-parser/Cargo.toml
vendored/sqlite3-parser/src/parser/ast/mod.rs
vendored/sqlite3-parser/src/parser/parse.y

We support it in libSQL already, so we just add appropriate entry in sqlite3_parser's parse.y as well
Fixes #447

sqlite3_parser: add support for `ALTER TABLE ALTER COLUMN` syntax

---

libsql-server/src/main.rs

The encryption key can now be set with SQLD_ENCRYPTION_KEY.

main: add env var option for encryption key

---

Cargo.lock
libsql-server/src/connection/mod.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/test/bottomless.rs

This PR makes the connections conccurency configurable with the `--max-concurrent-connections` argument. It also handles conccurency better by making it global, instead of per namespace

Make connection concurrency configurable

---

libsql-replication/proto/metadata.proto
libsql-replication/src/generated/metadata.rs
libsql-server/src/connection/config.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/http/admin/mod.rs

This PR makes txn timeout configurable per-namespace thanks to the `txn_timeout_s` option in the namespace configuration

configurable txn timeout

---

libsql/src/hrana/connection.rs
libsql/src/hrana/stream.rs
libsql/src/local/database.rs
libsql/src/util/mod.rs

Atm. Hrana connection takes in a base_url and internally constructs a pipeline (/v3/pipeline) and cursor (/v3/cursor) URLs out of it. The thing is that it did so without properly checking if it's ok to do so. Therefore if someone set a base URL to ie. `libsql://pen.turso.io/?authToken=` it wouldn't immediately fail, but instead the requests would be send to an invalid endpoint (`/?authToken=/v3/cursor` instead of `/v3/cursor/?authToken=`). This PR changes that behaviour.
Now, we could think: why not use native URL parsing capabilities and use Url all the way down:
1. Hyper and Cloudflare use different parsing libraries. Hyper uses `http` based one which comes with dependencies that we don't want on Cloudflare end.
2. Cloudflare (and `url` crate, which it uses internally) comes with some …

Hrana URL strings: don't append pipeline/cursor routes blindly

---

Dockerfile
libsql-ffi/build.rs
libsql-ffi/bundled/SQLite3MultipleCiphers/CMakeLists.txt

Fix the docker build:
- check the output of multi-cipher build command
- add cmake as a build dependency
- downgrade cmake require version to meet what's available on debian

fix docker build

---

libsql-server/src/http/admin/stats.rs
libsql-server/src/stats.rs

This should allow any stats consumer to know when the file has been lost and the counters should be restarted.
Replaces https://github.com/tursodatabase/libsql/pull/883.

Add UUID to stats

---

bottomless/src/bottomless_wal.rs
libsql-ffi/bundled/bindings/bindgen.rs
libsql-ffi/bundled/bindings/session_bindgen.rs
libsql-ffi/bundled/src/sqlite3.h
libsql-replication/src/injector/injector_wal.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-sqlite3/src/pager.c
libsql-sqlite3/src/wal.c
libsql-sqlite3/src/wal.h
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-sys/src/wal/ffi.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs

This pr makes xFrame return the number of committed frames after a call to xFrame. This is necessary to keep track of the current replication index, and notify the waiting replicators when new data becomes available.

return number of committed frames on insert_frames

---

libsql-server/src/replication/mod.rs
libsql-server/src/replication/snapshot_store.rs

Introduce the snapshot store, that manages snapshots for all namespaces. It is backed by a sqlite table, which allows efficient searching. The resource is also separated from the namespaces, so that it's lifetime is not tied to that of the namespaces, and that it is shared.

introduce snapshot store

---

libsql-sqlite3/src/wal.c

A 100% benign error, because the function has the correct signature, but gets rid of a compiler warning.

wal.c: fix the function pointer type

---

libsql-server/src/replication/snapshot.rs

Wait for a longer in compaction tests, because CI machines a slow.

extend snapshot test sleep

---

.github/workflows/release-libsql-server.yml
Cargo.toml

steps taken:
* remove allow-dirty from config
* cargo dist init
* rm ./.github/workflows/release-libsql-server.yml
* mv ./.github/workflows/release.yml ./.github/workflows/release-libsql-server.yml
* add libsql-server- prefix back to on:push:tags:
* add back allow-dirty
Note that this is applying a seemingly-pending change to your release notes. Previously you had set things up to use release-drafter, and `create-release=false` was set. Your config has a lingering `create-release=true` setting change.
By accepting this change, **it will now be an error for a draft release to exist**. cargo-dist will expect to create a release from scratch, and will use the changelogs it finds in your CHANGELOG/RELEASES files.

chore: update cargo-dist to 0.8.2

---

libsql-server/src/connection/libsql.rs

This PR fixes a series of bugs that caused hangs on the platform.
- Replace `is_stolen` `AtomicBool` by a `Mutex<bool>`. I'm not sure this one was necessary, but I was desperate.
- Always update the state for a connection, even in case of error during execution.
- An instance of `borrow_and_update` in a channel was borrowing too long, causing a dead_lock. This was caused by some obscure rules about temporaries, causing the reference to be dropped after the call, even though it was being dereferenced. This is best exemplified by https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c7bf7fbc2471c9bce121c781ebc982b, and elements of explanation can be found here: https://blog.m-ou.se/super-let/

limit the number of retries of the busy handler

---

libsql-server/src/query_analysis.rs
libsql/src/parser.rs

This pragma is useful for turning off foreign keys as a oneshot operation within current transaction.
Example from turso shell:
```
→  create table t(id);
→  create table t2(id, v references t(id));
```
```
-- First insert to t2 fails, because t has no row with value (6)
→  pragma foreign_keys=on; begin; insert into t2 values(5,6); insert into t values (6); commit;
Error: SQLite error: FOREIGN KEY constraint failed
```
```
-- First insert doesn't fail, because checking foreign keys is deferred
-- until the transaction finishes
→  pragma foreign_keys=on; begin; pragma defer_foreign_keys=true; insert into t2 values(5,6); insert into t values (6); commit;
OK
```

query_analysis: allow defer_foreign_keys pragma on primary

---

libsql-server/tests/hrana/batch.rs
libsql/src/hrana/stream.rs

This PR fixes the Hrana client issue when we were resetting last_insert_rowid in situations when sqld didn't return it. The correct behaviour (using SQLite local connection as reference) is to leave the last_insert_rowid unchanged. This PR fixes that and includes some tests to verify.

libsql client: don't reset last_insert_rowid

---

libsql-replication/src/frame.rs
libsql-server/Cargo.toml
libsql-server/src/namespace/mod.rs
libsql-server/tests/cluster/replication.rs

When we detect an error from the injector, we threat it a potential corruption, and reset the replica.

reset replica when injector detects potential corruption

---

libsql-server/src/lib.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/replication/mod.rs
libsql-server/src/replication/primary/logger.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-server/src/replication/script_backup_manager.rs
libsql-server/src/replication/snapshot.rs
libsql-server/tests/standalone/mod.rs
libsql/src/local/mod.rs
rust-toolchain.toml

This is a revision of scripted backups. This code was left unused for a long time, and it started to rot a bit, so I refreshed it with some improvements.
- The script is called with 4 arguments:
- The path where the snapshot can be found
- The namespace for that snapshot
- The starting replication index
- The end replication index
- The path passed as an argument is a hard link to the snapshot file. It is expected that the script removes it after the snapshot was ingested. Sqld will check for the existence of the snapshot file, on success, if the file is still present, this is considered, it will panic. On error, if the snapshot file *is not present* sqld will also panic. On restart, the leftover snapshots will be passed again to the script. The script must, therefore, ensure idempotency. …

scripted replication

---

.github/workflows/rust.yml
bindings/c/src/lib.rs
bindings/wasm/src/lib.rs
libsql-server/tests/cluster/mod.rs
libsql-server/tests/common/net.rs
libsql-server/tests/embedded_replica/mod.rs
libsql-server/tests/hrana/mod.rs
libsql-server/tests/namespaces/mod.rs
libsql-server/tests/standalone/mod.rs
libsql/benches/benchmark.rs
libsql/examples/deserialization.rs
libsql/examples/example.rs
libsql/examples/example_v2.rs
libsql/examples/flutter.rs
libsql/examples/local_sync.rs
libsql/examples/remote_sync.rs
libsql/examples/replica.rs
libsql/examples/transaction.rs
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/errors.rs
libsql/src/lib.rs
libsql/tests/integration_tests.rs
libsql/tests/replication.rs

This adds a new `Builder` type that can now be used to construct the `Database` type. This will scale better as we add more varied options. This commit also deprecates the old builder types and will produce a warning that will push users to using the new `Builder` type. This will then allow us to remove the old deprecated constructors at some point in the future.

libsql: add `Builder` to construct the db

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/local/database.rs
libsql/src/replication/mod.rs

This adds a new periodic sync configuration item to the `Builder` that will allow users to set a duration at which they want the background sync to sync.

libsql: add periodic background sync

---

vendored/rusqlite/Cargo.toml

Otherwise linker errors are to be expected -- wasmtime-bindings crate provides symbols necessary for WebAssembly runtime.

rusqlite: enable libsql-ffi/wasmtime-bindings feature for wasm

---

libsql-replication/src/injector/mod.rs

This PR fixes a replication bug that would happens sometimes when shcema changes where replicated. Sqlite would freak out because the schema was being modified without its knowledge. Setting `writable_schema=true` before injection solves the issue.

Fix replication bug

---

libsql-replication/proto/metadata.proto
libsql-replication/src/generated/metadata.rs
libsql-server/src/connection/config.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/query_analysis.rs
libsql-server/tests/namespaces/meta.rs
libsql/src/parser.rs
libsql/src/replication/connection.rs

With this proof-of-concept patch, other namespaces hosted on the same sqld machine can now be attached in readonly mode, so that users can read from other databases when connected to a particular one.
Turned off by default, can be turned on with admin API by setting `allow_attach = true`:
```
curl -H 'Content-Type: application/json' \
-d '{"block_reads": false, "block_writes": false,"allow_attach": true}' \
http://localhost:9090/v1/namespaces/default/config
```
The expected usage is to `ATTACH namespace-name AS namespace-name`, without any paths or flags, e.g.
```
ATTACH my_other_ns AS my_other_ns; SELECT * FROM my_other_ns;
```
Note that `turso db shell` sends separate statements in separate streams, so ATTACH will only be in effect if you put it in the same line.
Fixes TURSO-90.

libsql: attach databases from other namespaces as readonly

---

.github/workflows/extensions-test.yml
libsql-ffi/bundled/src/sqlite3.h
libsql-sqlite3/ext/crr/rs/core/src/create_cl_set_vtab.rs
libsql-sqlite3/ext/crr/rs/core/src/unpack_columns_vtab.rs
libsql-sqlite3/ext/crr/src/changes-vtab.c
libsql-sqlite3/src/pragma.c
libsql-sqlite3/src/sqlite.h.in
libsql-sqlite3/src/sqliteInt.h
libsql-sqlite3/src/vdbe.c
libsql-sqlite3/src/vtab.c
libsql-sqlite3/test/rust_suite/Cargo.toml
libsql-sqlite3/test/rust_suite/src/extensions.rs
libsql-sqlite3/test/rust_suite/src/lib.rs

fixes #865 
Earlier, we had [merged upstream changes](https://github.com/tursodatabase/libsql/pull/625) from SQLite 3.44.0 to libsql. The upstream had modified `sqlite3_module` struct by adding a new field `xIntegrity`. Prior to this, we had added a custom function field `xPreparedSql` to `sqlite3_module`. This change broke the crsqlite extension. 
To fix that, we added a [new struct](https://github.com/tursodatabase/libsql/pull/625#issuecomment-1813954922) `libsql_module` and moved `xPreparedSql` in it. We also added helper functions like `libsql_create_module` and `libsql_create_module_v2`. This change also prompted to modify `sqlite3_vtab` by adding filed pointing to `libsql_module`. This fixed the crsqlite extension.
Unfortunately, it broke sqlite-vss extension. The sqlite-vss …

bugfix: reset modifications of `sqlite3_vtab`

---

libsql-server/src/replication/primary/logger.rs

Remove the `to_compact` directory on recovery to prevent piling on files in case of crash.

remove to_compact on recovery

---

.github/workflows/nemesis.yml

Nemesis tests are failing due to lack of free space - https://github.com/tursodatabase/libsql/actions/runs/7884104131

Add a step to free disk space in nemesis tests

---

libsql-ffi/build.rs

As Lucio points out, we no longer do submodules for sqlite3mc so let's just drop the bogus `git submodule update` invocation.

libsq-ffi: Drop git submodule trickery from sqlite3mc build

---

libsql-server/src/config.rs
libsql-server/src/connection/config.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/test/bottomless.rs

To help migration to 0.23, this pr adds the flag `--allow-metastore-recovery`: if this flag is set, and the metastore is empty, then the metastore is seeded from the config files found in the `/dbs` subdirectories.

recover metastore from fs

---

Cargo.toml
libsql-replication/proto/metadata.proto
libsql-replication/src/generated/metadata.rs
libsql-server/src/connection/config.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/http/admin/mod.rs

Limit the maximum row size. The default is set to 5mb. This limit is configurable per-namespace with the `max_row_size` key.

limit row size

---

libsql/src/parser.rs

- Enable parsing `ATTACH` statement for any db
- Add tests for parsing `ATTACH` statements

Enable parsing `ATTACH` statement for any db

---

.github/workflows/server-pr-images.yml

This PR adds a workflow which builds and pushes the PR Docker image of sqld to `libsql-server-devel`. 
Note: This workflow is only triggered for internal users and the pull request body must contain a special string `+build`
+build

Build libsql-server images on PR

---

libsql/src/hrana/hyper.rs

This PR replaces existing `todo!()` on some of the Hrana variant of prepared statements.
This is a very rough implementation (ie. columns just return default, just like Statement impl for embedded replica in some of the cases), but in order to have a full 1-1 compatibility with SQLite behaviour on all edge cases, we would basically need to fully parse SQLite statement AST and get the data from there.

Implemented todos in Hrana Statement::params related methods

---

libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/rpc/replication_log.rs

Config changes were not being replicated to the replica, because it required the replication stream to the interupted. The PR interupts the replication stream when a config change for that namespace is detected, forcing the replica into a new handshake.

Fix configuration not being synced with replicas

---

libsql-server/src/error.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs

Redo of https://github.com/tursodatabase/libsql/pull/1055
It basically stores the relationship between shared schema db and databases linked to it:
The relationships are stored in form of shared_schema_links table in the meta store of a shared-schema db.
When we create a dependent db, we store a link in shared-schema.
When we destroy dependent db, we remove link from shared-schema.
When we destroy shared-schema, we first check if all dependent dbs are already destroyed. We fail if they don't.
Some known decifiencies:
1. No way to fetch the schema links yet
2. ~~Forking a db that links to a shared schema should add a link between a new fork and a shared schema but doesn't do it right now.~~

Shared schema

---

.github/workflows/extensions-test.yml

Closes: #1077 
ci: fix duplicated rust suites test
Only the `extensions` tests

ci: fix duplicated rust suites test

---

libsql-ffi/bundled/SQLite3MultipleCiphers/src/sqlite3mc_vfs.c
libsql-ffi/bundled/bindings/bindgen.rs
libsql-sqlite3/src/pager.c
libsql-sqlite3/src/wal.c

We had a segfault recently where libsql-server didn't have encryption enabled, but the underlying library did.
This PR fixes it.

Make sure the C code doesn't segfault

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs
libsql-server/tests/hrana/batch.rs
libsql-server/tests/standalone/mod.rs
libsql/src/connection.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/stream.rs
libsql/src/local/impls.rs
libsql/src/replication/connection.rs

Go has a pool of connections.
We need to reset baton in the connection every time it's returned to the pool.
Otherwise, user gets STREAM EXPIRED errors a lot.
This depends on https://github.com/tursodatabase/libsql/pull/1099

Go: Reset connection when it's returned to a pool

---

libsql-server/src/auth/authenticated.rs
libsql-server/src/query_analysis.rs
libsql-server/tests/standalone/attach.rs
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth-2.snap
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth-5.snap
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth.snap

- add test
- fix auth using attach alias instead of target

fix bad attach name

---

libsql-server/src/connection/libsql.rs
libsql-server/src/connection/program.rs

Factorize program execution in the Vm struct. Schema migration requires more flexibility with program execution, and the `Connection` trait is making it more complicated to work with.
depends on #1103

Factorize program execution in VM object

---

libsql-server/src/http/admin/stats.rs
libsql-server/src/stats.rs

Replaces https://github.com/tursodatabase/libsql/pull/1116
Example of stats API response:
```json
{
"id": "9bc71983-6631-49b8-8bf8-ba5e2d8abca0",
"rows_read_count": 270380571,
"rows_written_count": 38406,
"storage_bytes_used": 409600,
"write_requests_delegated": 0,
"replication_index": 99,
"top_queries": [...],
"slowest_queries": [...],
"embedded_replica_frames_replicated": 0,
"query_count": 233,
"elapsed_ms": 27159,
"queries": {
"id": "0268dcf7-d755-494d-8791-e698f6c0e4f9",
"created_at": 1709311047,
"count": 44,
"stats": [
{
"query": "SELECT * FROM a LIMIT 10000;",
"elapsed_ms": 189,
"count": 18,
"rows_written": 0,
"rows_read": 180000
},
{
"query": "SELECT * FROM a LIMIT 1000;",
"elapsed_ms": 37,
"count": 23,
"rows_written": 0,
"rows_read": 23000
},
{
"query": "SELECT * FROM a LIMIT …
```

Reset query stats at the beginning of every hour

---

Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/http/admin/stats.rs
libsql-server/src/stats.rs

This uses `hdrhistogram` to record `p50`, `p75`, `p90`, `p95`, `p99`, and `p99.9` of query latency.
If it works well, we may decide to add it per query too.
---
`hdrhistogram` uses constant memory given its range and `sigfig` parameter.
So usage does not go up as we add more records.
I've decided not to use the bounded version of the histogram because even though our latency should be below hundreds of thousands of milliseconds, I didn't want to risk an error or panic.
Some benchmarks around memory usage:
```
memory footprint with sigfig 2 and no records: ~1024
memory footprint with sigfig 2 and records between 0 and 1000: ~2048
memory footprint with sigfig 2 and records between 0 and 5000: ~3584
memory footprint with sigfig 2 and records between 0 and 100000: ~4096
memory footprint with …
```

Add query percentile support to stats

---

Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/connection/libsql.rs
libsql-server/src/http/admin/stats.rs
libsql-server/src/stats.rs

We need to be able to provide statistics about an individual query.
This is the first step, adding `count`, `elapsed_ms`, `rows_written`, and `rows_read`.
--- 
Those stats are not persisted on purpose, since we want them to be ephemeral and even reset from time to time.

Aggregated stats for queries with most elapsed_time

---

Cargo.lock
bottomless/Cargo.toml
bottomless/src/backup.rs
bottomless/src/bottomless_wal.rs
bottomless/src/completion_progress.rs
bottomless/src/lib.rs
bottomless/src/replicator.rs
libsql-server/src/database/primary.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs

This PR introduces a new feature to bottomless - ability to materialise tracker object, that can be awaited for in order to confirm that bottomless asynchronous upload matched the replication status at the moment of method call.

Bottomless savepoint

---

.github/workflows/rust.yml
libsql-server/Cargo.toml
libsql-server/tests/embedded_replica/mod.rs

When run with:
```
cargo test -F encryption --package libsql-server --test tests embedded_replica::embedded_replica_with_encryption
```
Fails with:
```
running 1 test
2024-03-04T13:28:35.019664Z ERROR tests::embedded_replica: sqlite error 21: API call with invalid database connection pointer
2024-03-04T13:28:35.019716Z ERROR tests::embedded_replica: sqlite error 21: misuse at line 180340 of [17129ba1ff]
2024-03-04T13:28:35.599894Z ERROR tests::embedded_replica: sqlite error 1555: abort at 15 in [INSERT INTO user (id) VALUES (1), (1);]: UNIQUE constraint failed: user.id
2024-03-04T13:28:35.604323Z ERROR tests::embedded_replica: sqlite error 21: API call with invalid database connection pointer
2024-03-04T13:28:35.604336Z ERROR tests::embedded_replica: sqlite error 21: misuse at line 180340 …
```

Embedded replicas encryption test

---

libsql-server/src/connection/libsql.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/store.rs
libsql-server/src/query_analysis.rs
libsql-server/src/rpc/streaming_exec.rs
libsql-server/src/schema/db.rs
libsql-server/src/schema/error.rs
libsql-server/src/schema/migration.rs
libsql-server/src/schema/mod.rs
libsql-server/src/schema/scheduler.rs
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__enqueue_migration_job-2.snap
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__enqueue_migration_job-3.snap
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__enqueue_migration_job.snap
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__pending_job-2.snap
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__pending_job-3.snap
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__pending_job.snap
libsql-server/src/schema/status.rs
libsql-server/tests/namespaces/shared_schema.rs

- Move migration related tables and ops to the schema module (`db.rs`)
- Prevent jobs for a schema from being enqueued, if there are already enqueued jobs for that schema
- Few robustness improverments
- more tests
- Some error handling

prevent task enqueue when pending task

---

libsql-server/src/schema/migration.rs
libsql-server/src/schema/scheduler.rs
libsql-server/src/schema/snapshots/libsql_server__schema__migration__test__already_performed_task_is_not_reexecuted.snap
libsql-server/src/schema/status.rs

When a job was already performed on a db, but the scheduler inquires again about its status, return the status immediately, and don't re-perform the operation.

handle job retry

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/local/database.rs
libsql/src/replication/mod.rs

Rename the configuration option for periodic sync to `sync_interval` to align with what we're doing with the rest of the SDKs.

libsql: Rename `periodic_sync` to `sync_interval`

---

libsql-server/src/error.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/schema/db.rs
libsql-server/src/schema/mod.rs
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__attempt_to_create_db_during_migration.snap
libsql-server/src/schema/status.rs

prevent updating/creating namespaces refering to a shared schema when there are pending migration on the schema

prevent namespace creation/update when there is a pending migration on shared schema

---

bindings/go/README.md

The Go SDK code lives in two places, but people are supposed to consume the one in the other repository. Let's add a small hint in this repository for people to find the right one.

bindings/go: Redirect people to Go SDK repository

---

libsql-server/src/database/schema.rs
libsql-server/src/error.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/query_result_builder.rs
libsql-server/src/schema/db.rs
libsql-server/src/schema/error.rs
libsql-server/src/schema/migration.rs
libsql-server/src/schema/mod.rs
libsql-server/src/schema/result_builder.rs
libsql-server/src/schema/scheduler.rs
libsql-server/tests/namespaces/shared_schema.rs
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__no_job_created_when_migration_job_is_invalid-2.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__no_job_created_when_migration_job_is_invalid.snap

Use `SchemaMigrationQueryBuilder` to collect migration error, and check migration task status

use custom query builder to collect migration error

---

libsql-server/src/http/admin/mod.rs

IOW, a db belonging to a shared schema, should always start empty.

Disallow creation of shared schema db with a dump

---

libsql-ffi/build.rs

The stack protector links to symbols like `strcpy_chk`, which are not available on musl. Therefore, disable it.
Fixes #1155

libsql-ffi: Disable stack protector for sqlite3mc on musl

---

libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/store.rs

Added a new method `store_and_maybe_flush` in MetaStore, which gives you an option to flush the config changes to disk.
The previous `store` method behaviour is not changed. It internally calls `store_and_maybe_flush` method, stores the config and flushes to disk.
This patch fixes a bug in fork. Earlier, we were flushing the target config before actually creating a fork. If the fork failed, MetaStore would have invalid data. Now, we store the config, without flush, create the fork. Iff successful, flush the target config to disk.

Add optional flush param when storing in MetaStore

---

libsql-server/tests/namespaces/shared_schema.rs
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__conflicting_data_migration-2.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__conflicting_data_migration-3.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__conflicting_data_migration.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__perform_data_migration-2.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__perform_data_migration-3.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__perform_data_migration-4.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__perform_data_migration.snap

- Added a test which performs data migration including inserts, updates and deletes
- Added a test which shows that schema migration fails if there is any conflicting data in the linked dbs

Add tests for data migration in schema dbs

---

libsql/Cargo.toml

Related to build issues on the docs.rs site due to ffi writing to the file system instead of the out dir.

libsql: bump 0.3.1 and remove all features for doc

---

libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/schema_lock.rs
libsql-server/src/namespace/store.rs
libsql-server/src/schema/scheduler.rs

- introduce schema lock
- synchronize migration with db creation

block migration during db operation

---

libsql-ffi/build.rs

Use `amalgamation` instead of `amalgation`.
Ref: https://www.merriam-webster.com/dictionary/amalgamation
Also in comments of `amalgamated` file

Fixed function `make_amalgamation` naming typo

---

libsql-server/tests/standalone/mod.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/mod.rs

This PR fixes the issue @haaawk and me originally noticed in libsql Go tests. It turns out, that the prepared statements - when calling `stmt.execute` - were always closing the stream, even if there was a transaction pending (created before prepare stmt).
I've also added standalone test that confirms the original issue.

Hrana: don't close the stream at the end of prepared statement execution

---

libsql-server/src/http/admin/mod.rs
libsql-server/src/http/user/mod.rs
libsql-server/tests/namespaces/shared_schema.rs

move the job status endpoints to the user API. adds two routes:
- `GET /v1/jobs`: list the job for the schema namespace that the `host` header key is pointing to
- `GET /v1/jobs/:id`: returns details for the specific job id
requires read permission to the schema

move migration api to user api

---

libsql-server/src/auth/authenticated.rs
libsql-server/src/auth/authorized.rs
libsql-server/src/auth/permission.rs
libsql-server/src/auth/user_auth_strategies/jwt.rs
libsql-server/tests/standalone/attach.rs

We don't try to merge legacy auth with new auth anymore. Legacy auth fields are ignored is new auth is present.

ignore legacy auth when new auth is present

---

bottomless/src/completion_progress.rs
bottomless/src/replicator.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/store.rs
libsql-server/src/schema/scheduler.rs

Accordingly to @haaawk request: this PR extends DELETE `v1/namespace/:ns` API with optional `{"keep_backup": bool}` option. If it's set, the database will be deleted locally, but we make sure that its state is preserved in the backup.
~~Question: _while we don't delete the backup, we still have pretty much no out-of-the-box way of restoring the db using it (other than using bottomless-cli which will be troublesome) after it was deleted this way._~~

Namespace::destroy: add parameter to perform soft delete (preserve backup)

---

vendored/sqlite3-parser/src/parser/ast/mod.rs
vendored/sqlite3-parser/src/parser/parse.y

This PR fixes a bug in the parser found by the fuzzer. A minimal example that would trigger it is:
```
SELECT
0
FROM
T
on''
```

fix parser error

---

Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/replication/snapshot.rs

use uuid v7 for log ids so that log ids can be ordered.

use uuid v7 for log id

---

.github/workflows/nemesis.yml

Right now nemesis would run on all the forks as well. This PR prevents that and makes nemesis run only for Turso

Fix: run nemesis only on source repository

---

bottomless/src/bottomless_wal.rs
bottomless/src/replicator.rs
libsql-server/src/connection/connection_manager.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/replication/primary/replication_logger_wal.rs

Build on top of #1237 
This PR enables setting up (through `export LIBSQL_BOTTOMLESS_SKIP_SNAPSHOT=true`) ability to skip snapshot generation when a checkpoint is being made. It still may happen if machine ie. recovered from backup after process restart (however it's just a matter of calling `snapshot_main_db_file(force)`).
This feature could work together with #1229 - backup WAL without snapshots on sqld server and periodically call snapshot creation from bottomless-cli on separate process.

Bottomless skip snapshot

---

libsql-server/src/connection/connection_manager.rs

There was a deadlock when a conn failed to upgrade to a write lock, because there's nothing to rollback. This happens in scenarios such as:
```
C1: BEGIN
C1: SELECT * FROM test
C2: INSERT INTO TEST
C1: INSERT INTO TEST
```
C1 fails to upgrade it's lock, but it has a shallow lock in the connection manager. Aborting the transaction would have no effect because it doesn't own a sqlite lock.

fix conn upgrade lock

---

libsql-server/src/namespace/mod.rs

Prevent primary to nuke itself if there is an error during load, unless the namespace didn't exist before load.

prevent primary to remove itself in case of load error

---

libsql-server/src/query.rs

In SQLite, it is invalid to pass a query with a ? or named parameter without a bind variable, unless you are just trying to explain the command.
We always fail those queries, but we shouldn't.

server: allow explain queries without bind parameters

---

libsql-server/src/replication/primary/logger.rs

We have a user with a failing snapshot, but we don't know why. We know rename returns EINVAL, which could happen for a variety of reasons, all of them related to the paths themselves.
By printing the path, we will be able to figure out the actual reason. Right now we're shooting in the dark.

Add more logging in case snapshots fail

---

libsql-ffi/build.rs

Make CC and CXX configurable for the build process. Allows us to, for example, make sure we're building with just clang on macOS.

libsql-ffi: Make CC and CXX configurable

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/local/connection.rs
libsql/src/replication/client.rs
libsql/src/replication/mod.rs

This commit fixes an issue where new connections for embedded replica's with write delegation would not create a new "connection" on the server causing weird issues with transactions and state. The fix here is to create a new `client_id` when creating a new writer for a new connection locally. This forces the server to use separate connections to execute the writes.
Closes #1283

libsql: fix embedded replica multiple txn

---

Cargo.toml

It's probably only temporary. Helpful to debug on the platform.

add debug info to release build

---

Cargo.toml

This reverts commit 342e4c368bce0b988500e619df27cf582914793a.
~CI is broken, let's get it to a healthy state and then we see how we go about this.~
CI was fixed by https://github.com/tursodatabase/libsql/pull/1301.
But the Docker image size increased ~4x from `142MB` to `571MB`.
Even though debug symbols can help us troubleshoot that difference is significant.
We should consider having a different registry/tag for debug builds, not replacing the main one with it.

Revert "add debug info to release build (#1297)"

---

libsql/src/local/database.rs
libsql/src/replication/remote_client.rs

When the client already has a session token we can try to prefetch next_frames during handshake.
For a replica in Sydney and primary in US it cuts the sync time from 400ms to 200ms.

Prefetch frames during handshake

---

libsql-server/src/query_analysis.rs
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__enqueue_migration_job.snap
vendored/sqlite3-parser/src/lexer/scan.rs
vendored/sqlite3-parser/src/lexer/sql/mod.rs

rather than using a query string reconstructed from the parsed AST, use the user query string.
Fixes https://github.com/tursodatabase/libsql/issues/1329

use user query string for queries rather than generated

---

libsql-server/src/rpc/proxy.rs

Holding a lock during query execution can lead to a deadlock if the transaction holding it is blocked by another transaction and that other transaction can't proceed because it can't get the lock that is held by the first transaction.
Fixes #1290

Stop holding lock during query execution

---

Cargo.toml
libsql-wal/Cargo.toml
libsql-wal/src/fs/file.rs
libsql-wal/src/fs/mod.rs
libsql-wal/src/lib.rs

This PR introduces the libsql-wal crate, that will contain the libsql custom wal implementation.
For now it only contains filesystem methods abstraction that the custom wal will use. Abstracting io/fs ops allows us to perform fault injection during testing.

libsql wal init

---

Cargo.lock
libsql-wal/Cargo.toml
libsql-wal/src/lib.rs
libsql-wal/src/name.rs
libsql-wal/src/registry.rs
libsql-wal/src/segment/mod.rs
libsql-wal/src/shared_wal.rs

Introduce `SharedWal` and `WalRegistry`
The `WalRegistry` manages wal instances and ressources from different databases. In libsql wal, the wal segments are managed by the registry, and so are the database files. All read and writes to the main file go through the wal.
The `SharedWal` brings all the different parts of the wal together.

libsql wal shared wal

---

README-libsql.md
README.md

Fixes some broken links to the Go libsql repo.
Original link pointed to `bindings/go`
Link should point to: https://github.com/libsql/go-libsql

fix readme: go-libsql link

---

libsql-hrana/src/proto.rs
libsql/src/connection.rs
libsql/src/errors.rs
libsql/src/hrana/hyper.rs
libsql/src/local/connection.rs
libsql/src/local/impls.rs
libsql/src/replication/connection.rs
libsql/src/replication/mod.rs
libsql/tests/integration_tests.rs

This new method executes a batch of statements atomically in a transaction.
This will be used by all SDKs to provide batch method.

Add Connection::transactional_batch

---

libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/store.rs

---
e.g. usage 
```
curl -X POST http://localhost:8080/v1/namespaces/b16397ca-d793-11ee-b439-acde48001123/checkpoint -H "Content-Type: application/json" -d {} -v
```

Add an admin endpoint to checkpoint

---

bottomless/src/bottomless_wal.rs
bottomless/src/replicator.rs
libsql-server/src/namespace/meta_store.rs

This PR fixes many issues that caused the metastore and bottomless to deadlock.
- blocking on `wait_for_snapshot`: instead of blocking to wait for snapshot, we return busy if the previous snapshot isn't ready yet. That prevents blocking when bottomless becomes unavailable.
- timeout on `wait_for_committed`: if all the send snapshot tasks failed, wait for committed would wait forever for an event that would never happen; since jobs are not enqueued, the whole connection would stale: checkpoint would wait for a recent enough committed index, and send loop would wait for checkpoint to flush new frames => deadlock. Instead, we timed out so that the connection would be throttled due to unavailability, but we can still make progress.
- Meta store deadlock: there was a slim chance that …

fix metastore deadlock

---

libsql-server/src/connection/libsql.rs
libsql-server/src/connection/program.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/database/schema.rs
libsql-server/src/hrana/batch.rs
libsql-server/src/query_result_builder.rs
libsql-server/src/rpc/proxy.rs
libsql-server/src/schema/mod.rs
libsql-server/tests/namespaces/shared_schema.rs
libsql-sqlite3/test/rust_suite/Cargo.toml

Only allow single transaction that wraps the whole migration.

Allow single transaction in schema migration

---

bottomless/src/replicator.rs
libsql-server/src/config.rs
libsql-server/src/main.rs
libsql-server/src/namespace/meta_store.rs

This PR adds the functionality to use temporary credentials to backup the database to S3. The AWS_SESSION_TOKEN can be optionally passed in to use temporary credentials locally or in an environment like EC2/EKS where roles are attached to the instance.
@avinassh Created a new PR as the old one had some problems with squashing commits.

add session_token for AWS short-term credentials

---

Cargo.lock
Cargo.toml
libsql-storage-server/Cargo.toml
libsql-storage-server/build.rs
libsql-storage-server/src/lib.rs
libsql-storage-server/src/main.rs
libsql-storage-server/src/memory_store.rs
libsql-storage-server/src/service.rs
libsql-storage-server/src/store.rs
libsql-storage-server/src/version.rs

This patch adds the storage gRPC server. It is based on the proto that was previously merged in https://github.com/tursodatabase/libsql/pull/1426
This adds a `FrameStore` trait which lets us implement different pluggable storage backends. Check the simple in-memory storage `InMemFrameStore` for a sample implementation

Add storage server

---

Cargo.lock
libsql-storage-server/src/memory_store.rs
libsql-storage-server/src/store.rs
libsql-storage/Cargo.toml
libsql-storage/proto/storage.proto
libsql-storage/src/generated/storage.rs
libsql-storage/src/lib.rs

This patch adds the RPC client for the storage server. It is based on the proto that was previously merged in #1426
This is a preliminary work and I expect it to go through several modifications. The transaction layer isn't correct, there are issues which will be fixed in the subsequent PRs. I have added appropriate TODOs. 
need your help / review in:
- The way I am storing tokio runtime and making RPC calls
- The transaction lock manager is very basic. I will probably implement the same way it is done in `libsql-wal` or do you have any alternative suggestions?

Add storage server RPC client

---

libsql-server/src/database/mod.rs
libsql-server/src/namespace/fork.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/store.rs
libsql-server/src/replication/replicator_client.rs
libsql-server/src/rpc/replication_log.rs
libsql-wal/src/wal.rs
libsql-wal/tests/oracle.rs

Allow shared schema database to be used with replication. There were two issues:
- the master schema database was not considered a primary, this is solved by exposing it's logger
- when we replicated a shared schema db without it's master first, a constraint was violated in the meta store. This is solved by forcing replication of the master schema first.

fix shared schema replicatioon

---

Cargo.toml
libsql-server/src/error.rs

- add libsql-server to default-members
- return NOT_FOUND when replica query unexisting namespace

categorize namespace doesnt exist error replicator

---

libsql-server/src/connection/dump/exporter.rs
libsql-server/src/http/user/dump.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/main.rs
libsql-server/src/namespace/mod.rs

dump import/export was using raw sqlite connection, thus bypassing libsql-wal. This PR fixes it.
I have removed the CLI to export dump because we can't rely on raw files anymore with libql-wal. Instead, one should use the http endpoint to export a dump.

fix dump import/export to support libsql-wal

---

libsql-ffi/build.rs

This pull request fixes `cross` builds in the libsql-js.git repository, caused by `CMake` picking up host compiler instead of the target compiler.

Fix cross build

---

libsql-ffi/build.rs

Windows build fails with "The network name cannot be found" error when built with encryption. That's because the std::fs::canocalize() function returns UNC paths on Windows, which confuses CMake to fail.
Switch to std::env::current_dir() instead, which returns paths that CMake can deal with.

ffi, build: Don't use UNC paths on Windows

---

libsql-storage-server/src/fdb_store.rs
libsql-storage-server/src/memory_store.rs
libsql-storage-server/src/redis_store.rs
libsql-storage-server/src/service.rs
libsql-storage-server/src/store.rs
libsql-storage/proto/storage.proto
libsql-storage/src/generated/storage.rs
libsql-storage/src/lib.rs

- Update proto to send `max_frame_no` while inserting frames so that we can have multiple writers
- cleanup: remove `insert_frame` method and impl. Use `insert_frames` instead
- Remove `FrameData`, use `Frame` from proto instead

Refactor and update storage server proto

---

libsql/src/connection.rs
libsql/src/errors.rs
libsql/src/lib.rs
libsql/src/load_extension_guard.rs
libsql/src/local/connection.rs
libsql/src/local/impls.rs

This adds a load_extension() API for loading SQLite extensions, which is API compatible with Rusqlite.
Fixes #402

libsql: SQLite extension loading support

---

.github/workflows/rust.yml
.github/workflows/server-pr-images.yml
Cargo.lock
Dockerfile
libsql-server/Cargo.toml
libsql-server/src/connection/connection_manager.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/src/schema/scheduler.rs

This patch adds the durable WAL from `libsql-storage` module to sqld. 
This has one (minor) breaking change. The CLI arg `use-libsql-wal` changed to `use-custom-wal` and it takes two options `libsql-wal` or `durable-wal`

Integrate durable WAL into libsql server

---

README.md

I have created a D driver for libsql (It uses the C driver but replacing the C header for a D version). 
A nice feature is that some tests are included using the Silly test runner for D.

Add a link to my (experimental) D driver based on the C driver.

---

Cargo.lock
Cargo.toml
libsql-server/Cargo.toml
libsql-server/src/broadcaster.rs
libsql-server/src/config.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/http/user/listen.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/src/metrics.rs
libsql-server/src/namespace/broadcasters.rs
libsql-server/src/namespace/fork.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/store.rs
libsql-server/src/test/bottomless.rs

Uses [SQLite's update hooks](https://sqlite.org/c3ref/update_hook.html) to allow users to listen for database changes.
Listening is pull-based, based on SSE.
This aims to offer a simple (implementation and API) and efficient (stateless, no need to query the table, nor store multiple versions of data) solution.
Users who want stricter guarantees should be able to combine this with other features to achieve their goals.
For instance, to get at least once delivery you can create a trigger that appends to an event table and listen to inserts to it.
To recover from crashes, clients can store the last processed entry somewhere (e.g. another libsql-server table).
---
Quirks to document and/or address:
- This will only work for rowid tables. Which excludes any virtual tables.
- This will not …

Proof of concept of CDC on libsql-server

---

libsql-server/src/lib.rs
libsql-server/src/namespace/name.rs
libsql-storage/src/lib.rs
libsql-sys/src/lib.rs
libsql-sys/src/name.rs
libsql-wal/benches/benchmarks.rs
libsql-wal/src/bottomless/job.rs
libsql-wal/src/bottomless/mod.rs
libsql-wal/src/bottomless/restore.rs
libsql-wal/src/bottomless/scheduler.rs
libsql-wal/src/bottomless/storage/fs.rs
libsql-wal/src/bottomless/storage/mod.rs
libsql-wal/src/bottomless/storage/s3.rs
libsql-wal/src/lib.rs
libsql-wal/src/registry.rs
libsql-wal/src/replication/injector.rs
libsql-wal/src/replication/replicator.rs
libsql-wal/src/shared_wal.rs
libsql-wal/tests/flaky_fs.rs
libsql-wal/tests/misc.rs
libsql-wal/tests/oracle.rs

Storage server requires namespace UUID to operate. In the `WALManager` we do not have access to the namespace, so this patch extracts the namespace from the `db_path`
The large diff is due to I moved `NamespaceName` from `libsql-wal` to `libsql-sys` so that `libsql-storage` also can use it. Or else I could copy the resolver method https://github.com/tursodatabase/libsql/blob/7ebe45b52/libsql-server/src/lib.rs#L672-L684 inside `libsql-storage` and use that.

Use the namespace resolver to extract namespace

---

libsql/src/local/connection.rs
libsql/tests/integration_tests.rs

`SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION` config verb require 2 additional arguments: `on/off` flag and pointer to the location where new state of the config will be written.
`libsql` misses last parameter which generally leads to UB and more specifically SEGFAULT under release builds (see https://github.com/tursodatabase/libsql/issues/1473)
This PR set second additional argument to null in order to comply with SQLite API specification.
See https://sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfigenableloadextension for the config verb description
- Add simple `enable_disable_extension` test which just trigger the method (better to load extension too - but it's a bit harder to setup)

provide one more required argument for SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION config command

---

libsql-server/src/database/schema.rs

In the previous iteration, we waited for the dry-run to succeed before returning the result of a schema migration. Instead, wait for the migration to complete before returning, as this is less confusing to users.

wait for migration task to finish

---

libsql-server/src/lib.rs
libsql-server/src/main.rs

Sqlite and sqld use a different allocator, which can cause memory fragmentation. This PR provides a custom allocator for sqlite that uses rust's global allocator (mimalloc).

use mimalloc for sqlite

---

bottomless/src/replicator.rs

Fix a bug in restoring from uncompressed snapshot where the file extension was hardcoded to `.db` when everywhere else, it was `.raw`. This caused the restore function to reccurse in the generation until it hit the first generation, effectively discarding everything.

fix bottomless bug when restoring from uncompressed snapshots

---

bottomless/src/bottomless_wal.rs
libsql-server/src/database/mod.rs
libsql-server/src/database/primary.rs
libsql-server/src/database/schema.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/replication_wal.rs
libsql-server/src/schema/scheduler.rs

When locking the replicator in the wal, bottomless assumed that it could hold on the lock across await points because the lock was uncontended. This assumption was not true, so when another thread tried to acquire the lock from a runtime thread, there was a slim chance that the reactor was on that thread, and the runtime would get blocked. the checkpointing thread could not make any progress because the runtime was blocked, and the runtime thread could not acquire the lock, because the checkpointing thread could not make progress. IOW, a deadlock.
This PR replaces the replicator lock from a std for an async lock. This is, of course, a poor man's fix, but it's not worth making any better with bottomless2 being cooked.
/!\: with an async replicator lock, be careful to always call sqlite in …

fix bottomless deadlock

---

libsql-server/src/lib.rs

since fragmentation is not the cause of the leak, put the sqlite mimalloc allocator behind a flag for now

flag sqlite mimalloc allocator

---

Cargo.lock
libsql-wal/Cargo.toml
libsql-wal/src/replication/injector.rs
libsql-wal/src/replication/replicator.rs
libsql-wal/src/replication/snapshots/libsql_wal__replication__replicator__test__stream_from_current_log-2.snap
libsql-wal/src/replication/snapshots/libsql_wal__replication__replicator__test__stream_from_current_log-3.snap
libsql-wal/src/replication/snapshots/libsql_wal__replication__replicator__test__stream_from_current_log-4.snap
libsql-wal/src/replication/snapshots/libsql_wal__replication__replicator__test__stream_from_current_log.snap
libsql-wal/src/segment/current.rs
libsql-wal/src/transaction.rs

The previous implementation was reading 1 frame too many. The new implementation selects frames from the segment index to read the minimum amount of frames to bring the replica up to date.
The new segment index is probably too slow, I'll optimize the datastructure in a followup.

fix current segment replicator

---

libsql-server/src/lib.rs

benign because mimalloc ignores the layout

fix allocator bug

---

Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/http/admin/mod.rs
libsql-server/src/lib.rs

This PR introduces a in-process heap profiler, using [hipptrack](https://github.com/MarinPostma/hipptrack).
The profiler is enabled by sending a request to the admin api:
```
echo '{}' | POST /profile/heap/enable
```
when enabled, hipptrack will start recording all allocation. The name of the profile is returned by the call to the endpoint.
to stop recording and download the profile:
```
POST /profile/heap/disable/:profile-id
```
this will download a tarball of the profile. The profile can then be analyzed using hipptrack:
```
POST /profile/heap/disable/hip-84397533 > profile.tar
tar xvf profile.tar
hipptrack hip-84397533 profile.db
sqlite3 profile.db
```
to remove the profile file from the server:
```
DELETE /profile/heap/:profile-id
```

add in-process heap profiler

---

.gitignore
bindings/c/Cargo.toml
bindings/c/Makefile
rust-toolchain.toml

Adds the necessary scripts to build the C bindings for iOS and Android which the in turn only need to be dropped into iOS/Android projects to be used via Obj-C++ or Android's JNI.
For my specific use case I use them in op-sqlite.

React Native support

---

libsql/src/hrana/hyper.rs
libsql/src/hrana/mod.rs
libsql/src/local/impls.rs
libsql/src/local/statement.rs
libsql/src/replication/connection.rs
libsql/src/statement.rs

The `execute()` method returns an error if the query returns rows, which makes it unsuitable for running any type of SQL queries. Similarly, the `query()` method only works on SQL statements that return rows. Therefore, the `run()` method is provided to execute any type of SQL statement.
This is needed, for example, for the libSQL JavaScript library that needs to preserve `better-sqlite3` semantics.

libsql: Add Statement::run() API

---

libsql/src/connection.rs
libsql/src/hrana/connection.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/stream.rs
libsql/src/local/connection.rs
libsql/src/local/impls.rs
libsql/src/replication/connection.rs

It's a rusqlite API that we're missing.

libsql: Add Connection::total_changes() API

---

libsql-sqlite3/src/main.c

TCL `recoverfault` tests are failing in master right now with the following error:
```
$> ./testfixture ext/recover/recoverfault.test
recoverfault-1.0... Ok
recoverfault-1-oom-persistent.1... Ok
recoverfault-1-oom-persistent.2... Ok
free(): invalid pointer
[1]    415207 IOT instruction (core dumped)  ./testfixture ext/recover/recoverfault.test
```
This is indeed happens due to the bug (rather minor - but still): if `sqlite3MutexAlloc` will fail during open call wal manager will be destroyed incorrectly with `sqlite3_free` function while it can be statically allocated.
Use dedicated `destroy_wal_manager` function which takes into account lifetime of the wal manager
Compiled `testfixture` and run it locally

use dedicated destroy_wal_manager function to destroy wal as it can be static

---

.github/workflows/c-bindings.yml

Follow up for #1514. I forgot to generate bundled C code for rust bindings with fix in `openDatabase` function.
- Run `cargo xtask build-bundled`
- Add `c-bundle-validate` which check that C code for FFI in repo is up to date with `libsql-sqlite3` sources. In case of mismatch job will fail with the following error:
```
$> Run git diff --quiet || (echo "found uncommited changes in the bundle; please run 'cargo xtask build-bundled' and commit the result" && exit 1)
found uncommited changes in the bundle; please run 'cargo xtask build-bundled' and commit the result
Error: Process completed with exit code 1.
```

add CI job to validate that bundle is up to date

---

libsql-storage/src/lib.rs
libsql-storage/src/local_cache.rs

Previously, `libsql-storage` stored all the data in-memory. It kept a in-memory frame cache and also cached all the transient transaction writes in-memory. This patch changes it to store the data on local disk. This data is transient in nature, disk loss should not cause any issues.

Move in-memory cache to disk

---

Cargo.lock
libsql-storage-server/Cargo.toml
libsql-storage-server/src/errors.rs
libsql-storage-server/src/fdb_store.rs
libsql-storage-server/src/main.rs
libsql-storage-server/src/memory_store.rs
libsql-storage-server/src/redis_store.rs
libsql-storage-server/src/service.rs
libsql-storage-server/src/store.rs
libsql-storage/src/lib.rs

- Storage server now uses `max_frame_no` from the txn to read frames
It will make sure to not read any frames beyond the `max_frame_no`
of the transaction. This fixes the bug in the isolation level.
- Storage server now checks `max_frame_no` before inserting. If it
has changed meanwhile, then it rejects the insertion request.
This lets us have multiple (non concurrent) writers or even multiple
logical primary instances.
Minor changes:
-  Improved the way we handle keys in Foundation DB
- Added basic tonic error handling

Use `max_frame_no` for transaction reads and writes

---

.github/workflows/storage-server-images.yml

forgot this in #1523 
this patch updates the workflow to generate the images with `latest` tag

Update workflow to release a `latest` dev image

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-server/src/connection/program.rs
libsql-sqlite3/src/vdbe.c

The rows read/written counters are stores in a u32, that can overflow. This PR "fixes" that by saturating the counter. This is a temporary fix, since increasing the size of the counter is more work than we are willing to put in right now.

fix overflow in row counters

---

libsql-server/src/error.rs
libsql-server/src/http/admin/mod.rs
libsql-wal/src/bottomless/storage/fs.rs

return an error when file pointed to by dump is not a file.

error out when dump is not a file

---

libsql-storage-server/src/fdb_store.rs

It is important to verify that the data we got from Foundation DB matches with what we want, since we are doing a range query.
for example, say we searched for ('db_name42', 10, 20). If this page does not exist, then it could match with ('db_name41', 10, 20) or with ('db_name42', 9, 20) since it does lexicographic search.

fix: prevent incorrect range queries when searching for a page version

---

libsql-sqlite3/src/alter.c
libsql-sqlite3/src/parse.y
libsql-sqlite3/src/sqliteInt.h
libsql-sqlite3/test/libsql_alter.test
libsql-sqlite3/test/rust_suite/src/alter_column.rs

Current `LibSQL` code for analyzing `ALTER TABLE t ALTER COLUMN x TO x ...` just takes raw string after second column name and use it as a column definition with only `;` (semicolon) stripped from the end.
This can lead to bad column definition as extra white spaces (like in https://github.com/tursodatabase/libsql/issues/1517) or comments can be prepended to the `ALTER TABLE` command (for example, `ALTER TABLE t4 ALTER COLUMN x TO x INTEGER DEFAULT(-1); -- some explanation` should be valid, but with current approach it will be translated to the incorrect SQL: `CREATE TABLE t ( x  INTEGER DEFAULT(-1); -- some explanation )`; note semicolon in the middle of `CREATE TABLE` expression)
This PR fixes new column sql definition by propagating parsed part of the expression directly from parser
- …

adjust ALTER COLUMN parsing

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-sqlite3/src/alter.c
libsql-sqlite3/test/libsql_alter.test
libsql-sqlite3/test/rust_suite/src/alter_column.rs

`ALTER COLUMN` doesn't work for tables with associated indices/triggers (for example https://github.com/tursodatabase/libsql/issues/1299) and failing with the error:
```
libsql> CREATE TABLE t(id);
libsql> CREATE INDEX i ON t(id);
libsql> ALTER TABLE t ALTER COLUMN id TO id;
Runtime error: error in adding id to t: Only ordinary tables can be altered, not indexes
```
But actually, since LibSQL only changes column "attributes" (not name) - this operation is safe and doesn't affect indices/triggers/etc in any way
- This PR apply rename command only to the table and ignores all other potential associated entities

apply alter column command only to the table

---

libsql-sqlite3/Makefile.in
libsql-sqlite3/Makefile.msc
libsql-sqlite3/configure
libsql-sqlite3/configure.ac
libsql-sqlite3/ext/crr/Makefile
libsql-sqlite3/src/func.c
libsql-sqlite3/src/sqliteInt.h
libsql-sqlite3/src/vector.c
libsql-sqlite3/src/vectorInt.h
libsql-sqlite3/src/vectorfloat32.c
libsql-sqlite3/src/vectorfloat64.c
libsql-sqlite3/test/all.test
libsql-sqlite3/test/libsql_vector.test
libsql-sqlite3/tool/mksqlite3c-noext.tcl
libsql-sqlite3/tool/mksqlite3c.tcl
libsql-sqlite3/tool/mksqlite3internalh.tcl

This PR adds native support for vector functions in the LibSQL.
This PR were extracted from the branch https://github.com/tursodatabase/libsql/pull/1402/ in order to make review more granular and simpler
- Vectors are represented as binary blobs with vector components encoded in little-endian format according to IEEE-754 standard
* `LibSQL` now supports f32/f64 vectors of any dimension not more than 65536 (see `MAX_VECTOR_SZ`)
* Zero-length vectors are supported - and they are always represented as zero size BLOB (**not** NULL)
- `LibSQL` can extended vector encoding on disk with 1 trailing byte which will encode vector type information (for now: `1 = F32, 2 = F64`).
```
[F3 76 86 C4] [BC 9D F1 3F] [01] - this is f32 vector because type equals to 0x01 = 1 (value = [-1075.72,1.88763])
[F3 …
```

feat(vector): add basic functions (vector/vector_extract etc)

---

.github/workflows/c-bindings.yml
.github/workflows/extensions-test.yml
.github/workflows/golang-bindings.yml
.github/workflows/rust.yml
.github/workflows/sqlite3.yml

Cancel previous run if new commits were pushed to the branch for several long actions which do some testing staff (just to be thoughtful users of GitHub Actions):
- c-bindings.yml
- extensions-test.yml
- golang-bindings.yml
- rust.yml
- sqlite3.yml
Example of how it looks in the UI:

cancel previous running actions if new commits are pushed

---

libsql-replication/proto/metadata.proto
libsql-replication/src/generated/metadata.rs
libsql-server/src/connection/config.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/http/admin/mod.rs

SQLite allows setting synchronous values to any four levels. This
patch provides an option to set the level for a namespace which will
be used for every connection. It defaults to `NORMAL`.
allowed values: https://www.sqlite.org/pragma.html#pragma_synchronous
e.g. to enable:
curl -X POST http://sqld-admin-endpoint/v1/namespaces/<namespace>/config -H "Content-Type: application/json" -d '{"durability_mode": "strong"}' -v

Make PRAGMA `synchronous` configurable for a Namespace

---

libsql-wal/Cargo.toml
libsql-wal/src/checkpointer.rs
libsql-wal/src/lib.rs

introduce the checkpointer.
The checkpointer performs checkpoint for databses in the background. When a namespace is ready to be checkpointed, the checkpointer if notified, and will schedule the database for checkpointing.

introduce checkpointer

---

libsql-storage/src/lib.rs
libsql-storage/src/local_cache.rs

Till now, `DurableWAL` used Storage Server for finding page versions. If the local cache's `max_frame_no` is same as storage server's and if a txn's `max_frame_no` is less or same as cache's `max_frame_no`, then all reads and writes can proceed using local data itself. Do note that writes from a stale primary will be rejected anyways, since we handle conflicts at Storage Server.
Currently, there is no replication built and it assumes a single primary writer. So, after write, it updates the local cache. In the future PRs, I will add replication. 
What's changed: 
- Update the cache after writes
- Use local cache for most operations
What's next:
- A primary can lag anytime, so we need replication or way to quickly bring up the cache to speed
- If the primary is lagging, we switch to remote …

Improve local cache and prefer local reads

---

libsql-server/src/auth/constants.rs
libsql-server/src/auth/mod.rs
libsql-server/src/auth/parsers.rs
libsql-server/src/auth/user_auth_strategies/disabled.rs
libsql-server/src/auth/user_auth_strategies/http_basic.rs
libsql-server/src/auth/user_auth_strategies/jwt.rs
libsql-server/src/auth/user_auth_strategies/mod.rs
libsql-server/src/hrana/ws/session.rs
libsql-server/src/http/user/extract.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/rpc/proxy.rs
libsql-server/src/rpc/replica_proxy.rs
libsql-server/src/rpc/replication_log.rs

every auth strategy now advertises the headers it needs by implementing required_fields method
the higher layer is responsible for providing the fields in UserAuthContext
UserAuthContext is not passed in as a result type, it is always required
if the higher layer is not able to provide required_fields, it should assume the particular auth strategy will not work
if required fields are not provided, auth strategy should not attempt to fall back unless there is a clear algorithm to do so

implemented custom headers passing in auth layer

---

libsql-sqlite3/Makefile.in
libsql-sqlite3/src/test_libsql_diskann.c
libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/vectorIndexInt.h
libsql-sqlite3/tool/mksqlite3c.tcl

Second branch in the series for DiskANN implementation. This PR introduce few utility functions and classes which aims to simplify interop between SQLite & DiskANN implementation
- `VectorIdxParams` - binary container of vector index params. Instead of storing parameters in the rigid schema we decided to use binary format over which we have full control (so we can add parameters dynamically without complicated schema changes and control default values easily)
* The format by itself is very simply: every value in container spans 9 bytes when first byte interpreted as a tag and 8 next bytes interpreted as an u64 integer or f64 float
- `VectorInRow` - container which stores input row for `INSERT`/`DELETE` operations
- `VectorOutRows` - container which stores output rows for `SEARCH` …

Vector aux functions

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs
bindings/c/src/types.rs

Expose interval sync in C bindings.
Fixes #1561

Add libsql_open_sync_with_config

---

libsql-server/src/connection/dump/exporter.rs

There are few minor issues with current implementation of `.dump` command in the `sqld`:
1. It stop after first `VIRTUAL TABLE` or table with `sqlite_` prefix - which is a bug
```sql
$> CREATE VIRTUAL TABLE email USING fts5(sender, title, body);
$> CREATE TABLE t ( value );
$> INSERT INTO t VALUES (1), (2);
$> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
PRAGMA writable_schema=ON;
INSERT INTO sqlite_schema(type,name,tbl_name,rootpage,sql) VALUES('table','email','email',0,'CREATE VIRTUAL TABLE email USING fts5(sender, title, body)');
PRAGMA writable_schema=OFF;
COMMIT;
```
2. It emit incorrect dump if `sqld` decides to preserve `rowid`:
```sql
$> CREATE TABLE t ( x INTEGER PRIMARY KEY DESC );
$> INSERT INTO t VALUES (1), (2), (10);
$> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION; …
```

fix .dump export command

---

docs/DOCKER.md

Was trying to explore LibSQL and run some of the commands that were in the docs. Noticed some strange behavior and found some trailing spaces that were causing issues in my shell.
```sh
➜  ~ docker run --name some-sqld  -p 8080:8080 -ti \ 
-e SQLD_NODE=primary \
--platform linux/amd64 \
ghcr.io/tursodatabase/libsql-server:latest
docker: invalid reference format.
See 'docker run --help'.
zsh: command not found: -e
```
By removing the trailing space, the command works properly

Remove Trailing Spaces from Docker Docs

---

Dockerfile
Dockerfile.dev
docker-wrapper.sh
docs/DOCKER.md

We are using `USER` command to run `sqld` process from `sqld` user but this is quite non-flexible. For example, if we will try to mount local user directory to the container it will fail with an error:
```sh
$> docker run --name some-sqld -it \
-v $(pwd):/var/lib/sqld \
-e SQLD_NODE=primary \
ghcr.io/tursodatabase/libsql-server:latest /bin/sqld
...
Error: Permission denied (os error 13)
```
This PR changes the way we spawn `sqld` process: now we run `docker-wrapper.sh` with root permission which internally change permission of the data dir recursively and then spawn `docker-entrypoint.sh` from the `sqld` user with the [`gosu`](https://github.com/tianon/gosu) utility

use gosu instead of native docker USER in the entrypoint

---

libsql-sqlite3/src/build.c

`quick.test` failing with debug build due to broken invariants:
```
recoverfault-1-oom-persistent.1428... Ok
testfixture: sqlite3.c:127443: sqlite3KeyInfoOfIndex: Assertion `pParse->rc==SQLITE_ERROR_MISSING_COLLSEQ' failed.
[1]    180982 IOT instruction (core dumped)  ./testfixture test/quick.test
```
This is due to violation of sqlite3 invariant which was introduced in the PR #1571 
This PR align our patch with sqlite invariants and expectations

set error to pParse and preserve internal invariant about possible error inside the condition

---

libsql-server/src/query_analysis.rs
libsql-server/tests/hrana/batch.rs
libsql/src/parser.rs

`REINDEX` ([native](https://www.sqlite.org/lang_reindex.html) SQLite statement) is not recognized statement by libsql but it's pretty safe and we should support it.
Also, it can be useful for vector indices to rebuild them from scratch.

allow reindex statement in libsql

---

libsql-sqlite3/src/build.c
libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/vectorIndexInt.h
libsql-sqlite3/test/libsql_vector_index.test

`.dump` and `VACUUM` command now works incorrectly because `SQLite` "confused" about vector index properties: usually indices are "storage-full" and has the data by themself, but vector indices are "storage-less" and offload all storage routines to another tables.
This leads to class of errors when mentioned commands trying to execute same inserts twice: first when shadow table is populated and then when index is created.
This PR aims to solve this issue for `.dump` and `VACUUM` command by following tricks (or you may call them "hacks"):
1. We we completely ignore writes/deletes during `VACUUM` (which can be detected by `mDbFlags & DBFLAG_VACUUM != 0` condition)
2.  In case of conflict in the metadata table during index creation we will deliberately skip refill operation for this vector …

fix dump and vacuum of vector indices

---

bottomless-cli/src/main.rs

This PR extends bottomless-cli with an ability to generate a snapshot option. Example usage:
```bash
bottomless-cli -e "<aws-endpoint>" -b "<bucket>" -d "<local-db-dir>" -n "ns-<db-id>:<namespace>" snapshot -g "<generation>"
```
If you don't know what generations are out there you can run:
```bash
bottomless-cli -e "<aws-endpoint>" -b "<bucket>" -d "<local-db-dir>" -n "ns-<db-id>:<namespace>" ls
```
To test - given that you have a local bottomless storage with at least 2 generations dependent on each other:
1. Go to a generation folder in AWS. **Ensure that this folder has `.dep` file**. Remove `db.zstd` and `.changecounter` files - this will make bottomless treat the generation as if it had no snapshots. `export RUST_LOG=info,bottomless=debug` for better visibility. *At this point …

bottomless-cli: added snapshot command

---

Cargo.lock
libsql-sqlite3/test/libsql_vector_index.test
libsql/Cargo.toml
libsql/tests/integration_tests.rs

Add simple "fuzz"-test which just execute multiple `INSERT/UPDATE/DELETE/SEARCH` operations against table with vector index + extend TCL test suite with couple more potentially tricky cases (rollback of the transaction and table with several vector columns)
fuzz-test is `ignored` by default but can be ran on demand with following command (on my laptop it runs within 15 minutes):
```sh
$> cargo test vector_fuzz_test -- --nocapture --include-ignored
...
running 1 test
============== ATTEMPT 0 (seed 5584570835305270879u64, dim 163, operations 1) ================
...
============== ATTEMPT 9999 (seed 11747876430315692925u64, dim 899, operations 73) ================
test vector_test ... ok
...
```

add more tests for vector feature

---

libsql-server/src/config.rs
libsql-server/src/main.rs
libsql-server/src/namespace/meta_store.rs

This adds a new flag that when set to true will destroy the metastore and start with a fresh db file when restore runs into issues. This is a temp fix to for larger metastore restore issues that include disk malformed issues that we have seen.

server: flag to destroy metastore on restore err

---

libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/vectorIndexInt.h
libsql-sqlite3/src/vectordiskann.c
libsql-sqlite3/test/libsql_vector_index.test

Now we hard coded 65536 as a default block size which is waste of space especially when we are working with relatively low-dimensional embeddings (like 64d). 
This PR introduces `max_edges=[int]` index parameter and also estimate reasonable default in case if parameter is omitted.
The logic behind current estimate is the following:
1. We don't want to have uncontrollable write amplification - so we should have hard upper bound for disk amplification due to neighbours redundancy in every node block. Current hard limit is `50x` redundancy compared to the node storage overhead (note, that with compression of neighbours this hard limit will automatically adjust and allow us to store more neighbours per node block)
2. The amount of neighbours should grows with the dimension of the embeddings …

Vector search adaptive block

---

libsql-sqlite3/src/vector.c
libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/vectordiskann.c
libsql-sqlite3/src/vectorfloat32.c
libsql-sqlite3/src/vectorfloat64.c
libsql-sqlite3/test/libsql_vector.test
libsql-sqlite3/test/libsql_vector_index.test

In order to boost DX we better to make errors messages concise and clean. This PR slightly improve details of errors message around vector/vectorIndex features + adds simple common structure for them like this:
1. `vector: ` prefixes all errors about plain vectors
2. `vector index: ` prefixes all errors during vector index creation stage
3. `vector index(insert/delete/search): ` prefixes all errors during corresponding vector index operation

refine errors for vector search

---

libsql-sqlite3/src/build.c
libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/vectorIndexInt.h
libsql-sqlite3/src/vectordiskann.c
libsql-sqlite3/test/libsql_vector_index.test

Initially, this PR aimed to change behaviour of vector index to prefer use PK over ROWID if both available, but we decided to preserve current vector index behaviour to always prefer ROWID (if any) because it aligned with SQLite native B-Tree indices behaviour.
Still, this PR introduce few useful changes:
1. `bUnordered=1` set for vector index in order to prevent SQLite from using vector index in different optimizations
2. `vectorIdxKeyGet` implemented more carefuly - now it look at the structure of index key and will adapt to what we will decide about index key structure during it's creation (so, we can more easily change behaviour in future if we will need this)
3. vector index shadow table now always define `INTEGER PRIMARY KEY` in order to preserve rowid (and PK) in dumps

vector search index key fix

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs

Add new `libsql_load_extension` function to C bindings to make it possible to load an extension on a connection.
This is needed for multiple things like allowing extensions in Go client or supporting CRSQLITE in OPSQLITE on mobile.

C bindings: Loading extensions

---

libsql-server/src/connection/dump/exporter.rs
libsql-server/src/connection/dump/snapshots/libsql_server__connection__dump__exporter__test__table_preserve_rowids.snap
libsql-server/src/http/user/dump.rs

SQLite support several arguments for `dump` command and `preserve-rowids` is one of them:
```
.help .dump
.dump ?OBJECTS?          Render database content as SQL
Options:
--data-only            Output only INSERT statements
--newlines             Allow unescaped newline characters in output
--nosys                Omit system tables (ex: "sqlite_stat1")
--preserve-rowids      Include ROWID values in the output
OBJECTS is a LIKE pattern for tables, indexes, triggers or views to dump
Additional LIKE patterns can be given in subsequent arguments
```
It can be particularly useful for vector indices because internally they use `ROWID` by default and internal index on-disk data contains `ROWID` values

add preserve_rowids query parameter to align with native SQLite shell feature

---

libsql-server/src/connection/libsql.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/http/user/timing.rs

this pr adds timing information to response headers.
the `recored_time` allows to easily add new timing info the the headers, from (almost) anywhere in the codebase

add timing infos to response header

---

libsql-wal/Cargo.toml
libsql-wal/src/checkpointer.rs
libsql-wal/src/error.rs
libsql-wal/src/io/file.rs
libsql-wal/src/io/mod.rs
libsql-wal/src/lib.rs
libsql-wal/src/registry.rs
libsql-wal/src/replication/injector.rs
libsql-wal/src/replication/replicator.rs
libsql-wal/src/segment/current.rs
libsql-wal/src/segment/list.rs
libsql-wal/src/segment/mod.rs
libsql-wal/src/segment/sealed.rs
libsql-wal/src/shared_wal.rs
libsql-wal/src/storage/mod.rs
libsql-wal/src/transaction.rs
libsql-wal/src/wal.rs
libsql-wal/tests/flaky_fs.rs
rust-toolchain.toml

The goal of this PR is to make the current segment recoverable in case of a crash. Taking inspiration from SQLite's wal, we introduce a grinning checksum to the current log, where each frame is hashed with the hash of the previous frame. If we find an unsealed segment on startup, we enter recovery mode for that segment, meaning that we iterate over its frames, recomputing the checksums. We stop whenever we hit a checksum that breaks the list invariant and patch the segment. This means that in NORMAL synchronous mode, we can lose committed data on the crash, but this is expected. We'll introduce a more robust sync mode later that flushes on every commit and has stronger guarantees.
This scheme introduces a bit more complexity:
- double flush on seal: on seal, we first flush all data to …

current segment recovery

---

libsql-wal/src/error.rs
libsql-wal/src/lib.rs
libsql-wal/src/segment/compacted.rs
libsql-wal/src/segment/current.rs
libsql-wal/src/segment/mod.rs
libsql-wal/src/segment/sealed.rs

right now, libsql-wal only support 4096 page size, but if we want to support other page size in the future, this will make it easier

add page size to segment header

---

libsql-server/src/main.rs

`Authornization` -> `Authorization`

Fix typo in the auth header name in the --heartbeat-auth cli option

---

libsql-server/src/main.rs

I didn't understand what this option would enable and how to access the console. Only after finding [this commit](https://github.com/tursodatabase/libsql/commit/101115e73e4a0e85163072248837194935b6d6c9) it became clear. With a description already in the cli this is easier to find.

Add description for the --enable-http-console cli option

---

libsql-replication/src/replicator.rs
libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/local/database.rs
libsql/src/replication/mod.rs
libsql/src/replication/remote_client.rs

This PR changes the return type of sync to a struct that provides the current commit fno and how many frames that sync call required. This should give more insight to users to understand how much data has been synced.

libsql: provide more return info for sync

---

libsql/src/connection.rs

Update the docs to specify which connections types actually return rows.

libsql: update batch docs on conn type allowed

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-sqlite3/src/sqliteInt.h

We don't support SEH on Windows because of WAL virtualization so let's just disable it in the source code. This comes after spending 30 minutes of quality time with our build system and CMake in an attempt to disable it externally...

Explicitly disable SEH on Windows

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-server/tests/hrana/batch.rs
libsql-sqlite3/src/vectorIndex.c

In one part of the vector search code we relying on the `SQLITE_CONSTRAINT` but since by default we enable `sqlite3_extended_result_codes` - the real return code will be more detailed.
In order to fix this we need to compare lower bits of the error code: `rc & 0xff`

Vector search fix error handling

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-sqlite3/src/vacuum.c
libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/test/libsql_vector_index.test

Follow up after PR https://github.com/tursodatabase/libsql/pull/1591
Previous PR ignored vector index modifications during VACUUM operations. This fixed issue with VACUUMing only for tables without ROWID because for tables with ROWID vector index will preserve old identifiers while rowid in base table after vacuum can change:
```
libsql> CREATE TABLE t_vacuum ( emb FLOAT32(2) );
libsql> INSERT INTO t_vacuum VALUES (vector('[1,2]')), (vector('[3,4]')), (vector('[5,6]'));
libsql> CREATE INDEX t_vacuum_idx ON t_vacuum(libsql_vector_idx(emb));
libsql> DELETE FROM t_vacuum WHERE rowid = 2;
libsql> SELECT rowid FROM t_vacuum;
1
3
libsql> SELECT rowid FROM t_vacuum_idx_shadow;
1
3
libsql> VACUUM;
libsql> SELECT rowid FROM t_vacuum;
1
2
libsql> SELECT rowid FROM t_vacuum_idx_shadow;
1
3
```
This …

fix behaviour of VACUUM for vector indices to make rowid consistent between shadow tables and base table

---

libsql-wal/src/lib.rs
libsql-wal/src/segment/list.rs

This PR adds a libsql-specific footer to libsql database file. This header is ignored by sqlite, but contains useful data for sqlite, such as the checkpointed replication index.

libsql footer

---

libsql-server/src/connection/libsql.rs
libsql-server/src/metrics.rs

This PR implements cancelling a query when the underlying request is dropped. This is done by adding a progress handler to the connection that checks every 100 instruction if the request has been dropped.

cancel query when request is dropped

---

libsql/src/replication/remote_client.rs

Users are seeing a warning message come up when a fresh database client tries to sync. Subsequent calls to sync don't trigger this warning log and in fact there is nothing to be worried about if this log fires because its normal to see this on the first call to sync.
Example logs showing this firing:
```
Running `target/debug/examples/remote_sync`
2024-08-07T21:39:26.287453Z  INFO libsql::replication::remote_client: Attempting to perform handshake with primary.
[libsql/src/replication/remote_client.rs:92:27] &self.session_token = None
[libsql/src/replication/remote_client.rs:92:56] &Some(hello.session_token.clone()) = Some(
b"e5c97d87-5ac7-089c-013f-31079f959e84",
)
2024-08-07T21:39:26.786669Z  WARN libsql::replication::remote_client: Frames prefetching failed because of new session token …
```

libsql: downgrade failed prefetch log to debug

---

.github/workflows/publish-server.yml

It seems like we are publishing two images (with and without debug symbols) under the same `libsql-server` image name.
This PR put `debug` docker images under `libsql-server-debug` name

publish sqld debug builds to the separate image name

---

.github/workflows/publish-server.yml

Follow up for #1648 PR where we stopped to produce debug build under `libsql-server` name but forgot to remove digests which used at the merge step

remove digests artifacts from debug build step

---

libsql/src/de.rs
libsql/src/hrana/mod.rs
libsql/src/local/impls.rs
libsql/src/local/rows.rs
libsql/src/local/statement.rs
libsql/src/replication/connection.rs
libsql/src/rows.rs

A few notes: I went the path of least resistance also assuming it would
break fewer folks, i.e. make Row more like Rows and thus usize -> i32.
Arguably, an unsigned type might be more appropriate both for length and
indexes. I understand that the i32 stems from the sqlite bindings, which
returns/accepts c_ints. Yet, Statement and Row made the jump to an
unsigned, probably drawing the same conclusion, whereas Rows preserved
its proximity to the c-bindings. This is probably an artifact?
Also going on a limb, mapping c_int -> i32 is already a non-portable
choice, with precision for c_int being platform dependent.

Breaking change: Make Rows and Row API more consistent.

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-sqlite3/ext/fts5/fts5_tokenize.c
libsql/tests/integration_tests.rs

`fts5` can crash if malformed tokenizer arguments are provided like this (see https://sqlite.org/forum/forumpost/171bcc2bcd for more details):
```
CREATE VIRTUAL TABLE t USING fts5(s, tokenize='trigram case_sensitive ');
```
This PR fixes this issue and make `SQLite` return regular error in such cases:
```
$> CREATE VIRTUAL TABLE t USING fts5(s, tokenize='trigram case_sensitive ');
Runtime error: error in tokenizer constructor
```

Fix fts5 crash

---

libsql/Cargo.toml

```sql
SELECT 0.00000001753244305291446;
```
```bash
Row: Real(1.7532443052914463e-8)
Row: Real(1.753244305291446e-8)
```
> [!NOTE]
This may incur a 2x performance cost.
https://github.com/serde-rs/json/blob/54381d6fee21cb05439937a0f5f286177c21d3f6/Cargo.toml#L68

Fix JSON Number(f64) precision

---

libsql-sqlite3/src/vectordiskann.c
libsql-sqlite3/test/libsql_vector_index.test

As vector node blocks usually are pretty huge (larger thane page size) - it leads to the situation where main shadow table B-Tree started to be a bit degenerate: all leafs will have only one cell. 
This is OK for read workloads - but for random row selection queries this lead to huge overhead as all leaf pages will be read just for the sake of single `rowid`!
```sql
-- for 5k rows B-Tree has depth of 3 and a lot of leaf pages 
-- (>1.5k - just sum up all degrees form second level internal pages)
-- each leaf page has 2-3 cells only most of the space occupied with huge blobs of data
$> SELECT path, ncell FROM dbstat WHERE pagetype = 'internal' AND name = 'x_idx_shadow';
/|3
/000/|452
/001/|446
/002/|382
/003/|383
```
This PR fixes this behaviour by adding lightweight index over rowid key …

vector search: speed up random row selection query

---

libsql-sqlite3/Makefile.in
libsql-sqlite3/src/sqliteInt.h
libsql-sqlite3/src/util.c
libsql-sqlite3/src/vector.c
libsql-sqlite3/src/vector1bit.c
libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/vectorIndexInt.h
libsql-sqlite3/src/vectorInt.h
libsql-sqlite3/src/vectordiskann.c
libsql-sqlite3/src/vectorfloat32.c
libsql-sqlite3/src/vectorfloat64.c
libsql-sqlite3/test/libsql_vector_index.test
libsql-sqlite3/tool/mksqlite3c.tcl

This PR introduces support for compressed edges representation in DiskANN implementation. For now, only `1bit` quantization is supported with the corresponding index parameter: `libsql_vector_idx(e, 'compress_neighbors=1bit')`.
In order to support compressed representation `DiskANN` search procedure were changed and now it supports 2 list of nodes:
1. `aCandidates` - list of **unvisited** candidates ordered by distance calculated with edge vector type (it will be compressed if index uses compression of edges)
2. `aTopCandidates` - list of top **visited** candidates ordered by the exact distance calculated with node vector type
This was done in order to always compare distances produced by the same vector representation: `aCandidates` ordered by distance between vector of "edge type" …

vector search: neighbors compression (1bit quantization)

---

libsql-sqlite3/src/build.c
libsql-sqlite3/src/parse.y
libsql-sqlite3/src/sqliteInt.h
libsql-sqlite3/test/libsql_vector_index.test

Recently we introduced new `idxType = 4` in the native SQLite code which corresponds to the vector index. 
Internally, SQLite use this field in several places and we tried to make SQLite believe that `idxType = 4` is equivalent to `idxType = 0` (which is APPDEF user defined-index). We missed one spot which results in the out-of-bound read and `SEGFAULT` in some cases (for some reason, `SEGFAULT` reproduced stably on Mac but code works fine on Linux with this bug :thinking: ).
This PR fixes `SEGFAULT` for `PRAGMA index_list='...'`  statements and also change our approach: instead of introducing new `idxType` we add new field `idxIsVector` which we will use to distinguish ordinary indices from the vector one but sqlite code will see our vector indices as `APPDEF` indices. This is more …

vector search: fix idx type bug

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs
bindings/c/src/types.rs

This adds a new replicated struct that is output during sync for the C bindings.

c: add replicated data for sync

---

libsql-sqlite3/src/vectordiskann.c

Windows builds are failing with the error (see https://github.com/tursodatabase/libsql-js/actions/runs/10353914696/job/28657926332?pr=134):
```
error C2036: 'void *': unknown size ...
```
This PR replaces several instances in the vector index implementation where operations involving `void*` pointers were performed, using `u8*` pointers instead.

windows compiler complains about operations with void* pointers

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/local/database.rs
libsql/src/replication/connection.rs
libsql/src/replication/mod.rs

`Database::max_write_replication_index` can be used by the client to keep track of the lowest replication index that guarantees seeing all the writes done by this client. `Database::sync_until` can be then used to sync the embedded replica at least to the replication index given by the client.
That way a client can:
1. Do a bunch of operations on one embedded replica
2. Fetch the max_write_replication index I
3. Run sync_until with a given replication index I on a different embedded replica and be sure that they see all the operations they've done on the first embedded replica.

libsql: Add max_write_replication_index and sync_until in Database

---

libsql-server/src/connection/libsql.rs
libsql-server/src/connection/program.rs
libsql-server/src/database/schema.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/store.rs
libsql-server/src/schema/db.rs

Current `sqld` code abuses tokio runtime which can lead to complete deadlock of the server.
One issue which got triggered pretty frequently relying on the following facts about `sqld` internals:
1. Many **async** request handlers in `sqld` checks that metadata has namespace in it with sync lock `metadata.inner.configs` (see `MetaStore::exists` method)
2. Metastore remove operation take `metadata.inner.configs` lock first and then try to take `inner.conn` lock
3. Background checkpoint operation which run on blocking thread take `inner.conn` lock for the time of the checkpoint process
So, if (2) took `metadata.inner.configs` lock while (3) is in process, then all request **tasks** which hits (1) will be **blocked** on the **parking_lot** mutex until (3) released the lock and (2) finished. …

replace parking_lot with tokio::sync::Mutex in some places

---

.github/workflows/nemesis.yml
.github/workflows/rust.yml
libsql-server/Cargo.toml
libsql-server/src/http/admin/mod.rs
libsql-server/src/metrics.rs

Expose basic tokio runtime metrics into the Prometheus:
```
tokio_runtime_blocking_queue_depth 0
tokio_runtime_injection_queue_depth 3
tokio_runtime_io_driver_fd_deregistered_count 5149
tokio_runtime_io_driver_fd_registered_count 5364
tokio_runtime_io_driver_ready_count 36342
tokio_runtime_num_blocking_threads 41
tokio_runtime_num_idle_blocking_threads 41
tokio_runtime_num_workers 8
tokio_runtime_remote_schedule_count 53401
```

expose basic tokio runtime metrics

---

libsql-server/Cargo.toml

`[build]` section must be in the `config.toml` (not in the `Cargo.toml`!) - but we already have it in the workspace config
Now build produces warnings:
```
$> cargo build
warning: /home/sivukhin/turso/libsql/libsql-server/Cargo.toml: unused manifest key: build
...
```

remove unused section from cargo.toml

---

.github/workflows/nemesis.yml

Force nemesis tests to use toolchain specified in the repository
Now action is working: https://github.com/tursodatabase/libsql/actions/runs/10467236343

update nemesis github action

---

Cargo.lock
libsql-server/Cargo.toml

Previous (0.24.19) release partially failed (artifacts were not published) - so let's not override it and just create new one

bump sqld version to 0.24.20 to create new release

---

libsql-sqlite3/src/build.c
libsql-sqlite3/src/select.c
libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/where.c
libsql-sqlite3/test/libsql_vector_index.test

PR https://github.com/tursodatabase/libsql/pull/1594 tried to solve issue with sqlite planner using vector index for some optimizations (for example in `SELECT COUNT(*) FROM t` queries).
Turned out hacks to avoid usage of vector indices in planner were not enough. Actually, `bUnordered` field set by `sqlite3` during index analysis process and manipulating with it can be dangerous and error-prone (as sqlite3 can reset it at any moment).
So, this PR fixes this more robustly:
1. `opMask` is set to 0 for vector index in `whereLoopAddBtreeIndex` which must additionally prevent sqlite to use index in any operations (`>`, `>=`, `=`, `IN`) (actually, it shouldn't happen because index has expression - but still - this is another guard)
2. `whereIsCoveringIndex` return false for vector index
3. …

vector search: hide vector index for sqlite planner

---

libsql-sqlite3/src/insert.c
libsql-sqlite3/src/pragma.c
libsql-sqlite3/test/libsql_vector_index.test

Before vector search indices produced integrity check errors because for SQLite core they looks like empty B-Tree indices.
This PR simply exclude vector indices from integrity_check pragma:
```
libsql> CREATE TABLE t (e FLOAT32(2));
libsql> INSERT INTO t VALUES (vector('[1,2]')), (vector('[2,3]'));
libsql> CREATE INDEX t_idx ON t(libsql_vector_idx(e));
libsql> PRAGMA integrity_check;
ok
```
This is important as `integrity_check` plays key role in DB validation process and can ruin some components even in LibSQL (like bottomless)

vector search: fix integrity check

---

Cargo.lock
bottomless/Cargo.toml
bottomless/src/backup.rs
bottomless/src/replicator.rs

Add few metrics to monitor bottomless
- `bottomless_s3_processed_frame_ranges` - amount of frame ranges processed by S3 upload process
- `bottomless_local_ready_frame_ranges` - amount of frame ranges ready to upload to S3
- `bottomless_s3_queue_size` - size of the local queue for transferring frames ranges to S3
- `bottomless_local_last_frame_no` - last processed frame number by local process
- `bottomless_s3_processing_frame_no` - last frame number which S3 upload process started to handle
- `bottomless_local_flush_time` - local frames flush time `histogram`
- `bottomless_snapshot_upload_time` - snapshot upload time `histogram`
- `bottomless_restore_upload_files_time` - restore upload files time `histogram`
- `bottomless_s3_write_time` - s3 write time `histogram`
Example of new metrics …

add some metrics in bottomless

---

bottomless/src/replicator.rs

During recovery from WAL `bottomless` has bug in case when S3 has more than 1 page of frames. 
The code is written in such a way that it tracks last injected frame number and abort recovery process of frame range from S3 doesn't match current next expected frame. This procedure is OK but the code reset `last_injected_frame_no` to zero for every S3 page which will lead to mismatch between expected and real frame number for every second page (if it will be) from S3.
This PR fixes this issue and just preserve frame number across S3 pages.

fix bug for case when S3 has more than 1 page of data

---

bottomless/src/backup.rs
bottomless/src/replicator.rs

Current implementation of `bottomless` skip frames which were failed during upload to S3. This create significant issue with restore process from such backup as `bottomless` can restore DB only from consecutive frames and first gap in frames will just stop restore process.
So, in case of slight fluctuation in S3 (like sqld network issue or just some degradation of S3) the backup will be "frozen" in time and all changes in the DB made after that fluctuation will not be restore from current generation (but next generation will have full snapshot and issue will disappear after generate bump will happen).
This PR addresses this nuance of `bottomless` implementation: now instead of bounded queue with frames for upload and fail-fast logic in case of S3 upload failure it has unbounded channel …

bottomless: do not skip frames even if there is a temporary issue with S3

---

libsql-server/src/lib.rs
libsql-server/src/main.rs

third time's the charm?
I forgot to not enforce HTTP scheme on the base HTTP connector

fix libsql-wal https connector

---

Cargo.lock
Dockerfile
bottomless-cli/Cargo.toml
bottomless-cli/src/main.rs
bottomless/src/replicator.rs
libsql-server/src/namespace/meta_store.rs

This PR implements two simple commands for `bottomless-cli`:
1. `bottomless-cli -n "ns-xxx:yyy" copy --to-dir local-directory -g generation` - copy specified (or latest if omitted) generation S3 content to the local directory
2. `bottomless-cli -n "ns-xxx:yyy" -d temp create --source-db-path dbs/xxx/data` - create new generation (with fresh timestamp) in the S3 from database file and upload single snapshot to the S3 with all necessary metadata for bottomless (`.changecounter`)
Create command opens DB at the path provided by `--source-db-path` in read-only mode and execute `VACUUM INTO ?` query to initialize fresh DB at the path provided by `-d`. After that DB without any changes in WAL will be sent as a single snapshot to the S3.
Also, CLI arguments structure a bit reworked in order to …

implement create and copy bottomless-cli commands

---

libsql-server/src/connection/mod.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/configurator/helpers.rs

Do not track internal connection, since it could block user queries if there are many loaded namespaces
Todo: add jitter to periodic jobs so that they don't execute all at the same time.

do not track internal connections

---

Cargo.lock
bindings/c/Cargo.toml
bindings/c/include/libsql.h
bindings/c/src/lib.rs

LibSQL is used from multiple SDK. In order to simplify debugging of issues with these SDKs we can expose `libsql_enable_tracing` method which will print rust logs to the stdout (if `RUST_LOG` env var set properly)

add libsql_enable_tracing to the libsql

---

libsql-server/src/database/schema.rs
libsql-server/src/query_analysis.rs
libsql-server/src/schema/db.rs
libsql-server/src/schema/mod.rs
libsql-server/src/schema/scheduler.rs
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__pending_job-3.snap
libsql-server/src/schema/snapshots/libsql_server__schema__db__test__pending_job.snap
libsql-server/src/schema/status.rs
libsql-server/tests/namespaces/shared_schema.rs

This PR works around disabling foreign_keys being a noop in schema migrations. During the validation of the migration script we allows a prologue and an epilogue of pragmas. If such a prologue is present, we assume that foreign_keys must be disabled for the migration. This is a bit hacky since we don't really validate what pragma is actually being used, but disabling foreign_keys is such a common pattern that assuming it should be ok

disable foreign keys in schema migration

---

libsql-server/src/connection/connection_core.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/configurator/replica.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/store.rs
libsql-server/src/replication/replicator_client.rs
libsql-server/src/rpc/streaming_exec.rs
libsql-server/src/schema/db.rs
libsql-server/src/schema/scheduler.rs
libsql-server/tests/cluster/mod.rs
libsql-server/tests/cluster/schema_dbs.rs

The was a regression where the replica would check for migrations completion on load. This is fixed by skipping the check for replicas.
also add regression tests

Fix schema db bug with replicas

---

libsql-server/src/lib.rs
libsql-server/src/main.rs

introduce a main runtime deadlock monitor.
We've add issues in the past where the main runtime would deadlock. It's hard to prove that this won't ever happen again, so instead, we introduce a deadlock monitor: every second, an OS thread pings the main runtime, expecting a response within a reasonable deadline. If the runtime fails to meet the deadline, the process is aborted.

introduce deadlock monitor

---

libsql-server/src/config.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/tests/cluster/mod.rs
libsql-server/tests/cluster/replica_restart.rs
libsql-server/tests/cluster/replication.rs
libsql-server/tests/common/http.rs
libsql-server/tests/embedded_replica/mod.rs
libsql-server/tests/namespaces/mod.rs
libsql-server/tests/standalone/admin.rs
libsql-server/tests/standalone/mod.rs

Add support for basic auth for the admin API.
when the flag `LIBSQL_ADMIN_AUTH_KEY` is set, that value is used to authenticate requests to the admin API with the header `authorization: basic <key>`

add support for basic auth for admin api

---

Cargo.lock
libsql-wal/Cargo.toml
libsql-wal/src/bins/compactor/main.rs
libsql-wal/src/bins/shell/main.rs
libsql-wal/src/io/buf.rs
libsql-wal/src/replication/storage.rs
libsql-wal/src/segment/compacted.rs
libsql-wal/src/storage/async_storage.rs
libsql-wal/src/storage/backend/mod.rs
libsql-wal/src/storage/backend/s3.rs
libsql-wal/src/storage/compaction/mod.rs
libsql-wal/src/storage/compaction/strategy/identity.rs
libsql-wal/src/storage/compaction/strategy/log_strategy.rs
libsql-wal/src/storage/compaction/strategy/mod.rs
libsql-wal/src/storage/job.rs
libsql-wal/src/storage/mod.rs

This PR adds an MVP for the compactor process in the form of a shell. It's not feature-complete but can perform compaction according to basic strategies. We'll expand strategies and functionality later on
It is exposed as a new cli bin:
```
cargo r --bin compactor -- --help
Compiling libsql-wal v0.1.0 (/Users/mpostma/Documents/code/turso/libsql/libsql-wal/libsql-wal)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.01s
Running `target/debug/compactor --help`
Usage: compactor [OPTIONS] <COMMAND>
Commands:
monitor  Register namespaces to monitor
analyze  Analyze segments for a namespaces
compact  Compact segments into bigger segments
sync     Sync namespace metadata from remote storage
restore  Restore namespace
help     Print this message or the help of the given …
```

Segment compactor

---

libsql-wal/src/segment/current.rs
libsql-wal/src/shared_wal.rs
libsql-wal/src/transaction.rs

This PR fixes a bug in libsql-wal transaction isolation that was thankfully caught by some assertions left behind.
Basically, we used to check that the frames we read from the main segment would not violate the max_frame_no property, we would use the log offset combined with the start offset in the index. This all worked fine with the regular mode of operation where frames are inserted in order, with increment of 1 in the wal. Things started to break with the replica, because frames can be inserted out-of-order, and with random increments.
To fix that, we remove the start_frame_no from the index, and instead we record the max_offset in the transaction: that offset correspond the max frame_no in the current segment, iow, any frame before that offset is guaranteed to be less that …

fix replica snapshot isolation bug

---

libsql-wal/src/replication/storage.rs
libsql-wal/src/storage/async_storage.rs
libsql-wal/src/storage/backend/mod.rs
libsql-wal/src/storage/backend/s3.rs
libsql-wal/src/storage/compaction/mod.rs
libsql-wal/src/storage/error.rs
libsql-wal/src/storage/job.rs
libsql-wal/src/storage/mod.rs

Fix the SegmentKey formatting such that the biggest most recent segment is always returned first
The `SegmentKey` starts with the inverted end-frame-no such that all segments are ordered by reverse biggest frame_no, then comes the start_frame no, in natural order, so that, for the same end_frame_no, the one with the smallest frame_no is ordered first. Lastly is the segment timestamp, which is roughly the commit time of the last txn in the segment. On merge, this is inheritted from the most recent segment, and the timestamp is therefore never a tie-breaker.
This change of key scheme means that we can't easily find segment by frame_no like we did before, but that's actually ok: we never need to fetch a random frame_no, rather, we iterate backward from segment boundary to segment boundary. …

libsql-wal: fix SegmentKey

---

libsql-server/src/bottomless_migrate.rs
libsql-server/src/error.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/configurator/fork.rs
libsql-server/src/namespace/configurator/helpers.rs
libsql-server/src/namespace/configurator/libsql_fork.rs
libsql-server/src/namespace/configurator/libsql_primary.rs
libsql-server/src/namespace/configurator/libsql_schema.rs
libsql-server/src/namespace/configurator/mod.rs
libsql-server/src/rpc/replication/libsql_replicator.rs
libsql-wal/benches/benchmarks.rs
libsql-wal/src/lib.rs
libsql-wal/src/registry.rs
libsql-wal/src/replication/injector.rs
libsql-wal/src/replication/replicator.rs
libsql-wal/src/replication/storage.rs
libsql-wal/src/segment/current.rs
libsql-wal/src/segment/mod.rs
libsql-wal/src/segment/sealed.rs
libsql-wal/src/shared_wal.rs
libsql-wal/src/storage/job.rs
libsql-wal/tests/flaky_fs.rs
libsql-wal/tests/oracle.rs

Implement forking for libsql-wal in a similar fashion to what was done before: create a new namespace, and replicate to is from the source namespace.
This PR also remove the use of the `wals` directory, and instead, it stores the wals alonside the dbs themselves.

Libsql-wal: implement forking

---

libsql-server/src/rpc/proxy.rs
libsql-server/src/rpc/replication/replication_log.rs
libsql-server/tests/cluster/mod.rs
libsql-server/tests/cluster/schema_dbs.rs
libsql-server/tests/embedded_replica/mod.rs

This PR contains two fixes one for preventing embedded replica's from being able to sync a schema db and another that cleans up the conn.is_primary panics/errors that we had before.

sqld: schema db and replica fixes

---

bindings/c/src/lib.rs

Without this call to stmt.reset(), the prepared statement is not correctly reset and the same values are read back despite having new bindings.
Fixes #1481

Add call to statement reset to libsql_reset_stmt C binding

---

Cargo.lock
libsql-replication/Cargo.toml
libsql/Cargo.toml
libsql/src/database.rs
libsql/src/lib.rs

This adds a new `tls` feature that is enabled by default, if this feature is disabled building a libsql connection will panic with a message asking you to configure a http connector. This allows users to bring their own http connector and more importantly their own TLS lib with their own versions without needing to compile rustls which we use by default.
This resolves solana-sdk >2 build issues with uses an older version of `curve25519-dalek` that pings `zeroize` to `<1.4`. New versions of `rustls` require `1.7` of `zeroize` thus causing issues when building `rustls` for libsql with the `tls` feature.

libsql: add `tls` feature

---

libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/test/libsql_vector_index.test

It can be hard in some clients (JS for example, [see](https://github.com/tursodatabase/libsql-js/blob/147715caed174f7cc411221fbebed0f34a9ec7d6/src/statement.rs#L31)) to distinguish between INTEGERs and FLOATs - so we always bind FLOATs instead (
This create unnecessary error: `vector index(search): third parameter (k) must be a non-negative integer`
This PR fixes vector search and make it tolerant to the FLOAT parameter if there is no precision loss (so, the provided FLOAT value is actually INTEGER). In case of precision loss (for example, user provided value `2.5` for the `K` parameter) the error message will look like this: `vector index(search): third parameter (k) must be an integer, but float value were provided`

accept K parameter as float if there is no loss in the precision after rounding to the integer

---

libsql-server/src/main.rs
libsql-wal/src/storage/backend/mod.rs
libsql-wal/src/storage/backend/s3.rs

This PR implements multipart uploads instead of regular uploads for the libsql-wal segment. That is because AWS S3 refuses payloads that are not known in size.
We instead use a multipart upload, where we stream in chunks of 50MB to temporary files that we then upload as parts of the multipart upload.

libsql wal multipart upload

---

libsql-server/src/connection/connection_core.rs
libsql-server/src/connection/legacy.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/lib.rs
libsql-server/src/namespace/configurator/helpers.rs
libsql-server/src/namespace/configurator/libsql_primary.rs
libsql-server/src/namespace/configurator/libsql_replica.rs
libsql-server/src/namespace/configurator/replica.rs
libsql-server/src/replication/replicator_client.rs
libsql-server/src/rpc/replication/libsql_replicator.rs

This PR fixes issues related to the integration of libsql-wal replication:
- auth issue: we changed auth to disambiguate between internal and external services, that didn't reflect on libsql-wal replication
- replication wasn't setup to retrieve the replica current frame_no and was replicating for scratch on restart
- when replica restarts, start replicating from the last durable frame_no to account for primary potential data loss

libsql-wal replication fixed

---

libsql-server/src/namespace/configurator/replica.rs

there is a bug where a primary will report that a valid
namespace doesn't exist when it does and causes the replicate to
destroy the namespace locally. For now the temp solution is to
ignore this error (still log it) and don't destroy the local
namespace data on the replica. This trades off storage space for
returing 500s.

sqld: temp fix replica namespace doesnt exist

---

libsql-wal/src/io/buf.rs
libsql-wal/src/io/file.rs
libsql-wal/src/replication/replicator.rs
libsql-wal/src/replication/storage.rs
libsql-wal/src/segment/current.rs
libsql-wal/src/segment/list.rs
libsql-wal/src/shared_wal.rs

The goal of this PR is to perform replication straight from the main DB file when the segments for the requested frame_no have already been sent to storage. Currently, we would fetch segments from storage to find missing pages, but this is unnecessary. Instead, we can use the segment indexes to scan the missing pages in the ranges covered by the index and read those pages from the database file.
For this to work, the replicator needs to hold a read transaction while it's performing a replication step. This prevents checkpointing of pages that the replicator has not seen to the main DB file and ensures that transaction boundaries are well preserved.
This first iteration reads from the main db-file when the requested frame_number is 1 (iow, replicating from scratch)

libsql wal replicate from db file

---

bottomless/src/replicator.rs
libsql-server/src/namespace/meta_store.rs

This commit adds a env var that can be set via
`LIBSQL_BOTTOMLESS_SKIP_SHUTDOWN_UPLOAD` that will force bottomless to ignore uploading a snapshot during a graceful shutdown.

bottomless: add upload on shutdown skip option

---

libsql-sqlite3/src/test8.c

The module struct initializer for xPrepareSql is wrong since commit d178de8f07 ("bugfix: reset modifications of `sqlite3_vtab` (#1027)") because it assings the xPrepareSql as the xIntegrity hook:
```
/home/runner/work/libsql/libsql/libsql-sqlite3/src/test8.c:1364:3: warning: initialization of 'int (*)(sqlite3_vtab *, const char *, const char *, int,  char **)' from incompatible pointer type 'int (*)(sqlite3_vtab_cursor *, const char *)' [-Wincompatible-pointer-types]
1364 |   echoPreparedSql,
|   ^~~~~~~~~~~~~~~
/home/runner/work/libsql/libsql/libsql-sqlite3/src/test8.c:1364:3: note: (near initialization for 'echoModuleV2.xIntegrity')
```

libsql-sqlite3: Fix xPrepareSql init in test8.c

---

libsql/src/local/database.rs
libsql/src/replication/mod.rs
libsql/src/replication/remote_client.rs

Track detailed usage of synced bytes that will hopefully allow to identify why we're accounting so many bytes for sync.
Expose those detailed stats through Database::get_sync_usage_stats.

Add Database::get_sync_usage_stats

---

libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/src/vectorIndexInt.h
libsql-sqlite3/src/vectorvtab.c
libsql-sqlite3/test/libsql_vector_index.test

Eponymous virtual tables exists only in main schema and any prefix before them is no-op for SQLite (like `attached.vector_top_k(...)`; see https://www.sqlite.org/vtab.html#epovtab)
So, in order to  use vector search from other schema name - we need to develop internal convention that index name string argument can have schema name prefix (in similar way as usual SQL query): `SELECT * FROM vector_top_k('attached.t_idx', vector('[1,2,3]'), 4)`.
This PR support this feature which will allow users to query vector search indices from attached DBs.

vector-search: fix attach

---

Cargo.lock
libsql-server/Cargo.toml

- new release will include fix for vector search in attached DBs (see https://github.com/tursodatabase/libsql/pull/1799)

bump sqld version

---

libsql-server/src/http/admin/mod.rs

This PR adds more visibility to the server about config changes operations by logging them on successful update in metastore:
```
2024-11-06T20:42:01.116818Z  INFO libsql_server::http::admin: updated db config namespace="testing" block_writes_before=false block_writes_after=true block_reads_before=false block_reads_after=false allow_attach_before=false allow_attach_after=false max_db_pages_before=244140625000000 max_db_pages_after=244140625000000 durability_mode_before="relaxed" durability_mode_after="relaxed"
```

add info log about all config changes

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-ffi/bundled/bindings/session_bindgen.rs
libsql-ffi/bundled/src/sqlite3.h
libsql-replication/src/injector/sqlite_injector/injector_wal.rs
libsql-sqlite3/doc/libsql_extensions.md
libsql-sqlite3/src/main.c
libsql-sqlite3/src/pager.c
libsql-sqlite3/src/pager.h
libsql-sqlite3/src/sqlite.h.in
libsql-sqlite3/src/sqliteInt.h
libsql-sqlite3/src/test_walapi.c
libsql-sqlite3/src/wal.c
libsql-sqlite3/src/wal.h
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-storage/src/lib.rs
libsql-sys/src/wal/either.rs
libsql-sys/src/wal/ffi.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs
libsql-wal/src/wal.rs

The libSQL has the following WAL API functions, which are useful for
syncing the WAL between databases:
* `libsql_wal_disable_checkpoint` -- Disable checkpointing, including on database close.
* `libsql_wal_frame_count` -- Get the number of frames in the WAL.
* `libsql_wal_get_frame` -- Get a frame from the WAL.
* `libsql_wal_insert_begin` -- Begin WAL insertion.
* `libsql_wal_insert_frame` -- Insert a frame into the WAL.
* `libsql_wal_insert_end` -- End WAL insertion.
The purpose of this API is to allow syncing the frames of one database WAL onto another. Example usage looks as follows (omitting error handling):
```c
static void sync_db(sqlite3 *db_primary, sqlite3 *db_backup){
unsigned int max_frame;
libsql_wal_frame_count(db_primary, &max_frame);
libsql_wal_begin_commit(db_backup); …
```

libSQL WAL API

---

Cargo.lock
libsql/Cargo.toml
libsql/examples/offline_writes.rs
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/lib.rs
libsql/src/local/connection.rs
libsql/src/local/database.rs
libsql/src/macros.rs
libsql/src/replication/mod.rs
libsql/src/sync.rs

This pull request adds a new type of database, synced database, which
allows local writes that can sync to a remote server.
The protocol on server side is simple:
**POST** `/sync/<generation>/<start_frame>/<end_frame>`
where request body is the WAL frames.

Initial offline write support

---

libsql/Cargo.toml
libsql/src/local/database.rs

The server returns its maximum frame number so let's use that as a hint to avoid pushing frames it already knows about. IOW, let's start by sending the first frame in the WAL, but immediately skip to a the server's max frame number. Later we should also cache the server max frame number on client side to make the first push start from the right frame.

libsql: Improve WAL frame push logic

---

docs/DOCKER.md

- typo in `latest`
- missing line continuation character `\`

fix typo in docker readme

---

libsql/src/local/database.rs

There seems to be a bug with `cargo fmt` and functions that have a `#[cfg(feature = "..")]`, what happens is `cargo fmt` does not pick this up as a formatting change and thus in our CI `cargo fmt --check` isn't picking up that these fn's need to be formatted. On the other hand when these files are passed through rust-analyzer with rustfmt on save, it ends up formatting the files. To solve this in a temporary sense right now I am just running files manually through my ide format to get them to format correctly. This does not cause `cargo fmt --check` to fail but allows anyone using rust-analyzer + rustfmt to not introduce extra changes.

chore: run ide fmt on local/database.rs

---

Cargo.lock
libsql/Cargo.toml
libsql/src/local/database.rs

This commit switches our usage of reqwest to hyper. In the future, this will allow us to pass in configuration for the connector to support both custom TLS implementations (aka using the system tls impl over rustls) and connecting to the sqld network simulation for future testing. This also removes the extra dependency on reqwest which is not needed since we already pull in the dependencies needed to implement the new protocol for local offline writes.

libsql: Switch to hyper for local offline

---

libsql/src/local/connection.rs
libsql/src/local/database.rs

This just moves unsafe wal code from safe database code to their own self contained safe fn. This clears up the safe and unsafe boundary instead of mixing and matching like before. This also creates a clear point of audit of our unsafe usage.

libsql: add wal frame_count and get_frame safe fn

---

libsql/src/local/database.rs
libsql/src/sync.rs

This PR has multiple commits each broken up into their own refactor piece. Broken down is the list of refactors and why:
- Move sync ctx behind a mutex, this in general makes sense since we only want one push to be active at a time but also will enable the future durable_frame_no caching by allow us to mutate the struct on push. It is an async lock since we want to sync access to push over long async periods.
- move push_with_retry into sync.rs
- move push_one_frame into sync.rs these both make sense since the data they depend on is inside the sync_ctx struct so this allows us to make those fields private.
- Following up on those two, the next commit makes those fields private to improve code encapsulation.
- Small refactor now to use the auth_token field from the struct.
This PR just …

libsql: refactor push and sync code

---

Cargo.lock
libsql/Cargo.toml
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/local/database.rs
libsql/src/sync.rs

This PR adds 3 new commits related to integrating hyper into offline writes. This also includes tls support. 
Tested this against a platform server:
```
❯ cargo run --example offline_writes
Compiling libsql v0.6.0 (/home/lucio/code/libsql/libsql)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 12.21s
Running `target/debug/examples/offline_writes`
Please write your entry to the guestbook:
hello
You entered: hello
Guest book entries:
cargo run --example offline_writeshello
hello
hello
hello
Syncing database to remote...
Done!
```

libsql: use hyper for offline writes

---

Cargo.lock
bindings/c/Cargo.toml
bindings/c/src/lib.rs
libsql/src/database/builder.rs

This is to make it possible to test offline writes in opsqlite.
To make the integration easy we don't create a new factory function but modify `libsql_open_sync_with_config` to create offline writes database if primary url contains `offline` query parameter.

Make it possible to use offline writes in C bindings

---

libsql-sqlite3/src/main.c
libsql-sqlite3/src/test_walapi.c

Fix error reporting and clean up test case a bit.

WAL API fixes

---

libsql-sqlite3/src/pager.c
libsql-sqlite3/src/test_walapi.c

If a database is empty, the pagerUseWal() returns false. In that case, make libsql_wal_frame_count() return zero instead of a logic error.

libsql-sqlite3: Fix libsql_wal_frame_count() for empty databases

---

libsql-server/src/error.rs
libsql-server/src/namespace/configurator/helpers.rs
libsql-server/tests/namespaces/dumps.rs
libsql-server/tests/namespaces/snapshots/tests__namespaces__dumps__load_dump_with_attach_rejected.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__dumps__load_dump_with_invalid_sql.snap

This adds support for rejecting `ATTACH` statements from dumps. `ATTACH` statements should be considered dangerous in a multi-tenant setting. With this commit any `ATTACH` statement inside a dump will be rejected with a 400 status code and a message. In addition, any other sql errors returned by sqlite will be returned as a 400. All other dump errors through this code path (conn.with_raw) will return a 500 like before.

sqld: reject `ATTACH` statements

---

libsql-sqlite3/src/test_walapi.c

Make the test bit harder on the WAL API by generating more than one frame per transaction.

libsql-sqlite3: Improve WAL API test

---

libsql-sqlite3/src/pager.c
libsql-sqlite3/src/test_walapi.c

We have a problem with WAL API where in some scenarios, we seem to lose WAL frames that were already applied. However, inspecting the external WAL frame, the sync mechanics work fine and the problem is in SQLite's in-memory state.

libsql-sqlite3: Fix problem with disappearing WAL frames

---

libsql/src/local/database.rs
libsql/src/sync.rs
libsql/src/sync/test.rs

This commit adds a new error returned from `SyncContext` that indicates that the server returned a lower frame_no than what the local cached max server frame no expected (durable_frame_num). When the high level `Database::push` fn gets this error it will restart the sync which will pick up the new server side frame hint that we got and start sync from that frame_no.
Test output:
```
2024-11-27T15:45:27.284544Z DEBUG libsql::sync: no metadata info file found
2024-11-27T15:45:27.284603Z DEBUG push_one_frame{generation=1 frame_no=0}: libsql::sync: pushing frame
2024-11-27T15:45:27.285044Z DEBUG push_one_frame{generation=1 frame_no=0}: libsql::sync: frame successfully pushed durable_frame_num=0
2024-11-27T15:45:27.315258Z DEBUG libsql::sync: read sync metadata for …
```

libsql: restart sync on lower frame_no from remote

---

libsql-server/tests/cluster/snapshots/tests__cluster__create_namespace.snap
libsql-server/tests/cluster/snapshots/tests__cluster__replication__replica_lazy_creation.snap
libsql-server/tests/hrana/batch.rs
libsql-server/tests/hrana/snapshots/tests__hrana__batch__server_restart_query_execute_invalid_baton.snap
libsql-server/tests/hrana/snapshots/tests__hrana__batch__server_restart_timeout.snap
libsql-server/tests/hrana/snapshots/tests__hrana__batch__server_restart_txn_execute_execute_invalid_baton.snap
libsql-server/tests/hrana/snapshots/tests__hrana__batch__server_restart_txn_execute_query_invalid_baton.snap
libsql-server/tests/hrana/snapshots/tests__hrana__batch__server_restart_txn_query_execute_invalid_baton.snap
libsql-server/tests/hrana/snapshots/tests__hrana__batch__server_timeout.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__check_migration_perms.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__disable_ddl.snap
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth-2.snap
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth-3.snap
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth.snap
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_no_auth.snap
libsql/src/hrana/hyper.rs
libsql/src/rows.rs

This improves the `Hrana(Api("..."))` message to include the status code of the response rather than just the body as a string. This also adds a bunch of tests related to this api and updated snapshots for the new error message.

libsql: improve hrana api error message

---

libsql/src/local/database.rs

Returns an error when one of the pull_one_frame calls fail. It will continue to write the metadata and end the insert before returning the error to the user. This also removes the println for a call to tracing.

libsql: Clean up error handling in try_pull

---

libsql/src/sync.rs

The JavaScript SDK is unfortunately stuck with Rust 1.78:
https://github.com/tursodatabase/libsql-js/issues/104
We should fix that, but since that's hard, let's just once again paper over it by fixing build on older Rust toolchains.

libsql: Fix build on older Rust toolchains

---

libsql/src/local/connection.rs

This prevents a potential panic that can happen in our ffi code when it expects a NonZero value but the input type into the unsafe function is a u32, meaning the compiler will not enforce the value and will result in a panic. This changes it so that when the code is called via the sys crate safe code it will return a sqlite failure.
Closes #1868

libsql: error on invalid frame_no on wal read

---

libsql/src/local/database.rs
libsql/src/sync.rs

The WAL sync protocol only allows you to fetch frames for a range. While the protocol does not have mechanism to determine what is the latest frame on the server for pull, it does signal with HTTP status code 400 when you attempt to read a frame that does not exists.
Let's use this signal to fix WAL pull logic not to fail always. In the future, we might want to consider extending the protocol to allow clients to proble for latest frame. That, however, will make the protocol a bit more chatty, so I am trying to avoid that as long as I can.

libsql: Fix WAL pull logic on last frame

---

libsql-sqlite3/src/pager.c

This fixes a missing pager that `libsql_pager_codec` expects to not be null. All this does is add the pager when we call `sqlite3PagerWalInsert` to the wal frame we want to insert.
Fixes #1867

sqlite3: fix missing pager causing SQLITE_MISUSE

---

libsql-server/src/lib.rs

Currently there's no way to disable checkpoint but one can emulate it by enabling periodic checkpoint with really long interval between checkpoints.
Unfortunately, current implementation runs checkpoint first before waiting for the interval to pass.
This change makes the periodic checkpoint to first wait and only after that checkpoint.

periodic checkpoint: Don't checkpoint at startup

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-ffi/bundled/bindings/session_bindgen.rs
libsql-ffi/bundled/src/sqlite3.h
libsql-replication/src/injector/sqlite_injector/injector_wal.rs
libsql-sqlite3/doc/libsql_extensions.md
libsql-sqlite3/src/main.c
libsql-sqlite3/src/pager.c
libsql-sqlite3/src/sqlite.h.in
libsql-sqlite3/src/test_walapi.c
libsql-sqlite3/src/wal.c
libsql-sqlite3/src/wal.h
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-storage/src/lib.rs
libsql-sys/src/wal/either.rs
libsql-sys/src/wal/ffi.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs
libsql-wal/src/wal.rs

This adds libsql_wal_checkpoint_seq_count() API function for determining the checkpoint sequence counter of a database WAL.

Add libsql_wal_checkpoint_seq_count() API

---

Cargo.lock
libsql/Cargo.toml

Dependabot warns about unsound usage in older versions, so bump the version:
https://github.com/tursodatabase/libsql/security/dependabot/68

Bump pprof version

---

libsql-replication/src/replicator.rs

If we fail to contact the primary, we return an error message. Let's switch to warn log level to avoid scaring users.

libsql-replication: Switch retry message to warn log level

---

bottomless/src/replicator.rs
libsql-server/src/namespace/configurator/helpers.rs

This commit changes our primary connection initialization code in two ways to achieve the ability to disable checkpointing the wal.
1) We ignore the initial checkpoint that we call directly into sqlite3
before we restore from bottomless. There is a fixme above that
explains why we need this but to me right now its not totally clear
why without digging deeper into the internals of bottomless. We
should do this but for the moment this unblocks us and from the fixme
comment it does not sound unsafe rather doing extra work potentially.
2) When bottomless needs to get the local change counter is creates a
sqlite connection. When this connection drops it seems like it
checkpoints the wal. I took a brief look at the `sqlite3_close` code
and did not find anything obvious, I have been told in the …

sqld: disable checkpoint on primary conn create

---

libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/local/database.rs

This adds a `skip_saftey_assert` builder option that will allow uses to unsafely opt-out of the safety checks that libsql has built in. The inline doc comments for this function explain more.

libsql: add `skip_safety_assert` builder option

---

libsql/src/local/connection.rs
libsql/src/local/database.rs

Resolves #1919
This PR also includes a internal API change regarding, it is straight forward enough to be included in the same PR.

Prevent reporting HttpDispatch errors in `sync_offline`

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-ffi/bundled/bindings/session_bindgen.rs
libsql-ffi/bundled/src/sqlite3.h
libsql-replication/src/injector/sqlite_injector/injector_wal.rs
libsql-sqlite3/doc/libsql_extensions.md
libsql-sqlite3/src/main.c
libsql-sqlite3/src/pager.c
libsql-sqlite3/src/sqlite.h.in
libsql-sqlite3/src/test_walapi.c
libsql-sqlite3/src/wal.c
libsql-sqlite3/src/wal.h
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-storage/src/lib.rs
libsql-sys/src/wal/either.rs
libsql-sys/src/wal/ffi.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs
libsql-wal/src/wal.rs

The `libsql_wal_checkpoint_seq_count()` API is not very useful for WAL sync because SQLite resets the counter when database is closed.

Remove libsql_wal_checkpoint_seq_count() API

---

libsql/Cargo.toml
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/mod.rs
libsql/src/local/database.rs
libsql/src/local/impls.rs
libsql/src/params.rs
libsql/src/replication/connection.rs
libsql/src/replication/mod.rs
libsql/src/sync.rs
libsql/src/sync/connection.rs
libsql/src/sync/statement.rs
libsql/src/sync/transaction.rs

Resolves #1920 by adding the capability of delegating writes a remote connection.
Following embedded replica convention, `read_your_writes` is enabled by default (after all write operations, `sync_offline` will be called), this can be disabled by adding `.read_your_writes(false)` to the builder.
```rust
libsql::Builder::new_synced_database(
"local.db",
"http://test.localhost:8080".to_string(),
"".to_string(),
)
.remote_writes(true) // NEW!
.build()
.await?
```

Remote writes for offline databases

---

libsql/src/local/connection.rs
libsql/src/sync.rs
libsql/src/sync/test.rs

This pull request adds WAL sync checkpointing support.

WAL sync checkpointing support

---

libsql/src/sync.rs

libsql: Fix sync panic when remote database is empty

---

libsql/src/sync.rs

We already handle bad request earlier in pull_with_retry() so drop the useless check.

libsql: Remove duplicate check in pull_with_retry()

---

libsql/src/database/builder.rs
libsql/src/sync.rs
libsql/src/sync/test.rs

In my tests, this speeds up push 4-5 times.
Making push of 300 frames take 4-5s instead of 20s.

Push up to 128 frames in sync

---

libsql-sqlite3/src/wal.c

libsql exposes a WAL checkpoint callback that is called once for each frame and right when checkpointing is about to finish.
before this change, the result code returned by the checkpoint callback was ignored on the 'finish' invocation, which resulted in the checkpoint completing successfully despite the callback returning an error.
this commit propagates the callback's error code and thus prevents the wal_checkpoint() routine from returning SQLITE_OK in cases where the callback failed.

wal.c: do not ignore the result code of xCb in walCheckpoint

---

libsql-server/src/connection/connection_core.rs
libsql-server/src/lib.rs
libsql-sys/src/connection.rs

This PR setup properly setup busy timeout for `libsql-server` connections:
1. It uses 100ms busy timeout by default
2. It uses 5s busy timeout for connection which execute `wal_checkpoint(TRUNCATE)`

Fix busy timeouts

---

libsql-ffi/bundled/bindings/bindgen.rs
libsql-ffi/bundled/src/sqlite3.h
libsql-sqlite3/src/sqlite.h.in
libsql-sqlite3/src/vdbeInt.h
libsql-sqlite3/src/vdbeapi.c
libsql-sqlite3/src/vdbeaux.c

This adds an API for interrupting a specific statement instead of all pending operations like `sqlite3_interrupt()` does.

libsql-sqlite: Add libsql_stmt_interrupt() API

---

libsql/src/database/builder.rs

This fixes the error like:
```
Error opening db path test.db, primary url libsql://testd.turso.io: sync error: error trying to connect: unsupported scheme libsql
```
when using libsql:// in the url

Make client work with libsql:// schema again

---

libsql-sys/src/wal/ffi.rs

The instrument macro uses info level by default. Let's switch to trace level instead to avoid spamming logs like crazy.

libsql-sys: Fix checkpoint logging to use trace level

---

bindings/c/src/lib.rs

Let's propagate the error code from the future we block on to the caller of `libsql_query_stmt()`.

bindings/c: Fix libsql_query_stmt() error reporting

---

libsql/src/database/builder.rs

addendum to #1966, uses https://doc.rust-lang.org/std/string/struct.String.html#method.replacen

refactor(builder): remove mut usage

---

libsql/src/sync.rs
libsql/src/sync/test.rs

This adds WAL push conflict detection to the client side.

libsql: WAL push conflict detection

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs
bindings/c/src/types.rs

Make it possible to configure offline writes via the normal `libsql_config` struct too.

bindings/c: Add `offline` to config struct

---

libsql/src/database/builder.rs

If we have an invalid access token, let's continue with gRPC protocol, because it produces odd error messages.

libsql: Improve sync protocol probe error handling

---

libsql-sys/src/connection.rs

Currently the codepath used when rusqlite is disabled, is Unix-platform-dependent.
For instance, here is the error we compiling from Windows:
```
error[E0433]: failed to resolve: could not find `unix` in `os`
--> C:\Users\runneradmin\.cargo\git\checkouts\libsql-311658d335deb3b1\9b04f1d\libsql-sys\src\connection.rs:276:26
|
276 |             use std::os::unix::ffi::OsStrExt;
|                          ^^^^ could not find `unix` in `os`
|
note: found an item that was configured out
--> /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\os\mod.rs:27:9
note: the item is gated here
--> /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\os\mod.rs:19:1
note: found an item that was configured out
--> /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\os\mod.r …
```

fix(libsql-sys): support non-Unix when rusqlite feature is disabled

---

libsql/src/sync.rs
libsql/src/sync/test.rs

Currently, the sync code pulls all the generations and frames one by one. However, this is very inefficient, for databases with many generations it could take hours.
This patch adds a optimisation that it pulls the latest generation by calling `export` endpoint and boostraps the db file quickly.
My testing shows insane improvements. For a db with 30 generations, and about 100 frames in each gen, it has brought down the initial sync from 1hr to 1 minute.
Fixes #1991

Bootstrap database file instead of pulling every WAL frame

---

libsql/src/auth.rs
libsql/src/connection.rs
libsql/src/errors.rs
libsql/src/lib.rs
libsql/src/local/connection.rs
libsql/src/local/impls.rs
libsql/tests/integration_tests.rs

This adds support for `sqlite3_set_authorizer()`. The API follows rusqlite and the enumerations are lifted straight from rusqlite for compatibility.

libsql: Add authorizer support

---

libsql/src/local/database.rs
libsql/src/sync.rs

This patch is a follow up on https://github.com/tursodatabase/libsql/pull/2017 It changes the heuristics for bootstrapping the DB. 
One more change is, it also does bootstrap before any connection to the local SQLite is created 
Earlier, we bootstrapped whenever we noticed a change in the generation. However, this patch changes this behaviour and does bootstrap only if local files don't exist:
1. if no db file or the metadata file exists, then user is starting from scratch
and we will do the sync
2. if the db file exists, but the metadata file does not exist (or other way around),
then local db is in an incorrect state. we stop and return with an error
3. if the db file exists and the metadata file exists, then we don't need to do the
sync

Bootstrap database before opening connection

---

libsql/src/database.rs
libsql/src/sync.rs
libsql/src/sync/statement.rs

Only pull frames when doing write delegation

---

libsql/src/database.rs
libsql/src/local/database.rs
libsql/src/sync.rs

Fixes #2024 
Whenever `db.connect` is called, we will try to bootstrap the db if required

Attempt to bootstrap the db on `connect`

---

libsql/src/database/builder.rs

Right now, despite providing your own connector, the code unconditionally calls its own connect function.
This has the side-effect of making sync incompatible with platforms which do not have native certs ready.

plumb connector through when syncing

---

libsql-ffi/build.rs

libsql-ffi build on Windows has been intermittently broken for a while due _build.rs_ calling `cp` which is not present on Windows.
Timeline:
- 2024-08-10: Issue #1657 was opened.
- 2024-11-14: #1791 was merged. First fix using `#[cfg(windows)]`.
- 2024-11-15: #1791 reverted in 9499c3c for breaking libsql-js on macOS.
- 2024-12-04: 9499c3c was reverted since #1791 was fine and did not cause the macOS problem. Windows build works again.
- 2025-03-17: da54c1b breaks Windows build.
- 2025-03-21: 0.9.1 is released with broken Windows build.
- 2025-03-27: This commit fixes the bug introduced in da54c1b.
This commit fixes a bug introduced by da54c1b. `Command::status()?` was propogating the error so the fallback, `fs::copy`, was never reached. This is now fixed so libsql-ffi builds again on …

Fix libsql-ffi build on Windows

---

libsql/src/sync.rs
libsql/src/sync/test.rs

Currently, we have a bug where each `push` request creates a new sync session in the server. Each push request can send up to 128 frames.
However, if a transaction spans more than 128 frames, then it needs to reuse the same sync session. Otherwise, the first push will succeed, but the rest of the pushes will fail due to the write lock held by the previous session.
This patch reuses the sync session. The way we do this is by using batons. If the server sends a baton, then we pass it back. Reusing the same baton ensures that we are using the same sync session.

Fix large sync sessions by reusing the same session

---

libsql/src/local/connection.rs

The call is redundant and seems to becausing issues in cases where connection is already closed.

libsql: Don't clear authorizer in disconnect()

---

libsql-ffi/Cargo.toml
libsql-ffi/build.rs
libsql-sqlite3/src/wal.c
rust-toolchain.toml

Currently we report a checkpoint is finished only when `mxSafeFrame == mxFrame` in wal
it is useful to have finish callback to be triggered in case any work moving frames was accomplished.

feature to move checkpoint callback if any frames is written

---

libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/sync.rs

This adds sync interval support for synced databases, which use the V2 sync protocol.
Fixes #2059

Add sync interval support for synced databases

---

libsql-server/tests/standalone/mod.rs
libsql/src/hrana/connection.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/mod.rs
libsql/src/replication/connection.rs
libsql/src/sync/connection.rs
libsql/src/wasm/mod.rs

Add `columns` information for Hrana Statements

---

libsql/src/database/builder.rs

fixes #2064 
this patch fixes the regression introduced in https://github.com/tursodatabase/libsql/pull/2055
`bootstrap_db` calls the `export` endpoint and bootstraps the db
quickly. If we call `connect` before calling `bootstrap_db`, it will
create a local `.db` file and sync falls back to incremental
bootstrap which is super slow

Fix synced database boostrapping

---

libsql/src/database/builder.rs
libsql/src/sync.rs

Prevent holding lock to context between sync interval ticks

---

libsql/src/database/builder.rs

fixes #2087
Instead of using `/sync/0/0/0` use info endpoint which is supported by the new server only, to identify the sync protocol URL

Use `/info` to probe if the server supports `sync`

---

libsql/src/replication/remote_client.rs
libsql/src/sync.rs

Previously, we pulled frames one by one. This patch changes it pull frames in batches. Currently, the batch size is set to 128 (the maximum supported by the server)

Optimise `sync_pull` to pull frames in batches

---

Cargo.lock
libsql-ffi/Cargo.toml
libsql-ffi/build.rs

This also implements everything that is needed for cross-compilation to various targets (including mobile).
Fixes encryption build for all targets: https://github.com/tursodatabase/libsql-c/actions/runs/15577857992

Simplify build script with cmake crate

---

libsql-ffi/build.rs

On macos, cp's `--no-preserve` option does not exist. It is enabled by default, and can be disabled with the explicit `-p` (preserve) flag. This lead libsql-ffi's build.rs to warn about an illegal option used:
```
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpSsvXx] source_file target_file
cp [-R [-H | -L | -P]] [-fi | -n] [-aclpSsvXx] source_file ... target_directory
```
This changeset makes sure the option is only passed in non `macos` target_os.
It seems like the build.rs file has had quite a lot of bugfixes over time, especially the CP function, so feel free to dismiss this PR if you're not comfortable landing it, as it's just a warning, and if the cp command does not work it will fallback to `copy_dir_all`.
I'm also lacking context on this library so if I'm …

Fix: fix osx cp warning.

---

libsql/Cargo.toml
libsql/examples/encryption_sync.rs
libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/hrana/hyper.rs
libsql/src/lib.rs
libsql/src/local/database.rs
libsql/src/sync.rs
libsql/src/sync/test.rs

This patch enables client to send encryption key header for encrypted databases.  The header we are required to send is `x-turso-encryption-key`.
To connect with encrypted database, either remote or offline write, you may use the builder pattern to provide the encryption context. Ex.:
```rust
let encryption = if let Ok(key) = std::env::var("LIBSQL_ENCRYPTION_KEY") {
Some(EncryptionContext {
key: EncryptionKey::Base64Encoded(key),
})
} else {
None
};
let db_builder =
Builder::new_synced_database(db_path, sync_url, auth_token).remote_encryption(encryption);
```
This patch also comes with a full example: https://github.com/avinassh/libsql/blob/5b95a1928b821855fced3880caf7871ce032c58b/libsql/examples/encryption_sync.rs

Update clients to interact with (new) server encrypted databases

---

libsql/src/connection.rs
libsql/src/database/builder.rs

Fixed typos in `connection.rs` and `database\builder.rs`

---

libsql/examples/encryption_sync.rs
libsql/src/database/builder.rs

In builder pattern, it is better to take the `Object` itself instead of `Option<Object>`. So 
```rust
pub fn remote_encryption(mut self, encryption_context: Option<EncryptionContext>) -> Builder<T> {}
```
changed to
```rust
pub fn remote_encryption(mut self, encryption_context: EncryptionContext) -> Builder<T> {}
```
This follows the existing practices, and consistent with the code.

Update `remote_encryption` builder to take encryption object instead of option

---

libsql/src/local/connection.rs
libsql/src/sync.rs

Basically, right now, embedded replica will fail if WAL reached size of more than `4120` frame (familiar number, huh?).
The issue is that in the Rust API we pass `frame.len()` as a `frame_no` and 0 as a `frame.len()` 🤪
The failure happens because `wal_insert` C code will check frame for conflict in case when `if (iFrame <= mxFrame)` and then try to allocate `nBuf - 24` bytes (where `nBuf` equals to `0` due to bug)
This PR fixes this bug and also added simple test to check the API.

Fix wal api ffi

---

libsql/src/local/connection.rs
libsql/src/sync.rs

Pull logic used invalid property of WAL in its implementation and was written under assumption that any frames written to WAL are durable.
This is not true in case of frames written for unfinished transaction, because such frames will be omitted by any SQLite connection except from the one which created them. So, in case of restart - we will "loose" these frames, but `durable_frame_num` will incorrectly state that we already written "missed" portion of WAL.
This PR fix this issue and make pull to persist information about "durable_frame_num" only at transaction boundaries.

Fix durable frame tracking to follow transaction boundaries

---

libsql/src/local/connection.rs
libsql/src/sync.rs

Otherwise, if client is on the checkpoint boundary and immediately get checkpoint command - we will crash with assertion
```
assert!(
!insert_handle.in_session(),
"WAL transaction must be finished"
);
```

do not open wal session from the beginning - wait for pulled frames

---

.github/workflows/rust.yml
libsql-server/tests/standalone/mod.rs
libsql/benches/benchmark.rs
libsql/examples/deserialization.rs
libsql/examples/example.rs
libsql/examples/example_v2.rs
libsql/examples/flutter.rs
libsql/src/connection.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/mod.rs
libsql/src/hrana/stream.rs
libsql/src/local/impls.rs
libsql/src/replication/connection.rs
libsql/src/statement.rs
libsql/src/sync/connection.rs
libsql/src/sync/statement.rs
libsql/src/wasm/mod.rs
libsql/tests/integration_tests.rs

The SQLite connection and statement objects are thread-safe. Let's mark more Rust methods as immutable so that applications don't need to keep wrapping `Connection` and  `Statement` with `Mutex`, for example, for mutability.

More immutable methods

---

libsql/src/database.rs
libsql/src/sync/connection.rs
libsql/src/sync/statement.rs

The optimization attempts to reduce pulling when an application is writing. However, the logic is embedded in prepare(), which is totally wrong because a statement can be reused. Let's remove the optimization as incorrect.
Refs: tursodatabase/turso-cloud#5

libsql: Remove lazy pulling optimization

---

libsql/src/database.rs
libsql/src/sync.rs

This fixes the following issues:
- If we fail to boostrap at database open, return an error instead of allowing local files to be in inconsistent state. Note that we ignored boostrap errors to avoid probing the remote for generation when offline, but that I fixed now in a different way.
- If we have a database file, but no metadata, return an error instead of allowing inconsistent state.

libsql: Fix bootstrap error handling

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs
libsql/src/connection.rs
libsql/src/errors.rs
libsql/src/local/impls.rs
libsql/src/replication/connection.rs
libsql/src/sync/connection.rs

- Exposes the API to the `Connection` struct
- Adds `libsql_set_reserved_bytes` and `libsql_get_reserved_bytes` to `libsql.h`

Add get/set reserved bytes to C bindings
