tursodatabase/libsql

doc/libsql_extensions.md

The paragraph points to our blog post and also briefly explains how to implement your own function in Rust.

doc: expand "how to implement user-defined functions" paragraph

---

ext/udf/wasmedge_bindings.c

I'm from WasmEdge.
This PR init wasi and load wasmedge plugin.

wasmedge: init wasi and load plugin

---

src/rust/libsql-shell/src/main.rs

It allows to execute multiple statements and also prevents sending empty statement to execution which resulted in unhandled error.
---
It is just a simple for loop, we could move it's logic to separate function, what do you think?

Parse and execute multiple statements at once

---

src/rust/libsql-shell/src/main.rs

Test + fixes that are result of testing + linting.

Add test for StrStatements iterator & fixes

---

src/rust/libsql-shell/src/main.rs

Provide simple foundation for adding new shell commands.
Add `quit` command and `tables` command to provide example of one that can take arguments.
Related-to: #142

Add quit and tables command

---

README.md

Link for the WASM blog is broken

fix blog link

---

crates/bindings/c/src/lib.rs
crates/bindings/python/src/lib.rs
crates/bindings/python/tests/test_basic.py
crates/core/benches/benchmark.rs
crates/core/examples/example.rs
crates/core/src/connection.rs
crates/core/src/lib.rs
crates/core/src/params.rs
crates/core/src/rows.rs
crates/core/src/statement.rs
crates/core/tests/integration_tests.rs

This patch adds initial support for positional parameters to the libSQL core and the Python bindings.

libSQL API positional parameter support

---

crates/Cargo.toml
crates/README.md

Don't strip release symbols and document how to run Criterion with perf.

libsql/core: Improve benchmark perf experience

---

.gitignore
crates/libsql-sys/Cargo.toml
crates/libsql-sys/build.rs
crates/libsql-sys/bundled/src/sqlite3.h
crates/libsql-sys/bundled/src/sqlite3ext.h

The default build script now recompiles the amalgamation file from bundled/src/sqlite3.c.

crates/core: allow amalgamation-driven builds

---

crates/core/src/database.rs
crates/replication/src/lib.rs
crates/replication/src/replica/hook.rs

Otherwise it's hard to call it...

libsql: Make Database::sync() async

---

crates/replication/Cargo.toml

libsql/core: Add "rt-multi-thread" feature to Tokio

---

src/vdbe.c

vdbe: bump ROWS_READ in ORDER BY x DESC queries

---

crates/core/src/lib.rs

When running `cargo test --all` I was seeing these test failures so I thought I'd try to fix them to learn more about the project.

libsql/core: Fix rustdoc tests

---

crates/bindings/c/include/libsql.h
crates/bindings/c/src/lib.rs
crates/bindings/c/src/types.rs
crates/bindings/go/libsql.go
crates/bindings/go/libsql_test.go
crates/core/src/lib.rs
crates/core/src/params.rs
crates/core/src/rows.rs

This PR is missing proper error handling. I will add that in the following PRs.

Implement more Golang bindgs

---

crates/core/src/lib.rs
crates/core/src/params.rs

Closes https://github.com/libsql/libsql/issues/268

libsql/core: Add `params_from_iter`

---

crates/replication/src/client.rs

libsql/replication: Remove grpc decoding limits

---

crates/core/src/connection.rs
crates/core/src/database.rs
crates/core/src/errors.rs
crates/core/src/params.rs
crates/core/src/rows.rs
crates/core/src/statement.rs
crates/core/src/v2/hrana.rs
crates/core/src/v2/rows.rs
crates/replication/src/lib.rs

Step 0 towards migrating to v2 as the main api.

chore: apply clippy fixes

---

crates/core/Cargo.toml
crates/core/src/lib.rs
crates/core/src/v1/connection.rs
crates/core/src/v1/database.rs
crates/core/src/v2/mod.rs

This adds open_with_flags() associate function to Database to turn on read-only mode, for example.

libsql/core: Add Database::open_with_flags()

---

crates/core/examples/replica.rs
crates/core/src/errors.rs
crates/core/src/v1/database.rs
crates/core/src/v1/mod.rs
crates/core/src/v1/params.rs
crates/core/src/v1/rows.rs
crates/core/src/v1/statement.rs
crates/core/src/v2/rows.rs
crates/core/src/v2/statement.rs
crates/replication/src/client.rs
crates/replication/src/lib.rs

This adds write delegation support for row response queries.

libsql/replication: Add query write delegation

---

crates/core/src/v1/connection.rs
crates/core/src/v2/mod.rs
crates/replication/src/client.rs
crates/replication/src/lib.rs

libsql/replication: Add `execute_batch` remote write

---

crates/core/src/v2/statement.rs

libsql/core: Fix v2 Statement::execute

---

crates/replication/src/lib.rs

If users try to replicate frames through sync_frames(), and the database has already seen them, the replication is reported to succeed. That allows calling sync_frames() multiple times, e.g. by continuously scanning a directory.

crates/core: skip replicating already seen frames

---

crates/core/src/v1/params.rs

This PR adds a bunch of utility methods to work with `Value` and `ValueRef`.

add value utility methods

---

crates/core/src/v1/database.rs
crates/replication/src/lib.rs

libsql/replication: Lazily init metadata

---

crates/core/benches/benchmark.rs

Make it easy to run specific benchmarks and also add benchmarks for local replicas.

libsql/core: Benchmark improvements

---

crates/core/src/replication/connection.rs

We still need to be careful when preparing those statements locally inside a write transaction.
I verified manually that readonly statements that happen within transaction context are properly write-delegated:
```sql
BEGIN IMMEDIATE
SELECT 42 -- gets properly delegated as well, as it should
COMMIT
```

replication: bring back preparing readonly statements locally

---

crates/core/Cargo.toml
crates/core/src/replication/client.rs

Fixes https://github.com/tursodatabase/libsql/issues/415

libsql/core: Move to webpki roots instead of native

---

crates/core/src/lib.rs

fixed:Link to libSQL API examples doesn't look right.

---

libsql/src/rows.rs
libsql/src/value.rs

This adds support for `bool` and `Option<T>` conversion with `Value` and `FromValue`

libsql: Support `bool` and `Option<T>` conversion for `Value` and `FromValue`

---

libsql-server/src/replication/primary/frame_stream.rs

After this patch, we do not cut off streams early in the middle of a transaction. And that's because we currently cannot assume that our clients can apply partial transactions correctly.

replication: do not preempt streams at transaction boundary

---

libsql-shell/src/main.rs

If the given statement is empty like ` ;`, `run_statement` panicks because in this case rusqlite would return an `Err(SqliteFailure(...))` but we `unwrap` it.
```
$ ./target/debug/libsql
libSQL version 0.2.0
Connected to a transient in-memory database.
libsql>  ;
thread 'main' panicked at libsql-shell/src/main.rs:407:28:
called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: ApiMisuse, extended_code: 21 }, Some("not an error"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This commit fixes the panic with the following changes:
- Prevent the iterator of `StrStatements` from returning empty statements.
- Skip a row if returned by rusqlite if it's `Err(...)`.
With the above changes:
```
$ cargo build && ./target/debug/libsql
Finished dev …
```

libsql-shell: fix panic on empty statement

---

libsql-shell/src/main.rs

Related to #143.
This is how it runs like:
```
$ ./target/debug/libsql --cmd '.show' --cmd '.echo on' --cmd '.show' --cmd '.quit'
libSQL version 0.2.0
Connected to a transient in-memory database.
echo: false
eqp: false
explain: Auto
headers: true
mode: Column
nullvalue: ""
output: stdout
colseparator:
rowseparator:
stats: Off
width: [0, 0, 0, 0, 0]
filename: :memory:
echo: true
eqp: false
explain: Auto
headers: true
mode: Column
nullvalue: ""
output: stdout
colseparator:
rowseparator:
stats: Off
width: [0, 0, 0, 0, 0]
filename: :memory:
```
I notice two nuances between this and the original libsql:
- the original libsql seems to ignore `.quit`
- the original libsql reports error if the command has leading spaces
I can update the PR to maintain parity if it's desired.

libsql-shell: add --cmd option

---

README.md

Small bugfix for wrong link to libsql-server

Small bugfix for wrong link to libsql-server

---

libsql-sys/build.rs

This removes the precompiled static libraries in favor of compiling sqlite's bundled amalgamated file each time. The change here is to only run bindgen if the proper env var is set. This allows us to not have an implicit dependency on `libclang` version 3.5+ when outside of the main repo (aka libsql-js).

Remove precompiled libs and make bindgen optional

---

libsql-server/src/replication/snapshot.rs

leftover from switch to async.

remove block_on in async function

---

libsql-server/src/hrana/proto.rs
libsql-server/src/hrana/result_builder.rs
libsql-server/src/lib.rs
libsql-server/tests/hrana/batch.rs
libsql-server/tests/hrana/mod.rs
libsql-server/tests/hrana/snapshots/tests__hrana__batch__sample_request.snap
libsql-server/tests/tests.rs

- fix hrana batch replication index
- test hrana batch correct sample query

fix batch replication index

---

libsql-shell/src/main.rs

libsql-shell: add --nofollow flag

---

libsql-server/src/hrana/stmt.rs
libsql-server/tests/standalone/mod.rs
libsql-server/tests/standalone/snapshots/tests__standalone__basic_query_fail.snap
libsql-server/tests/standalone/snapshots/tests__standalone__basic_query_fail.snap.new

Fix bug where hrana didn't catch rusqlite errors

fix hrana handling of rusqlite error

---

bottomless-cli/Cargo.toml
bottomless-cli/src/main.rs
bottomless-cli/src/replicator_extras.rs
bottomless/Cargo.toml
bottomless/src/lib.rs
bottomless/src/read.rs
bottomless/src/replicator.rs
bottomless/src/transaction_cache.rs
bottomless/src/wal.rs

Convenience function for manual restoration.

bottomless-cli: add restoring from a directory

---

Cargo.lock
libsql-server/src/hrana/http/request.rs

This PR adds a limit the size of stored statements to 5KB.

limit stored statement size

---

libsql-server/src/http/admin/mod.rs
libsql-server/src/http/user/mod.rs
libsql-server/src/lib.rs

This PR gracefully shutsdown any pending HTTP connection on shutdown.

Gracefully shutdown http services

---

libsql-replication/src/meta.rs
libsql-server/tests/embedded_replica/mod.rs
libsql/src/local/database.rs
libsql/src/replication/remote_client.rs

This PR fixes embedded replicas reset when trying to replicate an incompatible log.

embedded replica reset

---

vendored/sqlite3-parser/src/lexer/scan.rs
vendored/sqlite3-parser/src/parser/parse.y
vendored/sqlite3-parser/third_party/lemon/lempar.rs

sqlite3-parser: replace debug! with trace!

---

libsql-replication/src/injector/mod.rs

Fixes a bug that happened when the injector had an error, and would refuse to make progress because it was still in a transaction state. Now flush errors are caught and the connection is rolledback.

rollback injector on error

---

Cargo.toml
libsql-sqlite3/ext/crr/rs/core/src/create_cl_set_vtab.rs
libsql-sqlite3/ext/crr/rs/core/src/unpack_columns_vtab.rs
libsql-sqlite3/ext/crr/src/changes-vtab.c

following up on: https://github.com/tursodatabase/libsql/pull/625#event-10980735433 & #632

move libsql specific vtab methods to fix #632

---

libsql-server/src/hrana/http/mod.rs

This PR changes HTTP error status code for requests that failed because underlying Hrana stream has expired. Change made according discussion and suggestions by @LucioFranco and @athoscouto

modified http response code for Hrana's expired stream errors from 500 to 400

---

libsql-replication/src/replicator.rs
libsql-replication/src/rpc.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/replication/replicator_client.rs
libsql-server/src/rpc/mod.rs
libsql-server/src/rpc/proxy.rs
libsql-server/src/rpc/replication_log.rs
libsql-server/tests/cluster/replication.rs
libsql/src/replication/remote_client.rs

This PR improves replication error handling. I added an explicit state machine to handle replication steps, that made is easy to inject replication error, and test many error cases.

improve replication error handling

---

.github/workflows/nemesis.yml

This PR changes nemesis to run on main branch, at fixed interval schedule of 4 hours.
I have also updated it to run on Github hosted runner

nemesis test: switch to cron based schedule

---

libsql-sqlite3/src/sqliteInt.h
xtask/src/main.rs

We're not committing to SEH support due to virtual WAL incompatibility reasons.

windows,sqliteInt: skip SEH

---

bottomless-cli/src/main.rs

Otherwise it panics at https://github.com/tursodatabase/libsql/blob/6ac769e/bottomless-cli/src/main.rs#L195

validate namespace param starts with `ns-`

---

libsql-ffi/src/lib.rs

safe page header iter

---

bottomless/src/replicator.rs

In case if database snapshot fails, include file path in the logs.

bottomless db snapshot: add more logging

---

libsql-sqlite3/src/pager.c
libsql-sqlite3/src/wal.c

Those are really weird internally, and assume that the db path string you pass as an argument resides in a very specific place in memory, preceded by 4 zero bytes, and followed by journal and wal names. The WALv2 rework broke this magic assumption, so we hereby restore it.
As follow-up, we should move this filename management to virtual WAL, because with virtual WAL implementations you sometimes don't even have a notion of "WAL file path".

libsql-sqlite3: restore sqlite3_filename_* API semantics

---

libsql-server/src/hrana/proto.rs
libsql-server/src/hrana/result_builder.rs
libsql-server/tests/hrana/snapshots/tests__hrana__batch__sample_request.snap

Return the replication index in a statement response

return replication index in hrana StmtResp

---

libsql-server/src/connection/libsql.rs
libsql-server/src/namespace/fork.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/mod.rs

... some are still left, related to https://github.com/rust-lang/rust-clippy/issues/5812

clippy fixes

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/replication/connection.rs
libsql/src/value.rs

This is a temporary fix. The real fix is to migrate to the streaming protocol.

Fix bincode deserialize error

---

.github/workflows/release-libsql-server.yml
Cargo.toml

Update cargo dist to 0.7.0

---

libsql/src/value.rs

Adds a boolean visitor for value deserializer (not sure why i didn't add this previously)

libsql: Add boolean visitor

---

libsql/examples/deserialization.rs

Bring back the Serde deserialization example

---

bottomless/src/bottomless_wal.rs
libsql-ffi/bundled/bindings/bindgen.rs
libsql-ffi/bundled/bindings/session_bindgen.rs
libsql-ffi/bundled/src/sqlite3.h
libsql-replication/src/injector/injector_wal.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-sqlite3/src/pager.c
libsql-sqlite3/src/wal.c
libsql-sqlite3/src/wal.h
libsql-sqlite3/test/rust_suite/src/lib.rs
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-sys/src/wal/ffi.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs

This is the 2nd PR in the unification series.
This PR introduces the checkpoint callback, that is called with every frame inserted in the WAL, and once more on a successfull checkpoint. This callback is later used to build snapshots on checkpoints.

Introduce checkpoint callback

---

libsql-server/src/query_analysis.rs
libsql/src/parser.rs

libsql-server: Allow `index_info` pragma

---

libsql-server/src/replication/primary/logger.rs

We were commiting for every page on recover, that doesn't make sense.

only commit once on recover

---

libsql-server/Cargo.toml
libsql-server/src/replication/primary/replication_logger_wal.rs

There are issues with the build process for encryption, so i'm disabling it until @psarna figures it out

disable replication

---

bindings/c/src/lib.rs
libsql-ffi/build.rs
libsql-replication/src/snapshot.rs
libsql-server/src/connection/config.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-server/src/rpc/proxy.rs
libsql-server/src/rpc/replica_proxy.rs
libsql-server/src/rpc/replication_log.rs
libsql-server/src/stats.rs
libsql-server/src/test/bottomless.rs
libsql-server/tests/common/mod.rs
libsql-server/tests/standalone/mod.rs
libsql-sys/src/connection.rs
libsql-sys/src/hrana/proto.rs
libsql-sys/src/lib.rs
libsql/src/database.rs
libsql/src/hrana/hyper.rs
libsql/src/hrana/mod.rs
libsql/src/value.rs
libsql/tests/integration_tests.rs

run clippy

---

docs/BUILD-RUN.md

Ask users to change into the right directory.

minor fix for BUILD-RUN.md

---

libsql-server/src/query_analysis.rs

insensitive pragma comparisons

---

bottomless/src/bottomless_wal.rs
libsql-ffi/bundled/bindings/bindgen.rs
libsql-ffi/bundled/bindings/session_bindgen.rs
libsql-ffi/bundled/src/sqlite3.h
libsql-ffi/src/lib.rs
libsql-replication/src/injector/headers.rs
libsql-replication/src/injector/injector_wal.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/replication_wal.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-sqlite3/ext/wasi/vfs.c
libsql-sqlite3/src/sqlite.h.in
libsql-sqlite3/src/wal.c
libsql-sqlite3/src/wal.h
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-sys/src/wal/either.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs

This is a series of small changes related to wal. After this is merged there won't be any C left necessary to merge the remaining code for unification.

Wal related changes

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/errors.rs
libsql/src/local/database.rs

closes https://github.com/tursodatabase/libsql/issues/427

libsql: add embedded replica freeze mode

---

Cargo.lock
libsql-sys/src/hrana/proto.rs

- fix missing default in hrana proto
- lockfile changed

fix hrana proto

---

libsql-server/src/replication/snapshot.rs

no regex parse snapshot

---

libsql-server/src/connection/config.rs
libsql-server/src/namespace/meta_store.rs

fix two bugs recovering metastore

recovery panic fix

---

libsql-sqlite3/doc/libsql_extensions.md

Updated libsql_extensions.md fix broken link

---

libsql-server/src/auth/authorized.rs
libsql-server/src/auth/user_auth_strategies/jwt.rs
libsql-server/tests/standalone/attach.rs
libsql-server/tests/standalone/auth.rs
libsql-server/tests/standalone/mod.rs
libsql-server/tests/standalone/utils.rs

Re allow old, malformed tokens with no claims

fix auth malformed token

---

libsql-server/src/query_analysis.rs
libsql-server/tests/standalone/attach.rs
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth_with_uuids-2.snap
libsql-server/tests/standalone/snapshots/tests__standalone__attach__attach_auth_with_uuids.snap

This patch comes with regression tests.

server: trim quotes in namespace string in attach statement

---

libsql-server/src/namespace/meta_store.rs

add a trigger to the `enqueued_tasks` temp table to remove the task there, when the task is updated in the task table.

trigger delete enqueued tasks

---

libsql-replication/src/meta.rs
libsql-server/src/namespace/mod.rs
libsql-server/tests/embedded_replica/mod.rs
libsql/src/database.rs
libsql/src/database/builder.rs

libsql: prevent database overwrite misuse

---

libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/mod.rs

Disable forking for a shared schema database

---

libsql-server/src/schema/scheduler.rs

scheduler.step is not cancel safe.

fix flaky shared schema test

---

libsql-replication/src/replicator.rs

Some more typo fixes in comments and messages.

Fixed typos in replicator

---

libsql-server/src/lib.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/schema/scheduler.rs

adds per namespace sentinel.
fix #1107

per-namespace sentinel

---

libsql-server/src/query_analysis.rs

catch parser panic until we can fix it

catch parser panic

---

libsql-server/src/error.rs
libsql-server/src/http/admin/mod.rs
libsql-server/src/namespace/meta_store.rs
libsql-server/src/namespace/store.rs
libsql-server/src/schema/db.rs
libsql-server/tests/namespaces/shared_schema.rs
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__schema_deletion-2.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__schema_deletion-3.snap
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__schema_deletion.snap

- fix schema deletion
- optional ns delete payload

Fix namespace deletion

---

libsql-server/src/connection/libsql.rs
libsql-server/src/connection/program.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/error.rs
libsql-server/src/namespace/fork.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/store.rs
libsql-server/src/schema/error.rs
libsql-server/src/schema/migration.rs
libsql-server/tests/namespaces/shared_schema.rs
libsql-server/tests/namespaces/snapshots/tests__namespaces__shared_schema__attach_in_migration_is_forbidden.snap

harden attach path resolution, and prevent attach in migration scripts

harden attach

---

vendored/sqlite3-parser/src/parser/parse.y

- fix parser error
- fix a bunch of parse panics

Fix parser panics

---

vendored/sqlite3-parser/src/parser/parse.y
vendored/sqlite3-parser/tests/regression.rs
vendored/sqlite3-parser/tests/regression_files/bad_table_arg1.sql
vendored/sqlite3-parser/tests/regression_files/bad_table_arg2.sql
vendored/sqlite3-parser/tests/regression_files/bad_table_arg3.sql
vendored/sqlite3-parser/tests/regression_files/on_missing_join.sql

- fix a bunch of parse panics
- add parser regression tests

parser regression tests

---

Cargo.lock
libsql-replication/src/injector/injector_wal.rs
libsql-server/Cargo.toml
libsql-server/src/connection/connection_manager.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/connection/mod.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/database/primary.rs
libsql-server/src/database/schema.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/replication_wal.rs
libsql-server/src/replication/primary/logger.rs
libsql-server/src/replication/primary/replication_logger_wal.rs
libsql-server/src/rpc/proxy.rs
libsql-server/src/rpc/replication_log.rs
libsql-server/src/rpc/streaming_exec.rs
libsql-sqlite3/test/rust_suite/src/virtual_wal.rs
libsql-sys/src/wal/either.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/sqlite3_wal.rs
libsql-sys/src/wal/wrapper.rs

write queue

---

libsql-server/src/connection/connection_manager.rs

This PR force the re-enqueueing of waiting connection when a checkpoint request > RESTART is received. This causes all the waiting connections to refresh their read marks, and not block the checkpoint anymore.

reenqueue stale reads on checkpoint

---

libsql-server/src/hrana/ws/conn.rs
libsql-server/src/hrana/ws/session.rs

deduplicated handling of hrana hello and repreated hello. Code is fully equivalent to the previous form. No change in logic.

Dedupe Hrana hello and repeated hello

---

.github/workflows/publish-server.yml

Builds of arm images are hanging/crashing.

Bump arm builder machine

---

.github/workflows/server-pr-images.yml

This patch updates the existing workflow to run when the workflow is manually triggered (workflow_dispatch event)

Add workflow_dispatch event trigger for PR images

---

libsql-server/src/connection/libsql.rs

We had two blocking RT by mistake, one without io enabled, causing panics

fix unused blocking rt

---

libsql-wal/src/segment/list.rs
libsql-wal/src/segment/sealed.rs

- segment list
- fix typo in comment
- rename SegmentLink to SegmentList
- fix bad refecent index for sealed segment lookup

fix bad index

---

Cargo.lock
libsql-wal/Cargo.toml
libsql-wal/src/segment/current.rs
libsql-wal/src/transaction.rs

add current segment and transaction to the wal.

libsql wal current segment

---

libsql-wal/src/lib.rs
libsql-wal/src/wal.rs

implement the sqlite Wal interface using the `SharedWal`

implement wal interface

---

README.md

LibSQL client for PHP reached 1.0.0

Update README.md: Add PHP client

---

Cargo.lock
Cargo.toml
libsql-server/Cargo.toml

- bump cargo dist
- bump libsql-server to 0.24.8

bump libsql server v0.24.8

---

Cargo.lock
bottomless2/Cargo.toml
bottomless2/src/job.rs
bottomless2/src/lib.rs
bottomless2/src/scheduler.rs

bottomless scheduler

---

libsql-server/src/schema/scheduler.rs

force checkpoint after schema migration db operation do make sure that the dbs get backed up quickly.

fix schema migration hang

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs

Add libsql_reset_stmt

---

bindings/c/include/libsql.h
bindings/c/src/lib.rs
bindings/c/src/types.rs

Define column types

---

Cargo.lock
libsql-ffi/build.rs
libsql-server/Cargo.toml
libsql-server/src/connection/connection_manager.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/connection/write_proxy.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/src/namespace/mod.rs
libsql-server/src/namespace/name.rs
libsql-server/src/schema/scheduler.rs
libsql-sys/src/connection.rs
libsql-sys/src/wal/mod.rs
libsql-sys/src/wal/wrapper.rs
libsql-wal/src/bottomless/job.rs
libsql-wal/src/name.rs
libsql-wal/src/segment/current.rs
libsql-wal/src/shared_wal.rs
libsql-wal/tests/oracle.rs

Basic integration of libsql-wal in sqld. Only the primary is supported right now, but it's still compatible with replicas with vanilla wal. Bottomless is not supported.
There are some tests failing with libsql-wal still (timeout issues in the simulation), i'll fix in a followup.

libsq wal integration

---

Cargo.lock
libsql-wal/Cargo.toml
libsql-wal/src/registry.rs
libsql-wal/src/segment/list.rs
libsql-wal/src/segment/mod.rs
libsql-wal/src/shared_wal.rs
libsql-wal/src/transaction.rs
libsql-wal/src/wal.rs

record the checkpointed frame no in shared wal

store checkpointed frameno in shared wal

---

libsql-wal/src/segment/current.rs

This optim resuses frames for pages already written during a transaction. This can save a significant amount of disk for very large txns.

libsql wal optim frame reuse

---

libsql-wal/src/bottomless/storage/fs.rs
libsql-wal/src/io/file.rs
libsql-wal/src/io/mod.rs

This adds a basic fs storage system, still a lot of work left on it just an initial pass to get started.

wal: add basic fs storage system

---

libsql/src/errors.rs
libsql/src/params.rs
libsql/src/rows.rs
libsql/src/value.rs

(small nit on the side and I feel bad for commenting on formatting, but could you check in a `.rustfmt.toml` that matches your style? I accidentally ran fmt on the repo by reflex... :hide: but I would also feel more confident in the consistency of my formatting if I could leave it to the robots)

Implement FromValue trait for byte arrays.

---

README.md

This README includes the new `libSQL` logo and updated links to SDKs, Docs, Discord and more.

docs(readme): new libsql logo

---

libsql-server/src/http/user/listen.rs

It was missing the query string

Fix primary redirect on listen endpoint

---

Cargo.lock
libsql-server/Cargo.toml
libsql-server/src/main.rs

let's see if this helps with fragmentation

enable mimalloc

---

.github/workflows/publish-server.yml
.github/workflows/server-pr-images.yml
Dockerfile

build an image with debug symbols, and make PR images ship with debug symbols too

build sqld debug

---

libsql-server/src/namespace/store.rs
rust-toolchain.toml

fix panic on delete namespace

---

libsql-storage/src/local_cache.rs

- Changed transaction table to use `(txn_id, page_no)` as composite primary key
- Updated `insert_frame` to ignore unique constraint violation since frames are immutable
- Change `insert_page` method to upsert

fix: minor bug issues with the cache tables

---

.github/workflows/storage-server-images.yml
libsql-storage-server/Dockerfile

Dockerfile is inspired from https://github.com/tursodatabase/libsql/blob/main/Dockerfile and I have tested the workflow in my fork.

Add Dockerfile and Github action for Storage Server

---

libsql-server/src/connection/write_proxy.rs
libsql-server/tests/cluster/replication.rs

- **add test**
- **fix bug when updating autocommit status in write proxy**

fix bad autocommit

---

libsql-replication/src/replicator.rs
libsql-server/src/replication/replicator_client.rs

change log level to debug for replicator logs

---

libsql-server/src/http/user/listen.rs

Make it return SSE headers, so proxies know that the response is a stream.
Make action query parameters optional, so users aren't forced to specify them always.

Improve the listen endpoint

---

libsql-server/src/namespace/mod.rs

Current code trim lines from dump which leads too incorrect statements which ending comments:
So, next example will become single line incorrect statement: `CREATE TABLE (id INTEGER -- comment);`
```
CREATE TABLE (
id INTEGER -- comment
);
```
This PR fixes this and preserve original lines + add bad line number in the error to simplify issue resolution process

preserve original lines during dump load in order to not break around comments

---

libsql-server/src/http/user/mod.rs

This is caused by a fixed issue on tower-http [1]. We can't update right now, because it requires us to change too much logic. The work around is to avoid compressing SSE responses until we update tower.
[1] https://github.com/tower-rs/tower-http/issues/420

Skip compression on SSE responses because it breaks streaming

---

Cargo.lock
vendored/sqlite3-parser/Cargo.toml
vendored/sqlite3-parser/third_party/lemon/lempar.rs

port of https://github.com/gwenn/lemon-rs/pull/59

remove smallvec from parser

---

libsql-wal/src/lib.rs
libsql-wal/src/storage/backend/s3.rs
libsql-wal/src/storage/error.rs

- **add LIBSQL_MAGIC number const**
- **update InvalidIndex error**
- **add SegmentIndexHeader**
- **store segment index header to s3**
- **verify segment header when downloading from s3**

segment index header

---

libsql-server/src/rpc/proxy.rs

fix proxy describe impl when the remote is a schema db.

fix describe proxy impl

---

libsql-wal/src/replication/replicator.rs

followup to review addign some comments

add replicator comment

---

libsql-wal/src/storage/async_storage.rs
libsql-wal/src/storage/error.rs
libsql-wal/src/storage/job.rs
libsql-wal/src/storage/mod.rs
libsql-wal/src/storage/scheduler.rs

Type erase confic type, making code simpler to read

type erase override config

---

libsql-sqlite3/src/vectorIndex.c
libsql-sqlite3/test/libsql_vector_index.test

During first iterations of vector search I deliberately disabled parting indexing for vectors in order to narrow down scope of the feature.
Turned out, that partial indexing works fine with current vector search index and we can just enable it safely
Plus, user showed interest in such feature: https://discord.com/channels/933071162680958986/1270939331619455070/1270999193707872348

Vector search allow partial index

---

libsql-replication/src/replicator.rs
libsql/src/replication/mod.rs

Retry primary handshake 3 times instead of 100 in embedded replicas

---

libsql-server/src/namespace/meta_store.rs

There was a blocking call to sqlite in the metastore initialization that could cause a panic because it would call runtime blocking methods internally.

fix blocking sqlite call in meta store initialization

---

libsql-server/Cargo.toml
libsql-server/src/lib.rs

enable HTTPS for durable wal storage

https connector for durable storage

---

libsql-server/src/http/user/mod.rs
libsql-server/src/namespace/name.rs

Improve logging for invalid namespace to better understand the source of the error.

improve logging for invalid namespaces

---

bottomless/src/replicator.rs

Follow up after https://github.com/tursodatabase/libsql/pull/1692
Function `snapshot_main_db_file` return `JoinHandle` - so it returns almost immediately and we need to measure S3 upload time inside the join handle

we need to measure upload time inside the handle because function will return almost immediately

---

libsql-server/src/bottomless_migrate.rs
libsql-server/src/lib.rs
libsql-server/src/main.rs
libsql-server/src/namespace/meta_store.rs
libsql-wal/benches/benchmarks.rs
libsql-wal/src/bins/shell/main.rs
libsql-wal/src/error.rs
libsql-wal/src/io/mod.rs
libsql-wal/src/lib.rs
libsql-wal/src/registry.rs
libsql-wal/src/segment/list.rs
libsql-wal/src/segment/mod.rs
libsql-wal/src/storage/backend/s3.rs
libsql-wal/tests/flaky_fs.rs
libsql-wal/tests/oracle.rs

This PR implements the migration from bottomless to libsql-wal.

bottomless libsql wal migration

---

libsql-server/tests/embedded_replica/mod.rs
libsql/src/replication/mod.rs

Fixes an issue where a returned `Replicated#frames_synced` will continuously increment based off the `replicator.frames_synced()` even if no new frames have synced.

Only add to last_frames_synced if frames did change.

---

libsql-server/src/connection/legacy.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/lib.rs
libsql-wal/src/segment/current.rs

libsql wal fixes

---

libsql-server/src/main.rs

disable metrics

---

libsql-wal/src/storage/backend/s3.rs

There was a bug where the last segment chunk was not sent as part of the multipart upload

fix multipart upload empty payload

---

libsql-server/src/rpc/streaming_exec.rs

There was a stray debug timeout atrificially creating latency on query proxy

remove debug timeout

---

libsql-server/src/wal_toolkit.rs
libsql-wal/src/shared_wal.rs
libsql-wal/src/storage/compaction/mod.rs
libsql-wal/src/storage/compaction/strategy/identity.rs
libsql-wal/src/storage/compaction/strategy/log_strategy.rs
libsql-wal/src/storage/compaction/strategy/mod.rs
libsql-wal/src/storage/compaction/strategy/snapshots/libsql_wal__storage__compaction__strategy__tier_reduction__test__partition_tiered-2.snap
libsql-wal/src/storage/compaction/strategy/snapshots/libsql_wal__storage__compaction__strategy__tier_reduction__test__partition_tiered.snap
libsql-wal/src/storage/compaction/strategy/snapshots/libsql_wal__storage__compaction__strategy__tiered__test__partition_tiered-2.snap
libsql-wal/src/storage/compaction/strategy/snapshots/libsql_wal__storage__compaction__strategy__tiered__test__partition_tiered.snap
libsql-wal/src/storage/compaction/strategy/tiered.rs
libsql-wal/src/storage/mod.rs

This PR introduces the Tiered compaction strategy as an effort to make compaction more efficient

tiered compaction

---

libsql-replication/src/injector/libsql_injector.rs
libsql-server/src/connection/connection_manager.rs
libsql-server/src/connection/libsql.rs
libsql-server/src/namespace/configurator/libsql_fork.rs
libsql-server/src/replication/replicator_client.rs
libsql-server/src/rpc/replication/libsql_replicator.rs
libsql-wal/benches/benchmarks.rs
libsql-wal/src/checkpointer.rs
libsql-wal/src/lib.rs
libsql-wal/src/registry.rs
libsql-wal/src/replication/injector.rs
libsql-wal/src/replication/replicator.rs
libsql-wal/src/shared_wal.rs
libsql-wal/src/transaction.rs
libsql-wal/src/wal.rs

A series of refactor to libsql-wal

small refactors

---

libsql-ffi/build.rs

Fix for https://github.com/tursodatabase/libsql/issues/1657

fix libsql-ffi build.rs usage of cp command on Windows

---

Cargo.lock
libsql/Cargo.toml

I don't what more is required. I tried to go throw read me for contribution guideline but can't find one. I just needed to updated worker version to match latest. Build is working in `WSL` . Do let me know if any further checks or correction is required.

Worker version updated to latest 0.4.1

---

bindings/c/example.c

This example now becomes similar to `libsql/examples/offline_writes.rs` and allows testing offline writes and C bindings integration.

Make C bindings example do sync

---

libsql-ffi/build.rs

Add sqlite3 includes to sqlean

---

libsql/src/database.rs
libsql/src/database/builder.rs
libsql/src/lib.rs

Use offline database database when sync API is available

---

libsql/src/sync.rs

This makes HTTP->HTTPS redirect work

Support redirects in sync

---

Cargo.lock

I regenerated the lockfile and bottomless restore tests started to fail. Therefore, let's revert back to a known good state.

Revert Cargo.lock
